// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: msg_with_ctrl.proto

package wlst_pb2

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

//数据服务和通讯服务传输格式
type MsgWithCtrl struct {
	//协议头信息
	Head *Head `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	//协议参数
	Args *Args `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`
	//系统级别协议集
	Syscmds *SysCommands `protobuf:"bytes,3,opt,name=syscmds,proto3" json:"syscmds,omitempty"`
	// 设备升级公共协议
	Passthrough *Passthrough `protobuf:"bytes,99,opt,name=Passthrough,json=passthrough,proto3" json:"Passthrough,omitempty"`
	//终端协议集
	WlstTml *WlstTerminal `protobuf:"bytes,100,opt,name=wlst_tml,json=wlstTml,proto3" json:"wlst_tml,omitempty"`
	//模块协议集
	WlstCom_0000 *WlstCom_0000 `protobuf:"bytes,1000,opt,name=wlst_com_0000,json=wlstCom0000,proto3" json:"wlst_com_0000,omitempty"`
	WlstCom_3E01 *WlstCom_3E01 `protobuf:"bytes,1001,opt,name=wlst_com_3e01,json=wlstCom3e01,proto3" json:"wlst_com_3e01,omitempty"`
	WlstCom_3E02 *WlstCom_3E02 `protobuf:"bytes,1002,opt,name=wlst_com_3e02,json=wlstCom3e02,proto3" json:"wlst_com_3e02,omitempty"`
	WlstCom_3E82 *WlstCom_3E82 `protobuf:"bytes,1003,opt,name=wlst_com_3e82,json=wlstCom3e82,proto3" json:"wlst_com_3e82,omitempty"`
	WlstCom_3E81 *WlstCom_3E02 `protobuf:"bytes,1004,opt,name=wlst_com_3e81,json=wlstCom3e81,proto3" json:"wlst_com_3e81,omitempty"`
	WlstCom_3E84 *WlstCom_3E84 `protobuf:"bytes,1005,opt,name=wlst_com_3e84,json=wlstCom3e84,proto3" json:"wlst_com_3e84,omitempty"`
	//第三方设备
	//江阴节能
	WxjyEsu_5500 *WxjyEsu_5500 `protobuf:"bytes,2000,opt,name=wxjy_esu_5500,json=wxjyEsu5500,proto3" json:"wxjy_esu_5500,omitempty"`
	WxjyEsuD500  *WxjyEsu_5500 `protobuf:"bytes,2001,opt,name=wxjy_esu_d500,json=wxjyEsuD500,proto3" json:"wxjy_esu_d500,omitempty"`
	WxjyEsuD700  *WxjyEsuD700  `protobuf:"bytes,2002,opt,name=wxjy_esu_d700,json=wxjyEsuD700,proto3" json:"wxjy_esu_d700,omitempty"`
	WxjyEsuD800  *WxjyEsuD800  `protobuf:"bytes,2003,opt,name=wxjy_esu_d800,json=wxjyEsuD800,proto3" json:"wxjy_esu_d800,omitempty"`
	// 安徽合肥,head.tver=2，若无特殊说明，cmd和公司终端相同，公司标示改为ahhf
	// 对时，采用终端Wlst_rtu_9300结构下发，应答采用Wlst_rtu_9200
	// 下发年时间，采用终端wlst_rtu_7060, 应答采用wlst_rtu_70e0
	// 开关量输出/输入/上下限设置/应答采用下面结构，cmd=ahhf.rtu.6804
	AhhfRtu_6804 *AhhfRtu_6804 `protobuf:"bytes,2101,opt,name=ahhf_rtu_6804,json=ahhfRtu6804,proto3" json:"ahhf_rtu_6804,omitempty"`
	// 开关灯，采用终端的wlst_rtu_4b00结构下发，应答采用wlst_rtu_cb00
	// 读取版本，采用ahhf.rtu.5c00命令，应答采用wlst_rtu_dc00
	// 读取开关量输出/输入/上下限参数,应答使用以下结构,cmd=ahhf.rtu.680a
	AhhfRtu_680A *AhhfRtu_6804 `protobuf:"bytes,2102,opt,name=ahhf_rtu_680a,json=ahhfRtu680a,proto3" json:"ahhf_rtu_680a,omitempty"`
	// 勃洛克单灯
	// 选测控制器数据
	BlkSlu_6891 *BlkSlu_6891 `protobuf:"bytes,2201,opt,name=blk_slu_6891,json=blkSlu6891,proto3" json:"blk_slu_6891,omitempty"`
	// 选测控制器数据应答
	BlkSlu_6892 *BlkSlu_6892 `protobuf:"bytes,2202,opt,name=blk_slu_6892,json=blkSlu6892,proto3" json:"blk_slu_6892,omitempty"`
	// 对时
	BlkSlu_6887 *BlkSlu_6891 `protobuf:"bytes,2203,opt,name=blk_slu_6887,json=blkSlu6887,proto3" json:"blk_slu_6887,omitempty"`
	// 对时应答
	BlkSlu_6888 *BlkSlu_6891 `protobuf:"bytes,2204,opt,name=blk_slu_6888,json=blkSlu6888,proto3" json:"blk_slu_6888,omitempty"`
	// 即时控制
	BlkSlu_6895 *BlkSlu_6895 `protobuf:"bytes,2205,opt,name=blk_slu_6895,json=blkSlu6895,proto3" json:"blk_slu_6895,omitempty"`
	// 即时控制应答
	BlkSlu_6896 *BlkSlu_6895 `protobuf:"bytes,2206,opt,name=blk_slu_6896,json=blkSlu6896,proto3" json:"blk_slu_6896,omitempty"`
	// 集中器定时设置
	BlkSlu_6889 *BlkSlu_6895 `protobuf:"bytes,2207,opt,name=blk_slu_6889,json=blkSlu6889,proto3" json:"blk_slu_6889,omitempty"`
	// 集中器定时设置应答
	BlkSlu_6890 *BlkSlu_6895 `protobuf:"bytes,2208,opt,name=blk_slu_6890,json=blkSlu6890,proto3" json:"blk_slu_6890,omitempty"`
	// 控制器回路数设置
	BlkSlu_6893 *BlkSlu_6891 `protobuf:"bytes,2209,opt,name=blk_slu_6893,json=blkSlu6893,proto3" json:"blk_slu_6893,omitempty"`
	// 控制器回路数设置应答
	BlkSlu_6894 *BlkSlu_6891 `protobuf:"bytes,2210,opt,name=blk_slu_6894,json=blkSlu6894,proto3" json:"blk_slu_6894,omitempty"`
}

func (m *MsgWithCtrl) Reset()      { *m = MsgWithCtrl{} }
func (*MsgWithCtrl) ProtoMessage() {}
func (*MsgWithCtrl) Descriptor() ([]byte, []int) {
	return fileDescriptor_17a284b5b5297b67, []int{0}
}
func (m *MsgWithCtrl) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgWithCtrl) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgWithCtrl.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgWithCtrl) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgWithCtrl.Merge(m, src)
}
func (m *MsgWithCtrl) XXX_Size() int {
	return m.Size()
}
func (m *MsgWithCtrl) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgWithCtrl.DiscardUnknown(m)
}

var xxx_messageInfo_MsgWithCtrl proto.InternalMessageInfo

func (m *MsgWithCtrl) GetHead() *Head {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *MsgWithCtrl) GetArgs() *Args {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *MsgWithCtrl) GetSyscmds() *SysCommands {
	if m != nil {
		return m.Syscmds
	}
	return nil
}

func (m *MsgWithCtrl) GetPassthrough() *Passthrough {
	if m != nil {
		return m.Passthrough
	}
	return nil
}

func (m *MsgWithCtrl) GetWlstTml() *WlstTerminal {
	if m != nil {
		return m.WlstTml
	}
	return nil
}

func (m *MsgWithCtrl) GetWlstCom_0000() *WlstCom_0000 {
	if m != nil {
		return m.WlstCom_0000
	}
	return nil
}

func (m *MsgWithCtrl) GetWlstCom_3E01() *WlstCom_3E01 {
	if m != nil {
		return m.WlstCom_3E01
	}
	return nil
}

func (m *MsgWithCtrl) GetWlstCom_3E02() *WlstCom_3E02 {
	if m != nil {
		return m.WlstCom_3E02
	}
	return nil
}

func (m *MsgWithCtrl) GetWlstCom_3E82() *WlstCom_3E82 {
	if m != nil {
		return m.WlstCom_3E82
	}
	return nil
}

func (m *MsgWithCtrl) GetWlstCom_3E81() *WlstCom_3E02 {
	if m != nil {
		return m.WlstCom_3E81
	}
	return nil
}

func (m *MsgWithCtrl) GetWlstCom_3E84() *WlstCom_3E84 {
	if m != nil {
		return m.WlstCom_3E84
	}
	return nil
}

func (m *MsgWithCtrl) GetWxjyEsu_5500() *WxjyEsu_5500 {
	if m != nil {
		return m.WxjyEsu_5500
	}
	return nil
}

func (m *MsgWithCtrl) GetWxjyEsuD500() *WxjyEsu_5500 {
	if m != nil {
		return m.WxjyEsuD500
	}
	return nil
}

func (m *MsgWithCtrl) GetWxjyEsuD700() *WxjyEsuD700 {
	if m != nil {
		return m.WxjyEsuD700
	}
	return nil
}

func (m *MsgWithCtrl) GetWxjyEsuD800() *WxjyEsuD800 {
	if m != nil {
		return m.WxjyEsuD800
	}
	return nil
}

func (m *MsgWithCtrl) GetAhhfRtu_6804() *AhhfRtu_6804 {
	if m != nil {
		return m.AhhfRtu_6804
	}
	return nil
}

func (m *MsgWithCtrl) GetAhhfRtu_680A() *AhhfRtu_6804 {
	if m != nil {
		return m.AhhfRtu_680A
	}
	return nil
}

func (m *MsgWithCtrl) GetBlkSlu_6891() *BlkSlu_6891 {
	if m != nil {
		return m.BlkSlu_6891
	}
	return nil
}

func (m *MsgWithCtrl) GetBlkSlu_6892() *BlkSlu_6892 {
	if m != nil {
		return m.BlkSlu_6892
	}
	return nil
}

func (m *MsgWithCtrl) GetBlkSlu_6887() *BlkSlu_6891 {
	if m != nil {
		return m.BlkSlu_6887
	}
	return nil
}

func (m *MsgWithCtrl) GetBlkSlu_6888() *BlkSlu_6891 {
	if m != nil {
		return m.BlkSlu_6888
	}
	return nil
}

func (m *MsgWithCtrl) GetBlkSlu_6895() *BlkSlu_6895 {
	if m != nil {
		return m.BlkSlu_6895
	}
	return nil
}

func (m *MsgWithCtrl) GetBlkSlu_6896() *BlkSlu_6895 {
	if m != nil {
		return m.BlkSlu_6896
	}
	return nil
}

func (m *MsgWithCtrl) GetBlkSlu_6889() *BlkSlu_6895 {
	if m != nil {
		return m.BlkSlu_6889
	}
	return nil
}

func (m *MsgWithCtrl) GetBlkSlu_6890() *BlkSlu_6895 {
	if m != nil {
		return m.BlkSlu_6890
	}
	return nil
}

func (m *MsgWithCtrl) GetBlkSlu_6893() *BlkSlu_6891 {
	if m != nil {
		return m.BlkSlu_6893
	}
	return nil
}

func (m *MsgWithCtrl) GetBlkSlu_6894() *BlkSlu_6891 {
	if m != nil {
		return m.BlkSlu_6894
	}
	return nil
}

// 中间层报警信息提交
type SubmitAlarm struct {
	// Head head = 1;
	AlarmView []*SubmitAlarm_AlarmView `protobuf:"bytes,2,rep,name=alarm_view,json=alarmView,proto3" json:"alarm_view,omitempty"`
}

func (m *SubmitAlarm) Reset()      { *m = SubmitAlarm{} }
func (*SubmitAlarm) ProtoMessage() {}
func (*SubmitAlarm) Descriptor() ([]byte, []int) {
	return fileDescriptor_17a284b5b5297b67, []int{1}
}
func (m *SubmitAlarm) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SubmitAlarm) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SubmitAlarm.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SubmitAlarm) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitAlarm.Merge(m, src)
}
func (m *SubmitAlarm) XXX_Size() int {
	return m.Size()
}
func (m *SubmitAlarm) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitAlarm.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitAlarm proto.InternalMessageInfo

func (m *SubmitAlarm) GetAlarmView() []*SubmitAlarm_AlarmView {
	if m != nil {
		return m.AlarmView
	}
	return nil
}

type SubmitAlarm_AlarmView struct {
	DtCreate  int64  `protobuf:"varint,1,opt,name=dt_create,json=dtCreate,proto3" json:"dt_create,omitempty"`
	ErrId     int32  `protobuf:"varint,2,opt,name=err_id,json=errId,proto3" json:"err_id,omitempty"`
	TmlId     int32  `protobuf:"varint,3,opt,name=tml_id,json=tmlId,proto3" json:"tml_id,omitempty"`
	LoopId    int32  `protobuf:"varint,4,opt,name=loop_id,json=loopId,proto3" json:"loop_id,omitempty"`
	LampId    int32  `protobuf:"varint,5,opt,name=lamp_id,json=lampId,proto3" json:"lamp_id,omitempty"`
	ErrCount  int32  `protobuf:"varint,6,opt,name=err_count,json=errCount,proto3" json:"err_count,omitempty"`
	DtRemove  int64  `protobuf:"varint,8,opt,name=dt_remove,json=dtRemove,proto3" json:"dt_remove,omitempty"`
	IsAlarm   int32  `protobuf:"varint,9,opt,name=is_alarm,json=isAlarm,proto3" json:"is_alarm,omitempty"`
	AlarmSrc  int32  `protobuf:"varint,10,opt,name=alarm_src,json=alarmSrc,proto3" json:"alarm_src,omitempty"`
	AlarmName string `protobuf:"bytes,11,opt,name=alarm_name,json=alarmName,proto3" json:"alarm_name,omitempty"`
	TmlName   string `protobuf:"bytes,12,opt,name=tml_name,json=tmlName,proto3" json:"tml_name,omitempty"`
	LoopName  string `protobuf:"bytes,13,opt,name=loop_name,json=loopName,proto3" json:"loop_name,omitempty"`
}

func (m *SubmitAlarm_AlarmView) Reset()      { *m = SubmitAlarm_AlarmView{} }
func (*SubmitAlarm_AlarmView) ProtoMessage() {}
func (*SubmitAlarm_AlarmView) Descriptor() ([]byte, []int) {
	return fileDescriptor_17a284b5b5297b67, []int{1, 0}
}
func (m *SubmitAlarm_AlarmView) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SubmitAlarm_AlarmView) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SubmitAlarm_AlarmView.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SubmitAlarm_AlarmView) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitAlarm_AlarmView.Merge(m, src)
}
func (m *SubmitAlarm_AlarmView) XXX_Size() int {
	return m.Size()
}
func (m *SubmitAlarm_AlarmView) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitAlarm_AlarmView.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitAlarm_AlarmView proto.InternalMessageInfo

func (m *SubmitAlarm_AlarmView) GetDtCreate() int64 {
	if m != nil {
		return m.DtCreate
	}
	return 0
}

func (m *SubmitAlarm_AlarmView) GetErrId() int32 {
	if m != nil {
		return m.ErrId
	}
	return 0
}

func (m *SubmitAlarm_AlarmView) GetTmlId() int32 {
	if m != nil {
		return m.TmlId
	}
	return 0
}

func (m *SubmitAlarm_AlarmView) GetLoopId() int32 {
	if m != nil {
		return m.LoopId
	}
	return 0
}

func (m *SubmitAlarm_AlarmView) GetLampId() int32 {
	if m != nil {
		return m.LampId
	}
	return 0
}

func (m *SubmitAlarm_AlarmView) GetErrCount() int32 {
	if m != nil {
		return m.ErrCount
	}
	return 0
}

func (m *SubmitAlarm_AlarmView) GetDtRemove() int64 {
	if m != nil {
		return m.DtRemove
	}
	return 0
}

func (m *SubmitAlarm_AlarmView) GetIsAlarm() int32 {
	if m != nil {
		return m.IsAlarm
	}
	return 0
}

func (m *SubmitAlarm_AlarmView) GetAlarmSrc() int32 {
	if m != nil {
		return m.AlarmSrc
	}
	return 0
}

func (m *SubmitAlarm_AlarmView) GetAlarmName() string {
	if m != nil {
		return m.AlarmName
	}
	return ""
}

func (m *SubmitAlarm_AlarmView) GetTmlName() string {
	if m != nil {
		return m.TmlName
	}
	return ""
}

func (m *SubmitAlarm_AlarmView) GetLoopName() string {
	if m != nil {
		return m.LoopName
	}
	return ""
}

// 中间层参数修改提交
type SubmitSettingChange struct {
	// 参数类型，1-参数变化（含增删改），2-时间表变化（含单灯，终端，增删改），3-定时任务变化（增删改）
	SettingType int32 `protobuf:"varint,1,opt,name=setting_type,json=settingType,proto3" json:"setting_type,omitempty"`
	// 设备逻辑地址，setting_type==3时可不填充
	TmlId []int64 `protobuf:"varint,2,rep,packed,name=tml_id,json=tmlId,proto3" json:"tml_id,omitempty"`
}

func (m *SubmitSettingChange) Reset()      { *m = SubmitSettingChange{} }
func (*SubmitSettingChange) ProtoMessage() {}
func (*SubmitSettingChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_17a284b5b5297b67, []int{2}
}
func (m *SubmitSettingChange) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SubmitSettingChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SubmitSettingChange.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SubmitSettingChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitSettingChange.Merge(m, src)
}
func (m *SubmitSettingChange) XXX_Size() int {
	return m.Size()
}
func (m *SubmitSettingChange) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitSettingChange.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitSettingChange proto.InternalMessageInfo

func (m *SubmitSettingChange) GetSettingType() int32 {
	if m != nil {
		return m.SettingType
	}
	return 0
}

func (m *SubmitSettingChange) GetTmlId() []int64 {
	if m != nil {
		return m.TmlId
	}
	return nil
}

func init() {
	proto.RegisterType((*MsgWithCtrl)(nil), "wlst.pb2.MsgWithCtrl")
	proto.RegisterType((*SubmitAlarm)(nil), "wlst.pb2.SubmitAlarm")
	proto.RegisterType((*SubmitAlarm_AlarmView)(nil), "wlst.pb2.SubmitAlarm.AlarmView")
	proto.RegisterType((*SubmitSettingChange)(nil), "wlst.pb2.SubmitSettingChange")
}

func init() { proto.RegisterFile("msg_with_ctrl.proto", fileDescriptor_17a284b5b5297b67) }

var fileDescriptor_17a284b5b5297b67 = []byte{
	// 896 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x96, 0x4d, 0x6f, 0xdb, 0x36,
	0x18, 0xc7, 0xad, 0xb8, 0x89, 0x6d, 0x2a, 0xdd, 0x5a, 0x05, 0x5d, 0x39, 0x07, 0xd3, 0x32, 0x9f,
	0x72, 0xf2, 0x14, 0xd9, 0x8e, 0x15, 0xa0, 0x18, 0x90, 0xb8, 0x05, 0xda, 0x01, 0x1b, 0x06, 0x39,
	0x58, 0x8f, 0x02, 0x2d, 0x71, 0x96, 0x56, 0xd1, 0x32, 0x48, 0x2a, 0x99, 0x6f, 0xfb, 0x08, 0xbb,
	0xee, 0x7d, 0xdd, 0xa9, 0x5f, 0x60, 0xfb, 0x0c, 0x3b, 0xa6, 0xdb, 0xa5, 0xc7, 0xc5, 0xb9, 0x74,
	0x6f, 0x40, 0x3f, 0xc2, 0x40, 0xca, 0x8e, 0x15, 0xba, 0x31, 0x74, 0x09, 0xf8, 0xfc, 0xff, 0xcf,
	0x8f, 0xcf, 0xc3, 0x47, 0x88, 0x49, 0xb0, 0x45, 0xd8, 0xd0, 0x3b, 0x8d, 0x78, 0xe8, 0xf9, 0x9c,
	0xc6, 0xcd, 0x31, 0x4d, 0x78, 0x62, 0x54, 0x4f, 0x63, 0xc6, 0x9b, 0xe3, 0x81, 0x5d, 0xdf, 0x92,
	0x82, 0x9f, 0xc4, 0x5e, 0x88, 0x51, 0x90, 0xd9, 0x75, 0xe3, 0x52, 0xe4, 0x64, 0x86, 0xd4, 0x6f,
	0x2f, 0xb4, 0xf1, 0x92, 0xd4, 0xf2, 0x33, 0xa9, 0xf1, 0x6c, 0x13, 0xe8, 0x1f, 0xb1, 0xe1, 0xe3,
	0x88, 0x87, 0x3d, 0x4e, 0x63, 0xa3, 0x01, 0x6e, 0x88, 0x7d, 0xa1, 0xb6, 0xa3, 0xed, 0xea, 0xf6,
	0x1b, 0xcd, 0x79, 0xdd, 0xe6, 0x43, 0x8c, 0x02, 0x57, 0x7a, 0x22, 0x07, 0xd1, 0x21, 0x83, 0x6b,
	0x6a, 0xce, 0x21, 0x1d, 0x32, 0x57, 0x7a, 0xc6, 0xfb, 0xa0, 0xc2, 0x26, 0xcc, 0x27, 0x01, 0x83,
	0x65, 0x99, 0x76, 0x67, 0x91, 0xd6, 0x9f, 0xb0, 0x5e, 0x42, 0x08, 0x1a, 0x05, 0xcc, 0x9d, 0x67,
	0x19, 0x5d, 0xa0, 0x7f, 0x82, 0x18, 0xe3, 0x21, 0x4d, 0xd2, 0x61, 0x08, 0x7d, 0x15, 0xca, 0x99,
	0xae, 0x3e, 0x5e, 0x04, 0xc6, 0x1e, 0x90, 0xc3, 0x11, 0x27, 0x87, 0x81, 0xa4, 0xde, 0x5a, 0x50,
	0x8f, 0x63, 0xc6, 0x8f, 0x31, 0x25, 0xd1, 0x08, 0xc5, 0x6e, 0x45, 0xc8, 0xc7, 0x24, 0x36, 0xee,
	0x81, 0x9b, 0x12, 0xf1, 0x13, 0xe2, 0x59, 0x96, 0x65, 0xc1, 0x97, 0x15, 0x09, 0xde, 0xbd, 0x0a,
	0x5e, 0xfa, 0xae, 0x2e, 0xf4, 0x5e, 0x42, 0x44, 0x70, 0x85, 0x6e, 0x61, 0x6b, 0x0f, 0xfe, 0x75,
	0x3d, 0x2d, 0xfc, 0x4b, 0x5a, 0x04, 0x2a, 0x6d, 0xc3, 0xbf, 0x57, 0xd2, 0x76, 0x9e, 0xb6, 0x15,
	0xda, 0xb1, 0xe1, 0x3f, 0xab, 0x68, 0x27, 0x4f, 0x3b, 0x4b, 0xf4, 0x1e, 0xfc, 0xb7, 0x70, 0x6d,
	0x47, 0xed, 0xdc, 0x69, 0xc3, 0xff, 0x56, 0xd6, 0x6e, 0xe7, 0xe9, 0xb6, 0xa4, 0xbf, 0xf8, 0x7c,
	0xe2, 0x61, 0x96, 0x7a, 0x9d, 0x8e, 0x65, 0xc1, 0xb3, 0x37, 0x97, 0xe8, 0xbc, 0xef, 0xea, 0x22,
	0xfd, 0x01, 0x4b, 0x45, 0x70, 0x85, 0x0e, 0x04, 0xfd, 0xbc, 0x20, 0x7d, 0x7f, 0x89, 0xee, 0x5a,
	0x16, 0xfc, 0xfd, 0x7a, 0x5a, 0xf8, 0x0b, 0xba, 0xab, 0xd2, 0x8e, 0x65, 0xc1, 0x3f, 0x56, 0xd0,
	0x4e, 0x9e, 0x76, 0x32, 0x1a, 0x85, 0xe1, 0x67, 0x1e, 0xe5, 0xa9, 0xb7, 0xef, 0x58, 0x6d, 0xf8,
	0xcb, 0x2d, 0x95, 0x3e, 0xcc, 0xfb, 0xae, 0x2e, 0xd2, 0x5d, 0x9e, 0x8a, 0x40, 0xa5, 0x11, 0xfc,
	0xb5, 0x38, 0x8d, 0x8c, 0x03, 0xb0, 0x39, 0x88, 0x9f, 0x78, 0x2c, 0x16, 0xe6, 0xc1, 0x1e, 0xfc,
	0xfa, 0xb6, 0xfa, 0xff, 0x71, 0x94, 0xb3, 0x5d, 0x30, 0x88, 0x9f, 0xf4, 0xe3, 0x54, 0xac, 0x15,
	0xd4, 0x86, 0xdf, 0xac, 0x42, 0xed, 0x1c, 0x6a, 0x5f, 0x45, 0x9d, 0x2e, 0xfc, 0xb6, 0x60, 0x55,
	0xa7, 0xab, 0xa0, 0x0e, 0xfc, 0xae, 0x28, 0xea, 0x28, 0x0d, 0x77, 0xe0, 0xf7, 0xab, 0xd0, 0x4e,
	0xae, 0xe1, 0x8e, 0x82, 0xee, 0xc3, 0x1f, 0x8a, 0xa2, 0xfb, 0x4a, 0xc3, 0x07, 0xf0, 0xc7, 0x82,
	0xa8, 0x73, 0xa0, 0x54, 0xb5, 0xe0, 0x4f, 0x45, 0xab, 0x5a, 0x0a, 0xda, 0x82, 0x4f, 0x8b, 0x7e,
	0xd7, 0x96, 0x82, 0xb6, 0xe1, 0xcf, 0x45, 0xd1, 0x76, 0xe3, 0x69, 0x19, 0xe8, 0xfd, 0x74, 0x40,
	0x22, 0x7e, 0x18, 0x23, 0x4a, 0x8c, 0x0f, 0x00, 0x40, 0x62, 0xe1, 0x9d, 0x44, 0xf8, 0x14, 0xae,
	0xed, 0x94, 0x77, 0x75, 0xfb, 0xdd, 0xdc, 0xaf, 0xfc, 0x22, 0xb5, 0x29, 0xff, 0x7e, 0x1a, 0xe1,
	0x53, 0xb7, 0x86, 0xe6, 0xcb, 0xfa, 0xf3, 0x35, 0x50, 0xbb, 0x34, 0x8c, 0x6d, 0x50, 0x0b, 0xb8,
	0xe7, 0x53, 0x8c, 0x38, 0x96, 0xb7, 0x4f, 0xd9, 0xad, 0x06, 0xbc, 0x27, 0x63, 0xe3, 0x0e, 0xd8,
	0xc0, 0x94, 0x7a, 0x51, 0x20, 0xef, 0x9c, 0x75, 0x77, 0x1d, 0x53, 0xfa, 0x28, 0x10, 0x32, 0x27,
	0xb1, 0x90, 0xcb, 0x99, 0xcc, 0x49, 0xfc, 0x28, 0x30, 0xee, 0x82, 0x4a, 0x9c, 0x24, 0x63, 0xa1,
	0xdf, 0x90, 0xfa, 0x86, 0x08, 0x67, 0x06, 0x22, 0xd2, 0x58, 0x9f, 0x19, 0x88, 0x08, 0x63, 0x1b,
	0xd4, 0xc4, 0xfe, 0x7e, 0x92, 0x8e, 0x38, 0xdc, 0x90, 0x56, 0x15, 0x53, 0xda, 0x13, 0xf1, 0xac,
	0x33, 0x8a, 0x49, 0x72, 0x82, 0x61, 0x75, 0xde, 0x99, 0x2b, 0x63, 0xe3, 0x6d, 0x50, 0x8d, 0x98,
	0x27, 0x0f, 0x05, 0x6b, 0x12, 0xac, 0x44, 0x2c, 0x9b, 0xcf, 0x36, 0xc8, 0x0e, 0xeb, 0x31, 0xea,
	0x43, 0x90, 0x6d, 0x2a, 0x85, 0x3e, 0xf5, 0x8d, 0x77, 0xe6, 0xc3, 0x1b, 0x21, 0x82, 0xa1, 0xbe,
	0xa3, 0xed, 0xd6, 0x66, 0xb3, 0xf9, 0x18, 0x11, 0xb9, 0xad, 0x38, 0x99, 0x34, 0x37, 0xa5, 0x59,
	0xe1, 0x24, 0x96, 0xd6, 0x36, 0xa8, 0xc9, 0xd3, 0x49, 0xef, 0xa6, 0xf4, 0xaa, 0x42, 0x10, 0x66,
	0xa3, 0x0f, 0xb6, 0xb2, 0xb9, 0xf7, 0x31, 0xe7, 0xd1, 0x68, 0xd8, 0x0b, 0xd1, 0x68, 0x88, 0x8d,
	0xf7, 0xc0, 0x26, 0xcb, 0x04, 0x8f, 0x4f, 0xc6, 0xd9, 0x7c, 0xd7, 0x5d, 0x7d, 0xa6, 0x1d, 0x4f,
	0xc6, 0xa2, 0xe2, 0x7c, 0x96, 0xe2, 0x4b, 0x96, 0x8f, 0xd6, 0x6e, 0x69, 0xb3, 0x79, 0xda, 0x1f,
	0x02, 0x70, 0x1f, 0x9f, 0x44, 0x3e, 0x96, 0x2f, 0x84, 0x7b, 0xf3, 0xe8, 0x81, 0x1f, 0x26, 0x46,
	0xee, 0x86, 0xce, 0x3d, 0x23, 0xea, 0xaf, 0x97, 0x1b, 0xa5, 0xa3, 0xfd, 0xb3, 0x73, 0xb3, 0xf4,
	0xe2, 0xdc, 0x2c, 0xbd, 0x3a, 0x37, 0xb5, 0x2f, 0xa7, 0xa6, 0xf6, 0x6c, 0x6a, 0x6a, 0xbf, 0x4d,
	0x4d, 0xed, 0x6c, 0x6a, 0x6a, 0x7f, 0x4e, 0x4d, 0xed, 0xe5, 0xd4, 0x2c, 0xbd, 0x9a, 0x9a, 0xda,
	0x57, 0x17, 0x66, 0xe9, 0xec, 0xc2, 0x2c, 0xbd, 0xb8, 0x30, 0x4b, 0x0f, 0xb5, 0xc1, 0x86, 0x7c,
	0xae, 0xb4, 0xfe, 0x0f, 0x00, 0x00, 0xff, 0xff, 0xfa, 0x50, 0x0b, 0xcb, 0x1e, 0x09, 0x00, 0x00,
}

func (this *MsgWithCtrl) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*MsgWithCtrl)
	if !ok {
		that2, ok := that.(MsgWithCtrl)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Head.Equal(that1.Head) {
		return false
	}
	if !this.Args.Equal(that1.Args) {
		return false
	}
	if !this.Syscmds.Equal(that1.Syscmds) {
		return false
	}
	if !this.Passthrough.Equal(that1.Passthrough) {
		return false
	}
	if !this.WlstTml.Equal(that1.WlstTml) {
		return false
	}
	if !this.WlstCom_0000.Equal(that1.WlstCom_0000) {
		return false
	}
	if !this.WlstCom_3E01.Equal(that1.WlstCom_3E01) {
		return false
	}
	if !this.WlstCom_3E02.Equal(that1.WlstCom_3E02) {
		return false
	}
	if !this.WlstCom_3E82.Equal(that1.WlstCom_3E82) {
		return false
	}
	if !this.WlstCom_3E81.Equal(that1.WlstCom_3E81) {
		return false
	}
	if !this.WlstCom_3E84.Equal(that1.WlstCom_3E84) {
		return false
	}
	if !this.WxjyEsu_5500.Equal(that1.WxjyEsu_5500) {
		return false
	}
	if !this.WxjyEsuD500.Equal(that1.WxjyEsuD500) {
		return false
	}
	if !this.WxjyEsuD700.Equal(that1.WxjyEsuD700) {
		return false
	}
	if !this.WxjyEsuD800.Equal(that1.WxjyEsuD800) {
		return false
	}
	if !this.AhhfRtu_6804.Equal(that1.AhhfRtu_6804) {
		return false
	}
	if !this.AhhfRtu_680A.Equal(that1.AhhfRtu_680A) {
		return false
	}
	if !this.BlkSlu_6891.Equal(that1.BlkSlu_6891) {
		return false
	}
	if !this.BlkSlu_6892.Equal(that1.BlkSlu_6892) {
		return false
	}
	if !this.BlkSlu_6887.Equal(that1.BlkSlu_6887) {
		return false
	}
	if !this.BlkSlu_6888.Equal(that1.BlkSlu_6888) {
		return false
	}
	if !this.BlkSlu_6895.Equal(that1.BlkSlu_6895) {
		return false
	}
	if !this.BlkSlu_6896.Equal(that1.BlkSlu_6896) {
		return false
	}
	if !this.BlkSlu_6889.Equal(that1.BlkSlu_6889) {
		return false
	}
	if !this.BlkSlu_6890.Equal(that1.BlkSlu_6890) {
		return false
	}
	if !this.BlkSlu_6893.Equal(that1.BlkSlu_6893) {
		return false
	}
	if !this.BlkSlu_6894.Equal(that1.BlkSlu_6894) {
		return false
	}
	return true
}
func (this *SubmitAlarm) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SubmitAlarm)
	if !ok {
		that2, ok := that.(SubmitAlarm)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.AlarmView) != len(that1.AlarmView) {
		return false
	}
	for i := range this.AlarmView {
		if !this.AlarmView[i].Equal(that1.AlarmView[i]) {
			return false
		}
	}
	return true
}
func (this *SubmitAlarm_AlarmView) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SubmitAlarm_AlarmView)
	if !ok {
		that2, ok := that.(SubmitAlarm_AlarmView)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.DtCreate != that1.DtCreate {
		return false
	}
	if this.ErrId != that1.ErrId {
		return false
	}
	if this.TmlId != that1.TmlId {
		return false
	}
	if this.LoopId != that1.LoopId {
		return false
	}
	if this.LampId != that1.LampId {
		return false
	}
	if this.ErrCount != that1.ErrCount {
		return false
	}
	if this.DtRemove != that1.DtRemove {
		return false
	}
	if this.IsAlarm != that1.IsAlarm {
		return false
	}
	if this.AlarmSrc != that1.AlarmSrc {
		return false
	}
	if this.AlarmName != that1.AlarmName {
		return false
	}
	if this.TmlName != that1.TmlName {
		return false
	}
	if this.LoopName != that1.LoopName {
		return false
	}
	return true
}
func (this *SubmitSettingChange) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SubmitSettingChange)
	if !ok {
		that2, ok := that.(SubmitSettingChange)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.SettingType != that1.SettingType {
		return false
	}
	if len(this.TmlId) != len(that1.TmlId) {
		return false
	}
	for i := range this.TmlId {
		if this.TmlId[i] != that1.TmlId[i] {
			return false
		}
	}
	return true
}
func (this *MsgWithCtrl) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 31)
	s = append(s, "&wlst_pb2.MsgWithCtrl{")
	if this.Head != nil {
		s = append(s, "Head: "+fmt.Sprintf("%#v", this.Head)+",\n")
	}
	if this.Args != nil {
		s = append(s, "Args: "+fmt.Sprintf("%#v", this.Args)+",\n")
	}
	if this.Syscmds != nil {
		s = append(s, "Syscmds: "+fmt.Sprintf("%#v", this.Syscmds)+",\n")
	}
	if this.Passthrough != nil {
		s = append(s, "Passthrough: "+fmt.Sprintf("%#v", this.Passthrough)+",\n")
	}
	if this.WlstTml != nil {
		s = append(s, "WlstTml: "+fmt.Sprintf("%#v", this.WlstTml)+",\n")
	}
	if this.WlstCom_0000 != nil {
		s = append(s, "WlstCom_0000: "+fmt.Sprintf("%#v", this.WlstCom_0000)+",\n")
	}
	if this.WlstCom_3E01 != nil {
		s = append(s, "WlstCom_3E01: "+fmt.Sprintf("%#v", this.WlstCom_3E01)+",\n")
	}
	if this.WlstCom_3E02 != nil {
		s = append(s, "WlstCom_3E02: "+fmt.Sprintf("%#v", this.WlstCom_3E02)+",\n")
	}
	if this.WlstCom_3E82 != nil {
		s = append(s, "WlstCom_3E82: "+fmt.Sprintf("%#v", this.WlstCom_3E82)+",\n")
	}
	if this.WlstCom_3E81 != nil {
		s = append(s, "WlstCom_3E81: "+fmt.Sprintf("%#v", this.WlstCom_3E81)+",\n")
	}
	if this.WlstCom_3E84 != nil {
		s = append(s, "WlstCom_3E84: "+fmt.Sprintf("%#v", this.WlstCom_3E84)+",\n")
	}
	if this.WxjyEsu_5500 != nil {
		s = append(s, "WxjyEsu_5500: "+fmt.Sprintf("%#v", this.WxjyEsu_5500)+",\n")
	}
	if this.WxjyEsuD500 != nil {
		s = append(s, "WxjyEsuD500: "+fmt.Sprintf("%#v", this.WxjyEsuD500)+",\n")
	}
	if this.WxjyEsuD700 != nil {
		s = append(s, "WxjyEsuD700: "+fmt.Sprintf("%#v", this.WxjyEsuD700)+",\n")
	}
	if this.WxjyEsuD800 != nil {
		s = append(s, "WxjyEsuD800: "+fmt.Sprintf("%#v", this.WxjyEsuD800)+",\n")
	}
	if this.AhhfRtu_6804 != nil {
		s = append(s, "AhhfRtu_6804: "+fmt.Sprintf("%#v", this.AhhfRtu_6804)+",\n")
	}
	if this.AhhfRtu_680A != nil {
		s = append(s, "AhhfRtu_680A: "+fmt.Sprintf("%#v", this.AhhfRtu_680A)+",\n")
	}
	if this.BlkSlu_6891 != nil {
		s = append(s, "BlkSlu_6891: "+fmt.Sprintf("%#v", this.BlkSlu_6891)+",\n")
	}
	if this.BlkSlu_6892 != nil {
		s = append(s, "BlkSlu_6892: "+fmt.Sprintf("%#v", this.BlkSlu_6892)+",\n")
	}
	if this.BlkSlu_6887 != nil {
		s = append(s, "BlkSlu_6887: "+fmt.Sprintf("%#v", this.BlkSlu_6887)+",\n")
	}
	if this.BlkSlu_6888 != nil {
		s = append(s, "BlkSlu_6888: "+fmt.Sprintf("%#v", this.BlkSlu_6888)+",\n")
	}
	if this.BlkSlu_6895 != nil {
		s = append(s, "BlkSlu_6895: "+fmt.Sprintf("%#v", this.BlkSlu_6895)+",\n")
	}
	if this.BlkSlu_6896 != nil {
		s = append(s, "BlkSlu_6896: "+fmt.Sprintf("%#v", this.BlkSlu_6896)+",\n")
	}
	if this.BlkSlu_6889 != nil {
		s = append(s, "BlkSlu_6889: "+fmt.Sprintf("%#v", this.BlkSlu_6889)+",\n")
	}
	if this.BlkSlu_6890 != nil {
		s = append(s, "BlkSlu_6890: "+fmt.Sprintf("%#v", this.BlkSlu_6890)+",\n")
	}
	if this.BlkSlu_6893 != nil {
		s = append(s, "BlkSlu_6893: "+fmt.Sprintf("%#v", this.BlkSlu_6893)+",\n")
	}
	if this.BlkSlu_6894 != nil {
		s = append(s, "BlkSlu_6894: "+fmt.Sprintf("%#v", this.BlkSlu_6894)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *SubmitAlarm) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&wlst_pb2.SubmitAlarm{")
	if this.AlarmView != nil {
		s = append(s, "AlarmView: "+fmt.Sprintf("%#v", this.AlarmView)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *SubmitAlarm_AlarmView) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 16)
	s = append(s, "&wlst_pb2.SubmitAlarm_AlarmView{")
	s = append(s, "DtCreate: "+fmt.Sprintf("%#v", this.DtCreate)+",\n")
	s = append(s, "ErrId: "+fmt.Sprintf("%#v", this.ErrId)+",\n")
	s = append(s, "TmlId: "+fmt.Sprintf("%#v", this.TmlId)+",\n")
	s = append(s, "LoopId: "+fmt.Sprintf("%#v", this.LoopId)+",\n")
	s = append(s, "LampId: "+fmt.Sprintf("%#v", this.LampId)+",\n")
	s = append(s, "ErrCount: "+fmt.Sprintf("%#v", this.ErrCount)+",\n")
	s = append(s, "DtRemove: "+fmt.Sprintf("%#v", this.DtRemove)+",\n")
	s = append(s, "IsAlarm: "+fmt.Sprintf("%#v", this.IsAlarm)+",\n")
	s = append(s, "AlarmSrc: "+fmt.Sprintf("%#v", this.AlarmSrc)+",\n")
	s = append(s, "AlarmName: "+fmt.Sprintf("%#v", this.AlarmName)+",\n")
	s = append(s, "TmlName: "+fmt.Sprintf("%#v", this.TmlName)+",\n")
	s = append(s, "LoopName: "+fmt.Sprintf("%#v", this.LoopName)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *SubmitSettingChange) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&wlst_pb2.SubmitSettingChange{")
	s = append(s, "SettingType: "+fmt.Sprintf("%#v", this.SettingType)+",\n")
	s = append(s, "TmlId: "+fmt.Sprintf("%#v", this.TmlId)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringMsgWithCtrl(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DeviceCtrlClient is the client API for DeviceCtrl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DeviceCtrlClient interface {
	DeviceEcho(ctx context.Context, in *MsgWithCtrl, opts ...grpc.CallOption) (*MsgWithCtrl, error)
}

type deviceCtrlClient struct {
	cc *grpc.ClientConn
}

func NewDeviceCtrlClient(cc *grpc.ClientConn) DeviceCtrlClient {
	return &deviceCtrlClient{cc}
}

func (c *deviceCtrlClient) DeviceEcho(ctx context.Context, in *MsgWithCtrl, opts ...grpc.CallOption) (*MsgWithCtrl, error) {
	out := new(MsgWithCtrl)
	err := c.cc.Invoke(ctx, "/wlst.pb2.DeviceCtrl/DeviceEcho", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeviceCtrlServer is the server API for DeviceCtrl service.
type DeviceCtrlServer interface {
	DeviceEcho(context.Context, *MsgWithCtrl) (*MsgWithCtrl, error)
}

// UnimplementedDeviceCtrlServer can be embedded to have forward compatible implementations.
type UnimplementedDeviceCtrlServer struct {
}

func (*UnimplementedDeviceCtrlServer) DeviceEcho(ctx context.Context, req *MsgWithCtrl) (*MsgWithCtrl, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeviceEcho not implemented")
}

func RegisterDeviceCtrlServer(s *grpc.Server, srv DeviceCtrlServer) {
	s.RegisterService(&_DeviceCtrl_serviceDesc, srv)
}

func _DeviceCtrl_DeviceEcho_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgWithCtrl)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceCtrlServer).DeviceEcho(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wlst.pb2.DeviceCtrl/DeviceEcho",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceCtrlServer).DeviceEcho(ctx, req.(*MsgWithCtrl))
	}
	return interceptor(ctx, in, info, handler)
}

var _DeviceCtrl_serviceDesc = grpc.ServiceDesc{
	ServiceName: "wlst.pb2.DeviceCtrl",
	HandlerType: (*DeviceCtrlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeviceEcho",
			Handler:    _DeviceCtrl_DeviceEcho_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "msg_with_ctrl.proto",
}

func (m *MsgWithCtrl) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgWithCtrl) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgWithCtrl) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BlkSlu_6894 != nil {
		{
			size, err := m.BlkSlu_6894.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMsgWithCtrl(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x8a
		i--
		dAtA[i] = 0x92
	}
	if m.BlkSlu_6893 != nil {
		{
			size, err := m.BlkSlu_6893.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMsgWithCtrl(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x8a
		i--
		dAtA[i] = 0x8a
	}
	if m.BlkSlu_6890 != nil {
		{
			size, err := m.BlkSlu_6890.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMsgWithCtrl(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x8a
		i--
		dAtA[i] = 0x82
	}
	if m.BlkSlu_6889 != nil {
		{
			size, err := m.BlkSlu_6889.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMsgWithCtrl(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x89
		i--
		dAtA[i] = 0xfa
	}
	if m.BlkSlu_6896 != nil {
		{
			size, err := m.BlkSlu_6896.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMsgWithCtrl(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x89
		i--
		dAtA[i] = 0xf2
	}
	if m.BlkSlu_6895 != nil {
		{
			size, err := m.BlkSlu_6895.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMsgWithCtrl(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x89
		i--
		dAtA[i] = 0xea
	}
	if m.BlkSlu_6888 != nil {
		{
			size, err := m.BlkSlu_6888.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMsgWithCtrl(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x89
		i--
		dAtA[i] = 0xe2
	}
	if m.BlkSlu_6887 != nil {
		{
			size, err := m.BlkSlu_6887.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMsgWithCtrl(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x89
		i--
		dAtA[i] = 0xda
	}
	if m.BlkSlu_6892 != nil {
		{
			size, err := m.BlkSlu_6892.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMsgWithCtrl(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x89
		i--
		dAtA[i] = 0xd2
	}
	if m.BlkSlu_6891 != nil {
		{
			size, err := m.BlkSlu_6891.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMsgWithCtrl(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x89
		i--
		dAtA[i] = 0xca
	}
	if m.AhhfRtu_680A != nil {
		{
			size, err := m.AhhfRtu_680A.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMsgWithCtrl(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x83
		i--
		dAtA[i] = 0xb2
	}
	if m.AhhfRtu_6804 != nil {
		{
			size, err := m.AhhfRtu_6804.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMsgWithCtrl(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x83
		i--
		dAtA[i] = 0xaa
	}
	if m.WxjyEsuD800 != nil {
		{
			size, err := m.WxjyEsuD800.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMsgWithCtrl(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x7d
		i--
		dAtA[i] = 0x9a
	}
	if m.WxjyEsuD700 != nil {
		{
			size, err := m.WxjyEsuD700.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMsgWithCtrl(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x7d
		i--
		dAtA[i] = 0x92
	}
	if m.WxjyEsuD500 != nil {
		{
			size, err := m.WxjyEsuD500.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMsgWithCtrl(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x7d
		i--
		dAtA[i] = 0x8a
	}
	if m.WxjyEsu_5500 != nil {
		{
			size, err := m.WxjyEsu_5500.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMsgWithCtrl(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x7d
		i--
		dAtA[i] = 0x82
	}
	if m.WlstCom_3E84 != nil {
		{
			size, err := m.WlstCom_3E84.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMsgWithCtrl(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x3e
		i--
		dAtA[i] = 0xea
	}
	if m.WlstCom_3E81 != nil {
		{
			size, err := m.WlstCom_3E81.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMsgWithCtrl(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x3e
		i--
		dAtA[i] = 0xe2
	}
	if m.WlstCom_3E82 != nil {
		{
			size, err := m.WlstCom_3E82.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMsgWithCtrl(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x3e
		i--
		dAtA[i] = 0xda
	}
	if m.WlstCom_3E02 != nil {
		{
			size, err := m.WlstCom_3E02.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMsgWithCtrl(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x3e
		i--
		dAtA[i] = 0xd2
	}
	if m.WlstCom_3E01 != nil {
		{
			size, err := m.WlstCom_3E01.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMsgWithCtrl(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x3e
		i--
		dAtA[i] = 0xca
	}
	if m.WlstCom_0000 != nil {
		{
			size, err := m.WlstCom_0000.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMsgWithCtrl(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x3e
		i--
		dAtA[i] = 0xc2
	}
	if m.WlstTml != nil {
		{
			size, err := m.WlstTml.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMsgWithCtrl(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x6
		i--
		dAtA[i] = 0xa2
	}
	if m.Passthrough != nil {
		{
			size, err := m.Passthrough.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMsgWithCtrl(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x6
		i--
		dAtA[i] = 0x9a
	}
	if m.Syscmds != nil {
		{
			size, err := m.Syscmds.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMsgWithCtrl(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.Args != nil {
		{
			size, err := m.Args.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMsgWithCtrl(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Head != nil {
		{
			size, err := m.Head.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMsgWithCtrl(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SubmitAlarm) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SubmitAlarm) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SubmitAlarm) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AlarmView) > 0 {
		for iNdEx := len(m.AlarmView) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AlarmView[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintMsgWithCtrl(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	return len(dAtA) - i, nil
}

func (m *SubmitAlarm_AlarmView) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SubmitAlarm_AlarmView) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SubmitAlarm_AlarmView) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.LoopName) > 0 {
		i -= len(m.LoopName)
		copy(dAtA[i:], m.LoopName)
		i = encodeVarintMsgWithCtrl(dAtA, i, uint64(len(m.LoopName)))
		i--
		dAtA[i] = 0x6a
	}
	if len(m.TmlName) > 0 {
		i -= len(m.TmlName)
		copy(dAtA[i:], m.TmlName)
		i = encodeVarintMsgWithCtrl(dAtA, i, uint64(len(m.TmlName)))
		i--
		dAtA[i] = 0x62
	}
	if len(m.AlarmName) > 0 {
		i -= len(m.AlarmName)
		copy(dAtA[i:], m.AlarmName)
		i = encodeVarintMsgWithCtrl(dAtA, i, uint64(len(m.AlarmName)))
		i--
		dAtA[i] = 0x5a
	}
	if m.AlarmSrc != 0 {
		i = encodeVarintMsgWithCtrl(dAtA, i, uint64(m.AlarmSrc))
		i--
		dAtA[i] = 0x50
	}
	if m.IsAlarm != 0 {
		i = encodeVarintMsgWithCtrl(dAtA, i, uint64(m.IsAlarm))
		i--
		dAtA[i] = 0x48
	}
	if m.DtRemove != 0 {
		i = encodeVarintMsgWithCtrl(dAtA, i, uint64(m.DtRemove))
		i--
		dAtA[i] = 0x40
	}
	if m.ErrCount != 0 {
		i = encodeVarintMsgWithCtrl(dAtA, i, uint64(m.ErrCount))
		i--
		dAtA[i] = 0x30
	}
	if m.LampId != 0 {
		i = encodeVarintMsgWithCtrl(dAtA, i, uint64(m.LampId))
		i--
		dAtA[i] = 0x28
	}
	if m.LoopId != 0 {
		i = encodeVarintMsgWithCtrl(dAtA, i, uint64(m.LoopId))
		i--
		dAtA[i] = 0x20
	}
	if m.TmlId != 0 {
		i = encodeVarintMsgWithCtrl(dAtA, i, uint64(m.TmlId))
		i--
		dAtA[i] = 0x18
	}
	if m.ErrId != 0 {
		i = encodeVarintMsgWithCtrl(dAtA, i, uint64(m.ErrId))
		i--
		dAtA[i] = 0x10
	}
	if m.DtCreate != 0 {
		i = encodeVarintMsgWithCtrl(dAtA, i, uint64(m.DtCreate))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *SubmitSettingChange) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SubmitSettingChange) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SubmitSettingChange) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TmlId) > 0 {
		dAtA29 := make([]byte, len(m.TmlId)*10)
		var j28 int
		for _, num1 := range m.TmlId {
			num := uint64(num1)
			for num >= 1<<7 {
				dAtA29[j28] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j28++
			}
			dAtA29[j28] = uint8(num)
			j28++
		}
		i -= j28
		copy(dAtA[i:], dAtA29[:j28])
		i = encodeVarintMsgWithCtrl(dAtA, i, uint64(j28))
		i--
		dAtA[i] = 0x12
	}
	if m.SettingType != 0 {
		i = encodeVarintMsgWithCtrl(dAtA, i, uint64(m.SettingType))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintMsgWithCtrl(dAtA []byte, offset int, v uint64) int {
	offset -= sovMsgWithCtrl(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgWithCtrl) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Head != nil {
		l = m.Head.Size()
		n += 1 + l + sovMsgWithCtrl(uint64(l))
	}
	if m.Args != nil {
		l = m.Args.Size()
		n += 1 + l + sovMsgWithCtrl(uint64(l))
	}
	if m.Syscmds != nil {
		l = m.Syscmds.Size()
		n += 1 + l + sovMsgWithCtrl(uint64(l))
	}
	if m.Passthrough != nil {
		l = m.Passthrough.Size()
		n += 2 + l + sovMsgWithCtrl(uint64(l))
	}
	if m.WlstTml != nil {
		l = m.WlstTml.Size()
		n += 2 + l + sovMsgWithCtrl(uint64(l))
	}
	if m.WlstCom_0000 != nil {
		l = m.WlstCom_0000.Size()
		n += 2 + l + sovMsgWithCtrl(uint64(l))
	}
	if m.WlstCom_3E01 != nil {
		l = m.WlstCom_3E01.Size()
		n += 2 + l + sovMsgWithCtrl(uint64(l))
	}
	if m.WlstCom_3E02 != nil {
		l = m.WlstCom_3E02.Size()
		n += 2 + l + sovMsgWithCtrl(uint64(l))
	}
	if m.WlstCom_3E82 != nil {
		l = m.WlstCom_3E82.Size()
		n += 2 + l + sovMsgWithCtrl(uint64(l))
	}
	if m.WlstCom_3E81 != nil {
		l = m.WlstCom_3E81.Size()
		n += 2 + l + sovMsgWithCtrl(uint64(l))
	}
	if m.WlstCom_3E84 != nil {
		l = m.WlstCom_3E84.Size()
		n += 2 + l + sovMsgWithCtrl(uint64(l))
	}
	if m.WxjyEsu_5500 != nil {
		l = m.WxjyEsu_5500.Size()
		n += 2 + l + sovMsgWithCtrl(uint64(l))
	}
	if m.WxjyEsuD500 != nil {
		l = m.WxjyEsuD500.Size()
		n += 2 + l + sovMsgWithCtrl(uint64(l))
	}
	if m.WxjyEsuD700 != nil {
		l = m.WxjyEsuD700.Size()
		n += 2 + l + sovMsgWithCtrl(uint64(l))
	}
	if m.WxjyEsuD800 != nil {
		l = m.WxjyEsuD800.Size()
		n += 2 + l + sovMsgWithCtrl(uint64(l))
	}
	if m.AhhfRtu_6804 != nil {
		l = m.AhhfRtu_6804.Size()
		n += 3 + l + sovMsgWithCtrl(uint64(l))
	}
	if m.AhhfRtu_680A != nil {
		l = m.AhhfRtu_680A.Size()
		n += 3 + l + sovMsgWithCtrl(uint64(l))
	}
	if m.BlkSlu_6891 != nil {
		l = m.BlkSlu_6891.Size()
		n += 3 + l + sovMsgWithCtrl(uint64(l))
	}
	if m.BlkSlu_6892 != nil {
		l = m.BlkSlu_6892.Size()
		n += 3 + l + sovMsgWithCtrl(uint64(l))
	}
	if m.BlkSlu_6887 != nil {
		l = m.BlkSlu_6887.Size()
		n += 3 + l + sovMsgWithCtrl(uint64(l))
	}
	if m.BlkSlu_6888 != nil {
		l = m.BlkSlu_6888.Size()
		n += 3 + l + sovMsgWithCtrl(uint64(l))
	}
	if m.BlkSlu_6895 != nil {
		l = m.BlkSlu_6895.Size()
		n += 3 + l + sovMsgWithCtrl(uint64(l))
	}
	if m.BlkSlu_6896 != nil {
		l = m.BlkSlu_6896.Size()
		n += 3 + l + sovMsgWithCtrl(uint64(l))
	}
	if m.BlkSlu_6889 != nil {
		l = m.BlkSlu_6889.Size()
		n += 3 + l + sovMsgWithCtrl(uint64(l))
	}
	if m.BlkSlu_6890 != nil {
		l = m.BlkSlu_6890.Size()
		n += 3 + l + sovMsgWithCtrl(uint64(l))
	}
	if m.BlkSlu_6893 != nil {
		l = m.BlkSlu_6893.Size()
		n += 3 + l + sovMsgWithCtrl(uint64(l))
	}
	if m.BlkSlu_6894 != nil {
		l = m.BlkSlu_6894.Size()
		n += 3 + l + sovMsgWithCtrl(uint64(l))
	}
	return n
}

func (m *SubmitAlarm) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.AlarmView) > 0 {
		for _, e := range m.AlarmView {
			l = e.Size()
			n += 1 + l + sovMsgWithCtrl(uint64(l))
		}
	}
	return n
}

func (m *SubmitAlarm_AlarmView) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.DtCreate != 0 {
		n += 1 + sovMsgWithCtrl(uint64(m.DtCreate))
	}
	if m.ErrId != 0 {
		n += 1 + sovMsgWithCtrl(uint64(m.ErrId))
	}
	if m.TmlId != 0 {
		n += 1 + sovMsgWithCtrl(uint64(m.TmlId))
	}
	if m.LoopId != 0 {
		n += 1 + sovMsgWithCtrl(uint64(m.LoopId))
	}
	if m.LampId != 0 {
		n += 1 + sovMsgWithCtrl(uint64(m.LampId))
	}
	if m.ErrCount != 0 {
		n += 1 + sovMsgWithCtrl(uint64(m.ErrCount))
	}
	if m.DtRemove != 0 {
		n += 1 + sovMsgWithCtrl(uint64(m.DtRemove))
	}
	if m.IsAlarm != 0 {
		n += 1 + sovMsgWithCtrl(uint64(m.IsAlarm))
	}
	if m.AlarmSrc != 0 {
		n += 1 + sovMsgWithCtrl(uint64(m.AlarmSrc))
	}
	l = len(m.AlarmName)
	if l > 0 {
		n += 1 + l + sovMsgWithCtrl(uint64(l))
	}
	l = len(m.TmlName)
	if l > 0 {
		n += 1 + l + sovMsgWithCtrl(uint64(l))
	}
	l = len(m.LoopName)
	if l > 0 {
		n += 1 + l + sovMsgWithCtrl(uint64(l))
	}
	return n
}

func (m *SubmitSettingChange) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SettingType != 0 {
		n += 1 + sovMsgWithCtrl(uint64(m.SettingType))
	}
	if len(m.TmlId) > 0 {
		l = 0
		for _, e := range m.TmlId {
			l += sovMsgWithCtrl(uint64(e))
		}
		n += 1 + sovMsgWithCtrl(uint64(l)) + l
	}
	return n
}

func sovMsgWithCtrl(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMsgWithCtrl(x uint64) (n int) {
	return sovMsgWithCtrl(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *MsgWithCtrl) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&MsgWithCtrl{`,
		`Head:` + strings.Replace(fmt.Sprintf("%v", this.Head), "Head", "Head", 1) + `,`,
		`Args:` + strings.Replace(fmt.Sprintf("%v", this.Args), "Args", "Args", 1) + `,`,
		`Syscmds:` + strings.Replace(fmt.Sprintf("%v", this.Syscmds), "SysCommands", "SysCommands", 1) + `,`,
		`Passthrough:` + strings.Replace(fmt.Sprintf("%v", this.Passthrough), "Passthrough", "Passthrough", 1) + `,`,
		`WlstTml:` + strings.Replace(fmt.Sprintf("%v", this.WlstTml), "WlstTerminal", "WlstTerminal", 1) + `,`,
		`WlstCom_0000:` + strings.Replace(fmt.Sprintf("%v", this.WlstCom_0000), "WlstCom_0000", "WlstCom_0000", 1) + `,`,
		`WlstCom_3E01:` + strings.Replace(fmt.Sprintf("%v", this.WlstCom_3E01), "WlstCom_3E01", "WlstCom_3E01", 1) + `,`,
		`WlstCom_3E02:` + strings.Replace(fmt.Sprintf("%v", this.WlstCom_3E02), "WlstCom_3E02", "WlstCom_3E02", 1) + `,`,
		`WlstCom_3E82:` + strings.Replace(fmt.Sprintf("%v", this.WlstCom_3E82), "WlstCom_3E82", "WlstCom_3E82", 1) + `,`,
		`WlstCom_3E81:` + strings.Replace(fmt.Sprintf("%v", this.WlstCom_3E81), "WlstCom_3E02", "WlstCom_3E02", 1) + `,`,
		`WlstCom_3E84:` + strings.Replace(fmt.Sprintf("%v", this.WlstCom_3E84), "WlstCom_3E84", "WlstCom_3E84", 1) + `,`,
		`WxjyEsu_5500:` + strings.Replace(fmt.Sprintf("%v", this.WxjyEsu_5500), "WxjyEsu_5500", "WxjyEsu_5500", 1) + `,`,
		`WxjyEsuD500:` + strings.Replace(fmt.Sprintf("%v", this.WxjyEsuD500), "WxjyEsu_5500", "WxjyEsu_5500", 1) + `,`,
		`WxjyEsuD700:` + strings.Replace(fmt.Sprintf("%v", this.WxjyEsuD700), "WxjyEsuD700", "WxjyEsuD700", 1) + `,`,
		`WxjyEsuD800:` + strings.Replace(fmt.Sprintf("%v", this.WxjyEsuD800), "WxjyEsuD800", "WxjyEsuD800", 1) + `,`,
		`AhhfRtu_6804:` + strings.Replace(fmt.Sprintf("%v", this.AhhfRtu_6804), "AhhfRtu_6804", "AhhfRtu_6804", 1) + `,`,
		`AhhfRtu_680A:` + strings.Replace(fmt.Sprintf("%v", this.AhhfRtu_680A), "AhhfRtu_6804", "AhhfRtu_6804", 1) + `,`,
		`BlkSlu_6891:` + strings.Replace(fmt.Sprintf("%v", this.BlkSlu_6891), "BlkSlu_6891", "BlkSlu_6891", 1) + `,`,
		`BlkSlu_6892:` + strings.Replace(fmt.Sprintf("%v", this.BlkSlu_6892), "BlkSlu_6892", "BlkSlu_6892", 1) + `,`,
		`BlkSlu_6887:` + strings.Replace(fmt.Sprintf("%v", this.BlkSlu_6887), "BlkSlu_6891", "BlkSlu_6891", 1) + `,`,
		`BlkSlu_6888:` + strings.Replace(fmt.Sprintf("%v", this.BlkSlu_6888), "BlkSlu_6891", "BlkSlu_6891", 1) + `,`,
		`BlkSlu_6895:` + strings.Replace(fmt.Sprintf("%v", this.BlkSlu_6895), "BlkSlu_6895", "BlkSlu_6895", 1) + `,`,
		`BlkSlu_6896:` + strings.Replace(fmt.Sprintf("%v", this.BlkSlu_6896), "BlkSlu_6895", "BlkSlu_6895", 1) + `,`,
		`BlkSlu_6889:` + strings.Replace(fmt.Sprintf("%v", this.BlkSlu_6889), "BlkSlu_6895", "BlkSlu_6895", 1) + `,`,
		`BlkSlu_6890:` + strings.Replace(fmt.Sprintf("%v", this.BlkSlu_6890), "BlkSlu_6895", "BlkSlu_6895", 1) + `,`,
		`BlkSlu_6893:` + strings.Replace(fmt.Sprintf("%v", this.BlkSlu_6893), "BlkSlu_6891", "BlkSlu_6891", 1) + `,`,
		`BlkSlu_6894:` + strings.Replace(fmt.Sprintf("%v", this.BlkSlu_6894), "BlkSlu_6891", "BlkSlu_6891", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SubmitAlarm) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForAlarmView := "[]*SubmitAlarm_AlarmView{"
	for _, f := range this.AlarmView {
		repeatedStringForAlarmView += strings.Replace(fmt.Sprintf("%v", f), "SubmitAlarm_AlarmView", "SubmitAlarm_AlarmView", 1) + ","
	}
	repeatedStringForAlarmView += "}"
	s := strings.Join([]string{`&SubmitAlarm{`,
		`AlarmView:` + repeatedStringForAlarmView + `,`,
		`}`,
	}, "")
	return s
}
func (this *SubmitAlarm_AlarmView) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SubmitAlarm_AlarmView{`,
		`DtCreate:` + fmt.Sprintf("%v", this.DtCreate) + `,`,
		`ErrId:` + fmt.Sprintf("%v", this.ErrId) + `,`,
		`TmlId:` + fmt.Sprintf("%v", this.TmlId) + `,`,
		`LoopId:` + fmt.Sprintf("%v", this.LoopId) + `,`,
		`LampId:` + fmt.Sprintf("%v", this.LampId) + `,`,
		`ErrCount:` + fmt.Sprintf("%v", this.ErrCount) + `,`,
		`DtRemove:` + fmt.Sprintf("%v", this.DtRemove) + `,`,
		`IsAlarm:` + fmt.Sprintf("%v", this.IsAlarm) + `,`,
		`AlarmSrc:` + fmt.Sprintf("%v", this.AlarmSrc) + `,`,
		`AlarmName:` + fmt.Sprintf("%v", this.AlarmName) + `,`,
		`TmlName:` + fmt.Sprintf("%v", this.TmlName) + `,`,
		`LoopName:` + fmt.Sprintf("%v", this.LoopName) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SubmitSettingChange) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SubmitSettingChange{`,
		`SettingType:` + fmt.Sprintf("%v", this.SettingType) + `,`,
		`TmlId:` + fmt.Sprintf("%v", this.TmlId) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringMsgWithCtrl(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *MsgWithCtrl) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgWithCtrl
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgWithCtrl: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgWithCtrl: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Head", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgWithCtrl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Head == nil {
				m.Head = &Head{}
			}
			if err := m.Head.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Args", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgWithCtrl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Args == nil {
				m.Args = &Args{}
			}
			if err := m.Args.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Syscmds", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgWithCtrl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Syscmds == nil {
				m.Syscmds = &SysCommands{}
			}
			if err := m.Syscmds.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 99:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Passthrough", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgWithCtrl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Passthrough == nil {
				m.Passthrough = &Passthrough{}
			}
			if err := m.Passthrough.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 100:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WlstTml", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgWithCtrl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.WlstTml == nil {
				m.WlstTml = &WlstTerminal{}
			}
			if err := m.WlstTml.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 1000:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WlstCom_0000", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgWithCtrl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.WlstCom_0000 == nil {
				m.WlstCom_0000 = &WlstCom_0000{}
			}
			if err := m.WlstCom_0000.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 1001:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WlstCom_3E01", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgWithCtrl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.WlstCom_3E01 == nil {
				m.WlstCom_3E01 = &WlstCom_3E01{}
			}
			if err := m.WlstCom_3E01.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 1002:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WlstCom_3E02", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgWithCtrl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.WlstCom_3E02 == nil {
				m.WlstCom_3E02 = &WlstCom_3E02{}
			}
			if err := m.WlstCom_3E02.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 1003:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WlstCom_3E82", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgWithCtrl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.WlstCom_3E82 == nil {
				m.WlstCom_3E82 = &WlstCom_3E82{}
			}
			if err := m.WlstCom_3E82.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 1004:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WlstCom_3E81", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgWithCtrl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.WlstCom_3E81 == nil {
				m.WlstCom_3E81 = &WlstCom_3E02{}
			}
			if err := m.WlstCom_3E81.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 1005:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WlstCom_3E84", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgWithCtrl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.WlstCom_3E84 == nil {
				m.WlstCom_3E84 = &WlstCom_3E84{}
			}
			if err := m.WlstCom_3E84.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2000:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WxjyEsu_5500", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgWithCtrl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.WxjyEsu_5500 == nil {
				m.WxjyEsu_5500 = &WxjyEsu_5500{}
			}
			if err := m.WxjyEsu_5500.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2001:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WxjyEsuD500", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgWithCtrl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.WxjyEsuD500 == nil {
				m.WxjyEsuD500 = &WxjyEsu_5500{}
			}
			if err := m.WxjyEsuD500.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2002:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WxjyEsuD700", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgWithCtrl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.WxjyEsuD700 == nil {
				m.WxjyEsuD700 = &WxjyEsuD700{}
			}
			if err := m.WxjyEsuD700.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2003:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WxjyEsuD800", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgWithCtrl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.WxjyEsuD800 == nil {
				m.WxjyEsuD800 = &WxjyEsuD800{}
			}
			if err := m.WxjyEsuD800.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2101:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AhhfRtu_6804", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgWithCtrl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.AhhfRtu_6804 == nil {
				m.AhhfRtu_6804 = &AhhfRtu_6804{}
			}
			if err := m.AhhfRtu_6804.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2102:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AhhfRtu_680A", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgWithCtrl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.AhhfRtu_680A == nil {
				m.AhhfRtu_680A = &AhhfRtu_6804{}
			}
			if err := m.AhhfRtu_680A.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2201:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlkSlu_6891", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgWithCtrl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.BlkSlu_6891 == nil {
				m.BlkSlu_6891 = &BlkSlu_6891{}
			}
			if err := m.BlkSlu_6891.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2202:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlkSlu_6892", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgWithCtrl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.BlkSlu_6892 == nil {
				m.BlkSlu_6892 = &BlkSlu_6892{}
			}
			if err := m.BlkSlu_6892.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2203:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlkSlu_6887", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgWithCtrl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.BlkSlu_6887 == nil {
				m.BlkSlu_6887 = &BlkSlu_6891{}
			}
			if err := m.BlkSlu_6887.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2204:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlkSlu_6888", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgWithCtrl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.BlkSlu_6888 == nil {
				m.BlkSlu_6888 = &BlkSlu_6891{}
			}
			if err := m.BlkSlu_6888.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2205:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlkSlu_6895", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgWithCtrl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.BlkSlu_6895 == nil {
				m.BlkSlu_6895 = &BlkSlu_6895{}
			}
			if err := m.BlkSlu_6895.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2206:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlkSlu_6896", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgWithCtrl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.BlkSlu_6896 == nil {
				m.BlkSlu_6896 = &BlkSlu_6895{}
			}
			if err := m.BlkSlu_6896.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2207:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlkSlu_6889", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgWithCtrl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.BlkSlu_6889 == nil {
				m.BlkSlu_6889 = &BlkSlu_6895{}
			}
			if err := m.BlkSlu_6889.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2208:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlkSlu_6890", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgWithCtrl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.BlkSlu_6890 == nil {
				m.BlkSlu_6890 = &BlkSlu_6895{}
			}
			if err := m.BlkSlu_6890.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2209:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlkSlu_6893", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgWithCtrl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.BlkSlu_6893 == nil {
				m.BlkSlu_6893 = &BlkSlu_6891{}
			}
			if err := m.BlkSlu_6893.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2210:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlkSlu_6894", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgWithCtrl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.BlkSlu_6894 == nil {
				m.BlkSlu_6894 = &BlkSlu_6891{}
			}
			if err := m.BlkSlu_6894.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMsgWithCtrl(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SubmitAlarm) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgWithCtrl
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SubmitAlarm: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SubmitAlarm: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AlarmView", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgWithCtrl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AlarmView = append(m.AlarmView, &SubmitAlarm_AlarmView{})
			if err := m.AlarmView[len(m.AlarmView)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMsgWithCtrl(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SubmitAlarm_AlarmView) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgWithCtrl
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AlarmView: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AlarmView: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DtCreate", wireType)
			}
			m.DtCreate = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgWithCtrl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DtCreate |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ErrId", wireType)
			}
			m.ErrId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgWithCtrl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ErrId |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TmlId", wireType)
			}
			m.TmlId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgWithCtrl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TmlId |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LoopId", wireType)
			}
			m.LoopId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgWithCtrl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LoopId |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LampId", wireType)
			}
			m.LampId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgWithCtrl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LampId |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ErrCount", wireType)
			}
			m.ErrCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgWithCtrl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ErrCount |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DtRemove", wireType)
			}
			m.DtRemove = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgWithCtrl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DtRemove |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsAlarm", wireType)
			}
			m.IsAlarm = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgWithCtrl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.IsAlarm |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AlarmSrc", wireType)
			}
			m.AlarmSrc = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgWithCtrl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AlarmSrc |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AlarmName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgWithCtrl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AlarmName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TmlName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgWithCtrl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TmlName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LoopName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgWithCtrl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LoopName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMsgWithCtrl(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SubmitSettingChange) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgWithCtrl
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SubmitSettingChange: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SubmitSettingChange: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SettingType", wireType)
			}
			m.SettingType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgWithCtrl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SettingType |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType == 0 {
				var v int64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowMsgWithCtrl
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= int64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.TmlId = append(m.TmlId, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowMsgWithCtrl
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthMsgWithCtrl
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthMsgWithCtrl
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.TmlId) == 0 {
					m.TmlId = make([]int64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v int64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowMsgWithCtrl
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= int64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.TmlId = append(m.TmlId, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field TmlId", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMsgWithCtrl(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthMsgWithCtrl
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMsgWithCtrl(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMsgWithCtrl
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsgWithCtrl
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsgWithCtrl
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMsgWithCtrl
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthMsgWithCtrl
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowMsgWithCtrl
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipMsgWithCtrl(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthMsgWithCtrl
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthMsgWithCtrl = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMsgWithCtrl   = fmt.Errorf("proto: integer overflow")
)
