// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg_with_ctrl.proto

package wlst_pb2

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//数据服务和通讯服务传输格式
type MsgWithCtrl struct {
	//协议头信息
	Head *Head `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	//协议参数
	Args *Args `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`
	//系统级别协议集
	Syscmds *SysCommands `protobuf:"bytes,3,opt,name=syscmds,proto3" json:"syscmds,omitempty"`
	// 设备升级公共协议
	Passthrough *Passthrough `protobuf:"bytes,99,opt,name=Passthrough,json=passthrough,proto3" json:"Passthrough,omitempty"`
	//终端协议集
	WlstTml *WlstTerminal `protobuf:"bytes,100,opt,name=wlst_tml,json=wlstTml,proto3" json:"wlst_tml,omitempty"`
	//模块协议集
	WlstCom_0000 *WlstCom_0000 `protobuf:"bytes,1000,opt,name=wlst_com_0000,json=wlstCom0000,proto3" json:"wlst_com_0000,omitempty"`
	WlstCom_3E01 *WlstCom_3E01 `protobuf:"bytes,1001,opt,name=wlst_com_3e01,json=wlstCom3e01,proto3" json:"wlst_com_3e01,omitempty"`
	WlstCom_3E02 *WlstCom_3E02 `protobuf:"bytes,1002,opt,name=wlst_com_3e02,json=wlstCom3e02,proto3" json:"wlst_com_3e02,omitempty"`
	WlstCom_3E82 *WlstCom_3E82 `protobuf:"bytes,1003,opt,name=wlst_com_3e82,json=wlstCom3e82,proto3" json:"wlst_com_3e82,omitempty"`
	WlstCom_3E81 *WlstCom_3E02 `protobuf:"bytes,1004,opt,name=wlst_com_3e81,json=wlstCom3e81,proto3" json:"wlst_com_3e81,omitempty"`
	WlstCom_3E84 *WlstCom_3E84 `protobuf:"bytes,1005,opt,name=wlst_com_3e84,json=wlstCom3e84,proto3" json:"wlst_com_3e84,omitempty"`
	//第三方设备
	//江阴节能
	WxjyEsu_5500 *WxjyEsu_5500 `protobuf:"bytes,2000,opt,name=wxjy_esu_5500,json=wxjyEsu5500,proto3" json:"wxjy_esu_5500,omitempty"`
	WxjyEsuD500  *WxjyEsu_5500 `protobuf:"bytes,2001,opt,name=wxjy_esu_d500,json=wxjyEsuD500,proto3" json:"wxjy_esu_d500,omitempty"`
	WxjyEsuD700  *WxjyEsuD700  `protobuf:"bytes,2002,opt,name=wxjy_esu_d700,json=wxjyEsuD700,proto3" json:"wxjy_esu_d700,omitempty"`
	WxjyEsuD800  *WxjyEsuD800  `protobuf:"bytes,2003,opt,name=wxjy_esu_d800,json=wxjyEsuD800,proto3" json:"wxjy_esu_d800,omitempty"`
	// 安徽合肥,head.tver=2，若无特殊说明，cmd和公司终端相同，公司标示改为ahhf
	// 对时，采用终端Wlst_rtu_9300结构下发，应答采用Wlst_rtu_9200
	// 下发年时间，采用终端wlst_rtu_7060, 应答采用wlst_rtu_70e0
	// 开关量输出/输入/上下限设置/应答采用下面结构，cmd=ahhf.rtu.6804
	AhhfRtu_6804 *AhhfRtu_6804 `protobuf:"bytes,2101,opt,name=ahhf_rtu_6804,json=ahhfRtu6804,proto3" json:"ahhf_rtu_6804,omitempty"`
	// 开关灯，采用终端的wlst_rtu_4b00结构下发，应答采用wlst_rtu_cb00
	// 读取版本，采用ahhf.rtu.5c00命令，应答采用wlst_rtu_dc00
	// 读取开关量输出/输入/上下限参数,应答使用以下结构,cmd=ahhf.rtu.680a
	AhhfRtu_680A *AhhfRtu_6804 `protobuf:"bytes,2102,opt,name=ahhf_rtu_680a,json=ahhfRtu680a,proto3" json:"ahhf_rtu_680a,omitempty"`
	// 勃洛克单灯
	// 选测控制器数据
	BlkSlu_6891 *BlkSlu_6891 `protobuf:"bytes,2201,opt,name=blk_slu_6891,json=blkSlu6891,proto3" json:"blk_slu_6891,omitempty"`
	// 选测控制器数据应答
	BlkSlu_6892 *BlkSlu_6892 `protobuf:"bytes,2202,opt,name=blk_slu_6892,json=blkSlu6892,proto3" json:"blk_slu_6892,omitempty"`
	// 对时
	BlkSlu_6887 *BlkSlu_6891 `protobuf:"bytes,2203,opt,name=blk_slu_6887,json=blkSlu6887,proto3" json:"blk_slu_6887,omitempty"`
	// 对时应答
	BlkSlu_6888 *BlkSlu_6891 `protobuf:"bytes,2204,opt,name=blk_slu_6888,json=blkSlu6888,proto3" json:"blk_slu_6888,omitempty"`
	// 即时控制
	BlkSlu_6895 *BlkSlu_6895 `protobuf:"bytes,2205,opt,name=blk_slu_6895,json=blkSlu6895,proto3" json:"blk_slu_6895,omitempty"`
	// 即时控制应答
	BlkSlu_6896 *BlkSlu_6895 `protobuf:"bytes,2206,opt,name=blk_slu_6896,json=blkSlu6896,proto3" json:"blk_slu_6896,omitempty"`
	// 集中器定时设置
	BlkSlu_6889 *BlkSlu_6895 `protobuf:"bytes,2207,opt,name=blk_slu_6889,json=blkSlu6889,proto3" json:"blk_slu_6889,omitempty"`
	// 集中器定时设置应答
	BlkSlu_6890 *BlkSlu_6895 `protobuf:"bytes,2208,opt,name=blk_slu_6890,json=blkSlu6890,proto3" json:"blk_slu_6890,omitempty"`
	// 控制器回路数设置
	BlkSlu_6893 *BlkSlu_6891 `protobuf:"bytes,2209,opt,name=blk_slu_6893,json=blkSlu6893,proto3" json:"blk_slu_6893,omitempty"`
	// 控制器回路数设置应答
	BlkSlu_6894          *BlkSlu_6891 `protobuf:"bytes,2210,opt,name=blk_slu_6894,json=blkSlu6894,proto3" json:"blk_slu_6894,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *MsgWithCtrl) Reset()         { *m = MsgWithCtrl{} }
func (m *MsgWithCtrl) String() string { return proto.CompactTextString(m) }
func (*MsgWithCtrl) ProtoMessage()    {}
func (*MsgWithCtrl) Descriptor() ([]byte, []int) {
	return fileDescriptor_17a284b5b5297b67, []int{0}
}

func (m *MsgWithCtrl) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgWithCtrl.Unmarshal(m, b)
}
func (m *MsgWithCtrl) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgWithCtrl.Marshal(b, m, deterministic)
}
func (m *MsgWithCtrl) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgWithCtrl.Merge(m, src)
}
func (m *MsgWithCtrl) XXX_Size() int {
	return xxx_messageInfo_MsgWithCtrl.Size(m)
}
func (m *MsgWithCtrl) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgWithCtrl.DiscardUnknown(m)
}

var xxx_messageInfo_MsgWithCtrl proto.InternalMessageInfo

func (m *MsgWithCtrl) GetHead() *Head {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *MsgWithCtrl) GetArgs() *Args {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *MsgWithCtrl) GetSyscmds() *SysCommands {
	if m != nil {
		return m.Syscmds
	}
	return nil
}

func (m *MsgWithCtrl) GetPassthrough() *Passthrough {
	if m != nil {
		return m.Passthrough
	}
	return nil
}

func (m *MsgWithCtrl) GetWlstTml() *WlstTerminal {
	if m != nil {
		return m.WlstTml
	}
	return nil
}

func (m *MsgWithCtrl) GetWlstCom_0000() *WlstCom_0000 {
	if m != nil {
		return m.WlstCom_0000
	}
	return nil
}

func (m *MsgWithCtrl) GetWlstCom_3E01() *WlstCom_3E01 {
	if m != nil {
		return m.WlstCom_3E01
	}
	return nil
}

func (m *MsgWithCtrl) GetWlstCom_3E02() *WlstCom_3E02 {
	if m != nil {
		return m.WlstCom_3E02
	}
	return nil
}

func (m *MsgWithCtrl) GetWlstCom_3E82() *WlstCom_3E82 {
	if m != nil {
		return m.WlstCom_3E82
	}
	return nil
}

func (m *MsgWithCtrl) GetWlstCom_3E81() *WlstCom_3E02 {
	if m != nil {
		return m.WlstCom_3E81
	}
	return nil
}

func (m *MsgWithCtrl) GetWlstCom_3E84() *WlstCom_3E84 {
	if m != nil {
		return m.WlstCom_3E84
	}
	return nil
}

func (m *MsgWithCtrl) GetWxjyEsu_5500() *WxjyEsu_5500 {
	if m != nil {
		return m.WxjyEsu_5500
	}
	return nil
}

func (m *MsgWithCtrl) GetWxjyEsuD500() *WxjyEsu_5500 {
	if m != nil {
		return m.WxjyEsuD500
	}
	return nil
}

func (m *MsgWithCtrl) GetWxjyEsuD700() *WxjyEsuD700 {
	if m != nil {
		return m.WxjyEsuD700
	}
	return nil
}

func (m *MsgWithCtrl) GetWxjyEsuD800() *WxjyEsuD800 {
	if m != nil {
		return m.WxjyEsuD800
	}
	return nil
}

func (m *MsgWithCtrl) GetAhhfRtu_6804() *AhhfRtu_6804 {
	if m != nil {
		return m.AhhfRtu_6804
	}
	return nil
}

func (m *MsgWithCtrl) GetAhhfRtu_680A() *AhhfRtu_6804 {
	if m != nil {
		return m.AhhfRtu_680A
	}
	return nil
}

func (m *MsgWithCtrl) GetBlkSlu_6891() *BlkSlu_6891 {
	if m != nil {
		return m.BlkSlu_6891
	}
	return nil
}

func (m *MsgWithCtrl) GetBlkSlu_6892() *BlkSlu_6892 {
	if m != nil {
		return m.BlkSlu_6892
	}
	return nil
}

func (m *MsgWithCtrl) GetBlkSlu_6887() *BlkSlu_6891 {
	if m != nil {
		return m.BlkSlu_6887
	}
	return nil
}

func (m *MsgWithCtrl) GetBlkSlu_6888() *BlkSlu_6891 {
	if m != nil {
		return m.BlkSlu_6888
	}
	return nil
}

func (m *MsgWithCtrl) GetBlkSlu_6895() *BlkSlu_6895 {
	if m != nil {
		return m.BlkSlu_6895
	}
	return nil
}

func (m *MsgWithCtrl) GetBlkSlu_6896() *BlkSlu_6895 {
	if m != nil {
		return m.BlkSlu_6896
	}
	return nil
}

func (m *MsgWithCtrl) GetBlkSlu_6889() *BlkSlu_6895 {
	if m != nil {
		return m.BlkSlu_6889
	}
	return nil
}

func (m *MsgWithCtrl) GetBlkSlu_6890() *BlkSlu_6895 {
	if m != nil {
		return m.BlkSlu_6890
	}
	return nil
}

func (m *MsgWithCtrl) GetBlkSlu_6893() *BlkSlu_6891 {
	if m != nil {
		return m.BlkSlu_6893
	}
	return nil
}

func (m *MsgWithCtrl) GetBlkSlu_6894() *BlkSlu_6891 {
	if m != nil {
		return m.BlkSlu_6894
	}
	return nil
}

// 中间层报警信息提交
type SubmitAlarm struct {
	// Head head = 1;
	AlarmView            []*SubmitAlarm_AlarmView `protobuf:"bytes,2,rep,name=alarm_view,json=alarmView,proto3" json:"alarm_view,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *SubmitAlarm) Reset()         { *m = SubmitAlarm{} }
func (m *SubmitAlarm) String() string { return proto.CompactTextString(m) }
func (*SubmitAlarm) ProtoMessage()    {}
func (*SubmitAlarm) Descriptor() ([]byte, []int) {
	return fileDescriptor_17a284b5b5297b67, []int{1}
}

func (m *SubmitAlarm) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitAlarm.Unmarshal(m, b)
}
func (m *SubmitAlarm) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitAlarm.Marshal(b, m, deterministic)
}
func (m *SubmitAlarm) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitAlarm.Merge(m, src)
}
func (m *SubmitAlarm) XXX_Size() int {
	return xxx_messageInfo_SubmitAlarm.Size(m)
}
func (m *SubmitAlarm) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitAlarm.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitAlarm proto.InternalMessageInfo

func (m *SubmitAlarm) GetAlarmView() []*SubmitAlarm_AlarmView {
	if m != nil {
		return m.AlarmView
	}
	return nil
}

type SubmitAlarm_AlarmView struct {
	DtCreate             int64    `protobuf:"varint,1,opt,name=dt_create,json=dtCreate,proto3" json:"dt_create,omitempty"`
	ErrId                int32    `protobuf:"varint,2,opt,name=err_id,json=errId,proto3" json:"err_id,omitempty"`
	TmlId                int32    `protobuf:"varint,3,opt,name=tml_id,json=tmlId,proto3" json:"tml_id,omitempty"`
	LoopId               int32    `protobuf:"varint,4,opt,name=loop_id,json=loopId,proto3" json:"loop_id,omitempty"`
	LampId               int32    `protobuf:"varint,5,opt,name=lamp_id,json=lampId,proto3" json:"lamp_id,omitempty"`
	ErrCount             int32    `protobuf:"varint,6,opt,name=err_count,json=errCount,proto3" json:"err_count,omitempty"`
	DtRemove             int64    `protobuf:"varint,8,opt,name=dt_remove,json=dtRemove,proto3" json:"dt_remove,omitempty"`
	IsAlarm              int32    `protobuf:"varint,9,opt,name=is_alarm,json=isAlarm,proto3" json:"is_alarm,omitempty"`
	AlarmSrc             int32    `protobuf:"varint,10,opt,name=alarm_src,json=alarmSrc,proto3" json:"alarm_src,omitempty"`
	AlarmName            string   `protobuf:"bytes,11,opt,name=alarm_name,json=alarmName,proto3" json:"alarm_name,omitempty"`
	TmlName              string   `protobuf:"bytes,12,opt,name=tml_name,json=tmlName,proto3" json:"tml_name,omitempty"`
	LoopName             string   `protobuf:"bytes,13,opt,name=loop_name,json=loopName,proto3" json:"loop_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubmitAlarm_AlarmView) Reset()         { *m = SubmitAlarm_AlarmView{} }
func (m *SubmitAlarm_AlarmView) String() string { return proto.CompactTextString(m) }
func (*SubmitAlarm_AlarmView) ProtoMessage()    {}
func (*SubmitAlarm_AlarmView) Descriptor() ([]byte, []int) {
	return fileDescriptor_17a284b5b5297b67, []int{1, 0}
}

func (m *SubmitAlarm_AlarmView) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitAlarm_AlarmView.Unmarshal(m, b)
}
func (m *SubmitAlarm_AlarmView) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitAlarm_AlarmView.Marshal(b, m, deterministic)
}
func (m *SubmitAlarm_AlarmView) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitAlarm_AlarmView.Merge(m, src)
}
func (m *SubmitAlarm_AlarmView) XXX_Size() int {
	return xxx_messageInfo_SubmitAlarm_AlarmView.Size(m)
}
func (m *SubmitAlarm_AlarmView) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitAlarm_AlarmView.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitAlarm_AlarmView proto.InternalMessageInfo

func (m *SubmitAlarm_AlarmView) GetDtCreate() int64 {
	if m != nil {
		return m.DtCreate
	}
	return 0
}

func (m *SubmitAlarm_AlarmView) GetErrId() int32 {
	if m != nil {
		return m.ErrId
	}
	return 0
}

func (m *SubmitAlarm_AlarmView) GetTmlId() int32 {
	if m != nil {
		return m.TmlId
	}
	return 0
}

func (m *SubmitAlarm_AlarmView) GetLoopId() int32 {
	if m != nil {
		return m.LoopId
	}
	return 0
}

func (m *SubmitAlarm_AlarmView) GetLampId() int32 {
	if m != nil {
		return m.LampId
	}
	return 0
}

func (m *SubmitAlarm_AlarmView) GetErrCount() int32 {
	if m != nil {
		return m.ErrCount
	}
	return 0
}

func (m *SubmitAlarm_AlarmView) GetDtRemove() int64 {
	if m != nil {
		return m.DtRemove
	}
	return 0
}

func (m *SubmitAlarm_AlarmView) GetIsAlarm() int32 {
	if m != nil {
		return m.IsAlarm
	}
	return 0
}

func (m *SubmitAlarm_AlarmView) GetAlarmSrc() int32 {
	if m != nil {
		return m.AlarmSrc
	}
	return 0
}

func (m *SubmitAlarm_AlarmView) GetAlarmName() string {
	if m != nil {
		return m.AlarmName
	}
	return ""
}

func (m *SubmitAlarm_AlarmView) GetTmlName() string {
	if m != nil {
		return m.TmlName
	}
	return ""
}

func (m *SubmitAlarm_AlarmView) GetLoopName() string {
	if m != nil {
		return m.LoopName
	}
	return ""
}

// 中间层参数修改提交
type SubmitSettingChange struct {
	// 参数类型，1-参数变化（含增删改），2-时间表变化（含单灯，终端，增删改），3-定时任务变化（增删改）
	SettingType int32 `protobuf:"varint,1,opt,name=setting_type,json=settingType,proto3" json:"setting_type,omitempty"`
	// 设备逻辑地址，setting_type==3时可不填充
	TmlId                []int64  `protobuf:"varint,2,rep,packed,name=tml_id,json=tmlId,proto3" json:"tml_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubmitSettingChange) Reset()         { *m = SubmitSettingChange{} }
func (m *SubmitSettingChange) String() string { return proto.CompactTextString(m) }
func (*SubmitSettingChange) ProtoMessage()    {}
func (*SubmitSettingChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_17a284b5b5297b67, []int{2}
}

func (m *SubmitSettingChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitSettingChange.Unmarshal(m, b)
}
func (m *SubmitSettingChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitSettingChange.Marshal(b, m, deterministic)
}
func (m *SubmitSettingChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitSettingChange.Merge(m, src)
}
func (m *SubmitSettingChange) XXX_Size() int {
	return xxx_messageInfo_SubmitSettingChange.Size(m)
}
func (m *SubmitSettingChange) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitSettingChange.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitSettingChange proto.InternalMessageInfo

func (m *SubmitSettingChange) GetSettingType() int32 {
	if m != nil {
		return m.SettingType
	}
	return 0
}

func (m *SubmitSettingChange) GetTmlId() []int64 {
	if m != nil {
		return m.TmlId
	}
	return nil
}

func init() {
	proto.RegisterType((*MsgWithCtrl)(nil), "wlst.pb2.MsgWithCtrl")
	proto.RegisterType((*SubmitAlarm)(nil), "wlst.pb2.SubmitAlarm")
	proto.RegisterType((*SubmitAlarm_AlarmView)(nil), "wlst.pb2.SubmitAlarm.AlarmView")
	proto.RegisterType((*SubmitSettingChange)(nil), "wlst.pb2.SubmitSettingChange")
}

func init() { proto.RegisterFile("msg_with_ctrl.proto", fileDescriptor_17a284b5b5297b67) }

var fileDescriptor_17a284b5b5297b67 = []byte{
	// 834 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x96, 0xdd, 0x6e, 0xdb, 0x36,
	0x14, 0xc7, 0x67, 0xbb, 0x89, 0x6d, 0x2a, 0xdd, 0x5a, 0x06, 0x5d, 0xcf, 0x1c, 0x0c, 0xcb, 0x7c,
	0x95, 0x2b, 0x4f, 0x91, 0xed, 0x58, 0x01, 0x8a, 0x01, 0x89, 0x5b, 0xa0, 0x1d, 0xb0, 0x61, 0x90,
	0x83, 0xf5, 0x52, 0xa0, 0x25, 0xce, 0xd2, 0x4a, 0x5a, 0x06, 0x49, 0x27, 0xf3, 0xa3, 0xec, 0x7b,
	0xdd, 0xd5, 0x5e, 0x60, 0x7b, 0x8e, 0x75, 0x7b, 0x89, 0x7d, 0xbe, 0xc3, 0x40, 0xca, 0x8e, 0x15,
	0xba, 0x31, 0x74, 0x13, 0xf0, 0xfc, 0xff, 0xe7, 0xc7, 0x73, 0x78, 0x84, 0x98, 0x44, 0xfb, 0x5c,
	0x4e, 0xc2, 0xab, 0x54, 0x25, 0x61, 0xa4, 0x04, 0xeb, 0xcc, 0x44, 0xa6, 0x32, 0xdc, 0xb8, 0x62,
	0x52, 0x75, 0x66, 0x63, 0xaf, 0xb5, 0x6f, 0x84, 0x28, 0x63, 0x61, 0x42, 0x49, 0x9c, 0xdb, 0x2d,
	0x7c, 0x2d, 0x2a, 0xbe, 0x44, 0x5a, 0xf7, 0xd7, 0xda, 0x6c, 0x43, 0xea, 0x46, 0xb9, 0xd4, 0xfe,
	0x79, 0x0f, 0x39, 0x1f, 0xcb, 0xc9, 0xf3, 0x54, 0x25, 0x43, 0x25, 0x18, 0x6e, 0xa3, 0x3b, 0x7a,
	0x5f, 0xa8, 0x1c, 0x56, 0x8e, 0x1c, 0xef, 0xcd, 0xce, 0xaa, 0x6e, 0xe7, 0x29, 0x25, 0x71, 0x60,
	0x3c, 0x9d, 0x43, 0xc4, 0x44, 0x42, 0xd5, 0xce, 0x39, 0x13, 0x13, 0x19, 0x18, 0x0f, 0x7f, 0x80,
	0xea, 0x72, 0x21, 0x23, 0x1e, 0x4b, 0xa8, 0x99, 0xb4, 0x07, 0xeb, 0xb4, 0xd1, 0x42, 0x0e, 0x33,
	0xce, 0xc9, 0x34, 0x96, 0xc1, 0x2a, 0x0b, 0x0f, 0x90, 0xf3, 0x29, 0x91, 0x52, 0x25, 0x22, 0x9b,
	0x4f, 0x12, 0x88, 0x6c, 0xa8, 0x60, 0x06, 0xce, 0x6c, 0x1d, 0xe0, 0x63, 0x64, 0x86, 0xa3, 0x4f,
	0x0e, 0xb1, 0xa1, 0xde, 0x5e, 0x53, 0xcf, 0x99, 0x54, 0x17, 0x54, 0xf0, 0x74, 0x4a, 0x58, 0x50,
	0xd7, 0xf2, 0x05, 0x67, 0xf8, 0x11, 0xba, 0x6b, 0x90, 0x28, 0xe3, 0xa1, 0xeb, 0xba, 0x2e, 0xfc,
	0x59, 0x37, 0xe0, 0xc3, 0x9b, 0xe0, 0xb5, 0x1f, 0x38, 0x5a, 0x1f, 0x66, 0x5c, 0x07, 0x37, 0xe8,
	0x2e, 0x75, 0x8f, 0xe1, 0xaf, 0xdb, 0x69, 0xed, 0x5f, 0xd3, 0x3a, 0xb0, 0x69, 0x0f, 0xfe, 0xde,
	0x4a, 0x7b, 0x45, 0xda, 0xb3, 0x68, 0xdf, 0x83, 0x7f, 0xb6, 0xd1, 0x7e, 0x91, 0xf6, 0x37, 0xe8,
	0x63, 0xf8, 0xb7, 0x74, 0x6d, 0xdf, 0xee, 0xdc, 0xef, 0xc1, 0x7f, 0x5b, 0x6b, 0xf7, 0x8a, 0x74,
	0xcf, 0xd0, 0x5f, 0x7e, 0xb1, 0x08, 0xa9, 0x9c, 0x87, 0xfd, 0xbe, 0xeb, 0xc2, 0x6f, 0x6f, 0x6d,
	0xd0, 0x45, 0x3f, 0x70, 0x74, 0xfa, 0x13, 0x39, 0xd7, 0xc1, 0x0d, 0x3a, 0xd6, 0xf4, 0xab, 0x92,
	0xf4, 0xe3, 0x0d, 0x7a, 0xe0, 0xba, 0xf0, 0xfb, 0xed, 0xb4, 0xf6, 0xd7, 0xf4, 0xc0, 0xa6, 0x7d,
	0xd7, 0x85, 0x3f, 0xb6, 0xd0, 0x7e, 0x91, 0xf6, 0x73, 0x9a, 0x24, 0xc9, 0xe7, 0xa1, 0x50, 0xf3,
	0xf0, 0xc4, 0x77, 0x7b, 0xf0, 0xcb, 0x3d, 0x9b, 0x3e, 0x2b, 0xfa, 0x81, 0xa3, 0xd3, 0x03, 0x35,
	0xd7, 0x81, 0x4d, 0x13, 0xf8, 0xb5, 0x3c, 0x4d, 0xf0, 0x29, 0xda, 0x1b, 0xb3, 0x17, 0xa1, 0x64,
	0xda, 0x3c, 0x3d, 0x86, 0xaf, 0xee, 0xdb, 0xff, 0x1f, 0xe7, 0x05, 0x3b, 0x40, 0x63, 0xf6, 0x62,
	0xc4, 0xe6, 0x7a, 0x6d, 0xa1, 0x1e, 0x7c, 0xbd, 0x0d, 0xf5, 0x0a, 0xa8, 0x77, 0x13, 0xf5, 0x07,
	0xf0, 0x4d, 0xc9, 0xaa, 0xfe, 0xc0, 0x42, 0x7d, 0xf8, 0xb6, 0x2c, 0xea, 0x5b, 0x0d, 0xf7, 0xe1,
	0xbb, 0x6d, 0x68, 0xbf, 0xd0, 0x70, 0xdf, 0x42, 0x4f, 0xe0, 0xfb, 0xb2, 0xe8, 0x89, 0xd5, 0xf0,
	0x29, 0xfc, 0x50, 0x12, 0xf5, 0x4f, 0xad, 0xaa, 0x2e, 0xfc, 0x58, 0xb6, 0xaa, 0x6b, 0xa1, 0x5d,
	0x78, 0x59, 0xf6, 0xbb, 0x76, 0x2d, 0xb4, 0x07, 0x3f, 0x95, 0x45, 0x7b, 0xed, 0x97, 0x35, 0xe4,
	0x8c, 0xe6, 0x63, 0x9e, 0xaa, 0x33, 0x46, 0x04, 0xc7, 0x1f, 0x22, 0x44, 0xf4, 0x22, 0xbc, 0x4c,
	0xe9, 0x15, 0x54, 0x0f, 0x6b, 0x47, 0x8e, 0xf7, 0x5e, 0xe1, 0x57, 0x7e, 0x9d, 0xda, 0x31, 0x7f,
	0x3f, 0x4b, 0xe9, 0x55, 0xd0, 0x24, 0xab, 0x65, 0xeb, 0x55, 0x15, 0x35, 0xaf, 0x0d, 0x7c, 0x80,
	0x9a, 0xb1, 0x0a, 0x23, 0x41, 0x89, 0xa2, 0xe6, 0xf6, 0xa9, 0x05, 0x8d, 0x58, 0x0d, 0x4d, 0x8c,
	0x1f, 0xa0, 0x5d, 0x2a, 0x44, 0x98, 0xc6, 0xe6, 0xce, 0xd9, 0x09, 0x76, 0xa8, 0x10, 0xcf, 0x62,
	0x2d, 0x2b, 0xce, 0xb4, 0x5c, 0xcb, 0x65, 0xc5, 0xd9, 0xb3, 0x18, 0x3f, 0x44, 0x75, 0x96, 0x65,
	0x33, 0xad, 0xdf, 0x31, 0xfa, 0xae, 0x0e, 0x97, 0x06, 0xe1, 0xc6, 0xd8, 0x59, 0x1a, 0x84, 0x6b,
	0xe3, 0x00, 0x35, 0xf5, 0xfe, 0x51, 0x36, 0x9f, 0x2a, 0xd8, 0x35, 0x56, 0x83, 0x0a, 0x31, 0xd4,
	0xf1, 0xb2, 0x33, 0x41, 0x79, 0x76, 0x49, 0xa1, 0xb1, 0xea, 0x2c, 0x30, 0x31, 0x7e, 0x07, 0x35,
	0x52, 0x19, 0x9a, 0x43, 0x41, 0xd3, 0x80, 0xf5, 0x54, 0xe6, 0xf3, 0x39, 0x40, 0xf9, 0x61, 0x43,
	0x29, 0x22, 0x40, 0xf9, 0xa6, 0x46, 0x18, 0x89, 0x08, 0xbf, 0xbb, 0x1a, 0xde, 0x94, 0x70, 0x0a,
	0xce, 0x61, 0xe5, 0xa8, 0xb9, 0x9c, 0xcd, 0x27, 0x84, 0x9b, 0x6d, 0xf5, 0xc9, 0x8c, 0xb9, 0x67,
	0xcc, 0xba, 0xe2, 0xcc, 0x58, 0x07, 0xa8, 0x69, 0x4e, 0x67, 0xbc, 0xbb, 0xc6, 0x6b, 0x68, 0x41,
	0x9b, 0xed, 0x11, 0xda, 0xcf, 0xe7, 0x3e, 0xa2, 0x4a, 0xa5, 0xd3, 0xc9, 0x30, 0x21, 0xd3, 0x09,
	0xc5, 0xef, 0xa3, 0x3d, 0x99, 0x0b, 0xa1, 0x5a, 0xcc, 0xf2, 0xf9, 0xee, 0x04, 0xce, 0x52, 0xbb,
	0x58, 0xcc, 0x74, 0xc5, 0xd5, 0x2c, 0xf5, 0x97, 0xac, 0x9d, 0x57, 0xef, 0x55, 0x96, 0xf3, 0xf4,
	0x3e, 0x42, 0xe8, 0x31, 0xbd, 0x4c, 0x23, 0x6a, 0x5e, 0x08, 0x8f, 0x56, 0xd1, 0x93, 0x28, 0xc9,
	0x70, 0xe1, 0x86, 0x2e, 0x3c, 0x23, 0x5a, 0xaf, 0x97, 0xdb, 0x6f, 0x9c, 0x57, 0x9f, 0x56, 0xc6,
	0xbb, 0xe6, 0xe9, 0xd1, 0xfd, 0x3f, 0x00, 0x00, 0xff, 0xff, 0x81, 0x81, 0xe2, 0x8b, 0xea, 0x08,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DeviceCtrlClient is the client API for DeviceCtrl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DeviceCtrlClient interface {
	DeviceEcho(ctx context.Context, in *MsgWithCtrl, opts ...grpc.CallOption) (*MsgWithCtrl, error)
}

type deviceCtrlClient struct {
	cc *grpc.ClientConn
}

func NewDeviceCtrlClient(cc *grpc.ClientConn) DeviceCtrlClient {
	return &deviceCtrlClient{cc}
}

func (c *deviceCtrlClient) DeviceEcho(ctx context.Context, in *MsgWithCtrl, opts ...grpc.CallOption) (*MsgWithCtrl, error) {
	out := new(MsgWithCtrl)
	err := c.cc.Invoke(ctx, "/wlst.pb2.DeviceCtrl/DeviceEcho", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeviceCtrlServer is the server API for DeviceCtrl service.
type DeviceCtrlServer interface {
	DeviceEcho(context.Context, *MsgWithCtrl) (*MsgWithCtrl, error)
}

// UnimplementedDeviceCtrlServer can be embedded to have forward compatible implementations.
type UnimplementedDeviceCtrlServer struct {
}

func (*UnimplementedDeviceCtrlServer) DeviceEcho(ctx context.Context, req *MsgWithCtrl) (*MsgWithCtrl, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeviceEcho not implemented")
}

func RegisterDeviceCtrlServer(s *grpc.Server, srv DeviceCtrlServer) {
	s.RegisterService(&_DeviceCtrl_serviceDesc, srv)
}

func _DeviceCtrl_DeviceEcho_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgWithCtrl)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceCtrlServer).DeviceEcho(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wlst.pb2.DeviceCtrl/DeviceEcho",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceCtrlServer).DeviceEcho(ctx, req.(*MsgWithCtrl))
	}
	return interceptor(ctx, in, info, handler)
}

var _DeviceCtrl_serviceDesc = grpc.ServiceDesc{
	ServiceName: "wlst.pb2.DeviceCtrl",
	HandlerType: (*DeviceCtrlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeviceEcho",
			Handler:    _DeviceCtrl_DeviceEcho_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "msg_with_ctrl.proto",
}
