// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol_tml.proto

package wlst_pb2

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//数据服务和通讯服务传输格式
type WlstTerminal struct {
	//终端
	//设置终端物理地址
	WlstRtu_1900 *WlstRtu_1900 `protobuf:"bytes,10,opt,name=wlst_rtu_1900,json=wlstRtu1900,proto3" json:"wlst_rtu_1900,omitempty"`
	//设置工作参数
	WlstRtu_4000 *WlstRtu_4000 `protobuf:"bytes,11,opt,name=wlst_rtu_4000,json=wlstRtu4000,proto3" json:"wlst_rtu_4000,omitempty"`
	//设置显示参数
	WlstRtu_4101 *WlstRtu_4101 `protobuf:"bytes,12,opt,name=wlst_rtu_4101,json=wlstRtu4101,proto3" json:"wlst_rtu_4101,omitempty"`
	//设置显示参数
	WlstRtu_4104 *WlstRtu_4104 `protobuf:"bytes,13,opt,name=wlst_rtu_4104,json=wlstRtu4104,proto3" json:"wlst_rtu_4104,omitempty"`
	//设置显示参数
	WlstRtu_4110 *WlstRtu_4110 `protobuf:"bytes,14,opt,name=wlst_rtu_4110,json=wlstRtu4110,proto3" json:"wlst_rtu_4110,omitempty"`
	//设置口失参数
	WlstRtu_4201 *WlstRtu_4200 `protobuf:"bytes,15,opt,name=wlst_rtu_4201,json=wlstRtu4201,proto3" json:"wlst_rtu_4201,omitempty"`
	//设置口失参数
	WlstRtu_4204 *WlstRtu_4200 `protobuf:"bytes,16,opt,name=wlst_rtu_4204,json=wlstRtu4204,proto3" json:"wlst_rtu_4204,omitempty"`
	//设置口失参数
	WlstRtu_4210 *WlstRtu_4200 `protobuf:"bytes,17,opt,name=wlst_rtu_4210,json=wlstRtu4210,proto3" json:"wlst_rtu_4210,omitempty"`
	//设置上下限
	WlstRtu_4401 *WlstRtu_4401 `protobuf:"bytes,18,opt,name=wlst_rtu_4401,json=wlstRtu4401,proto3" json:"wlst_rtu_4401,omitempty"`
	//召测终端参数
	WlstRtuDa00 *WlstRtuDa00 `protobuf:"bytes,19,opt,name=wlst_rtu_da00,json=wlstRtuDa00,proto3" json:"wlst_rtu_da00,omitempty"`
	//设置电压
	WlstRtu_6100 *WlstRtu_6100 `protobuf:"bytes,20,opt,name=wlst_rtu_6100,json=wlstRtu6100,proto3" json:"wlst_rtu_6100,omitempty"`
	//选测数据
	WlstRtuA000 *WlstRtuA000 `protobuf:"bytes,21,opt,name=wlst_rtu_a000,json=wlstRtuA000,proto3" json:"wlst_rtu_a000,omitempty"`
	//所有回路开关灯
	WlstRtu_4B00 *WlstRtu_4B00 `protobuf:"bytes,22,opt,name=wlst_rtu_4b00,json=wlstRtu4b00,proto3" json:"wlst_rtu_4b00,omitempty"`
	//读取终端时间
	WlstRtu_9300 *WlstRtu_9300 `protobuf:"bytes,23,opt,name=wlst_rtu_9300,json=wlstRtu9300,proto3" json:"wlst_rtu_9300,omitempty"`
	//对时
	WlstRtu_1200 *WlstRtu_9300 `protobuf:"bytes,24,opt,name=wlst_rtu_1200,json=wlstRtu1200,proto3" json:"wlst_rtu_1200,omitempty"`
	//读周回路控制表1-3
	WlstRtuB200 *WlstRtuB200 `protobuf:"bytes,25,opt,name=wlst_rtu_b200,json=wlstRtuB200,proto3" json:"wlst_rtu_b200,omitempty"`
	//写周回路控制表1-3
	WlstRtu_3100 *WlstRtuB200 `protobuf:"bytes,26,opt,name=wlst_rtu_3100,json=wlstRtu3100,proto3" json:"wlst_rtu_3100,omitempty"`
	//写周回路控制表4-6
	WlstRtu_5800 *WlstRtuB200 `protobuf:"bytes,27,opt,name=wlst_rtu_5800,json=wlstRtu5800,proto3" json:"wlst_rtu_5800,omitempty"`
	//读周回路控制表4-6
	WlstRtuD900 *WlstRtuB200 `protobuf:"bytes,28,opt,name=wlst_rtu_d900,json=wlstRtuD900,proto3" json:"wlst_rtu_d900,omitempty"`
	//读周回路控制表7-8
	WlstRtuE900 *WlstRtuB200 `protobuf:"bytes,29,opt,name=wlst_rtu_e900,json=wlstRtuE900,proto3" json:"wlst_rtu_e900,omitempty"`
	//写周回路控制表7-8
	WlstRtu_6800 *WlstRtuB200 `protobuf:"bytes,30,opt,name=wlst_rtu_6800,json=wlstRtu6800,proto3" json:"wlst_rtu_6800,omitempty"`
	//召测节假日后4时段
	WlstRtuE600 *WlstRtuE600 `protobuf:"bytes,31,opt,name=wlst_rtu_e600,json=wlstRtuE600,proto3" json:"wlst_rtu_e600,omitempty"`
	//设置节假日前4时段
	WlstRtu_4600 *WlstRtuE600 `protobuf:"bytes,32,opt,name=wlst_rtu_4600,json=wlstRtu4600,proto3" json:"wlst_rtu_4600,omitempty"`
	//召测节假日前4时段
	WlstRtuC700 *WlstRtuE600 `protobuf:"bytes,33,opt,name=wlst_rtu_c700,json=wlstRtuC700,proto3" json:"wlst_rtu_c700,omitempty"`
	//设置节假日后4时段
	WlstRtu_6500 *WlstRtuE600 `protobuf:"bytes,34,opt,name=wlst_rtu_6500,json=wlstRtu6500,proto3" json:"wlst_rtu_6500,omitempty"`
	//执行端开机申请
	WlstRtu_9800 *WlstRtu_9800 `protobuf:"bytes,35,opt,name=wlst_rtu_9800,json=wlstRtu9800,proto3" json:"wlst_rtu_9800,omitempty"`
	//设置节能状态
	WlstRtuCc00 *WlstRtu_9800 `protobuf:"bytes,36,opt,name=wlst_rtu_cc00,json=wlstRtuCc00,proto3" json:"wlst_rtu_cc00,omitempty"`
	//设置节能状态
	WlstRtu_4C00 *WlstRtu_9800 `protobuf:"bytes,37,opt,name=wlst_rtu_4c00,json=wlstRtu4c00,proto3" json:"wlst_rtu_4c00,omitempty"`
	//召测终端软件版本
	WlstRtuDc00 *WlstRtuDc00 `protobuf:"bytes,38,opt,name=wlst_rtu_dc00,json=wlstRtuDc00,proto3" json:"wlst_rtu_dc00,omitempty"`
	//从终端主机板中读取全球唯一序列号
	WlstRtuAb00 *WlstRtuDc00 `protobuf:"bytes,39,opt,name=wlst_rtu_ab00,json=wlstRtuAb00,proto3" json:"wlst_rtu_ab00,omitempty"`
	//终端心跳包
	WlstRtu_7B00 *WlstRtu_7B00 `protobuf:"bytes,40,opt,name=wlst_rtu_7b00,json=wlstRtu7b00,proto3" json:"wlst_rtu_7b00,omitempty"`
	//终端单回路开关灯
	WlstRtu_2210 *WlstRtuA200 `protobuf:"bytes,41,opt,name=wlst_rtu_2210,json=wlstRtu2210,proto3" json:"wlst_rtu_2210,omitempty"`
	//单回路开关灯应答
	WlstRtuA200 *WlstRtuA200 `protobuf:"bytes,42,opt,name=wlst_rtu_a200,json=wlstRtuA200,proto3" json:"wlst_rtu_a200,omitempty"`
	//设置年开关灯
	WlstRtu_7060 *WlstRtu_7060 `protobuf:"bytes,43,opt,name=wlst_rtu_7060,json=wlstRtu7060,proto3" json:"wlst_rtu_7060,omitempty"`
	//设置年开关灯应答
	WlstRtu_70E0 *WlstRtu_70E0 `protobuf:"bytes,44,opt,name=wlst_rtu_70e0,json=wlstRtu70e0,proto3" json:"wlst_rtu_70e0,omitempty"`
	//招测年开关灯
	WlstRtu_7061 *WlstRtu_7061 `protobuf:"bytes,45,opt,name=wlst_rtu_7061,json=wlstRtu7061,proto3" json:"wlst_rtu_7061,omitempty"`
	//招测年开关灯应答
	WlstRtu_70E1 *WlstRtu_7060 `protobuf:"bytes,46,opt,name=wlst_rtu_70e1,json=wlstRtu70e1,proto3" json:"wlst_rtu_70e1,omitempty"`
	//远程升级准备
	WlstRtu_7006 *WlstRtu_7006 `protobuf:"bytes,47,opt,name=wlst_rtu_7006,json=wlstRtu7006,proto3" json:"wlst_rtu_7006,omitempty"`
	//查询包发送状态
	WlstRtu_7007 *WlstRtu_7007 `protobuf:"bytes,48,opt,name=wlst_rtu_7007,json=wlstRtu7007,proto3" json:"wlst_rtu_7007,omitempty"`
	//发送包
	WlstRtu_7008 *WlstRtu_7008 `protobuf:"bytes,49,opt,name=wlst_rtu_7008,json=wlstRtu7008,proto3" json:"wlst_rtu_7008,omitempty"`
	//发送缓存文件
	WlstRtuCupd *WlstRtu_7008 `protobuf:"bytes,50,opt,name=wlst_rtu_cupd,json=wlstRtuCupd,proto3" json:"wlst_rtu_cupd,omitempty"`
	//ftp升级数据
	WlstRtu_7003 *WlstRtu_7003 `protobuf:"bytes,51,opt,name=wlst_rtu_7003,json=wlstRtu7003,proto3" json:"wlst_rtu_7003,omitempty"`
	//升级数据包状态应答
	WlstRtu_7087 *WlstRtu_7087 `protobuf:"bytes,52,opt,name=wlst_rtu_7087,json=wlstRtu7087,proto3" json:"wlst_rtu_7087,omitempty"`
	//FTP升级应答
	WlstRtu_7083 *WlstRtu_7087 `protobuf:"bytes,53,opt,name=wlst_rtu_7083,json=wlstRtu7083,proto3" json:"wlst_rtu_7083,omitempty"`
	//修改主板通讯参数
	WlstRtu_700A *WlstRtu_700A `protobuf:"bytes,54,opt,name=wlst_rtu_700a,json=wlstRtu700a,proto3" json:"wlst_rtu_700a,omitempty"`
	// 3006终端复位
	WlstRtu_7010 *WlstRtu_7010 `protobuf:"bytes,55,opt,name=wlst_rtu_7010,json=wlstRtu7010,proto3" json:"wlst_rtu_7010,omitempty"`
	// 3006终端复位应答
	WlstRtu_7090 *WlstRtu_7010 `protobuf:"bytes,56,opt,name=wlst_rtu_7090,json=wlstRtu7090,proto3" json:"wlst_rtu_7090,omitempty"`
	// 召测k7,k8参数
	WlstRtuDf00 *WlstRtuDf00 `protobuf:"bytes,57,opt,name=wlst_rtu_df00,json=wlstRtuDf00,proto3" json:"wlst_rtu_df00,omitempty"`
	// 新版选测
	WlstRtu_70D0 *WlstRtu_70D0 `protobuf:"bytes,58,opt,name=wlst_rtu_70d0,json=wlstRtu70d0,proto3" json:"wlst_rtu_70d0,omitempty"`
	// 新版召测参数应答
	WlstRtu_70Da *WlstRtu_70Da `protobuf:"bytes,59,opt,name=wlst_rtu_70da,json=wlstRtu70da,proto3" json:"wlst_rtu_70da,omitempty"`
	// 多路开关灯应答
	WlstRtuCb00 *WlstRtuAns `protobuf:"bytes,60,opt,name=wlst_rtu_cb00,json=wlstRtuCb00,proto3" json:"wlst_rtu_cb00,omitempty"`
	// 对时应答
	WlstRtu_9200 *WlstRtuAns `protobuf:"bytes,61,opt,name=wlst_rtu_9200,json=wlstRtu9200,proto3" json:"wlst_rtu_9200,omitempty"`
	// 设置上下限应答
	WlstRtuC400 *WlstRtuAns `protobuf:"bytes,62,opt,name=wlst_rtu_c400,json=wlstRtuC400,proto3" json:"wlst_rtu_c400,omitempty"`
	// 招测事件
	WlstRtu_7800 *WlstRtu_7800 `protobuf:"bytes,63,opt,name=wlst_rtu_7800,json=wlstRtu7800,proto3" json:"wlst_rtu_7800,omitempty"`
	// 招测事件应答
	WlstRtuF800 *WlstRtu_7800 `protobuf:"bytes,64,opt,name=wlst_rtu_f800,json=wlstRtuF800,proto3" json:"wlst_rtu_f800,omitempty"`
	// 读取sd卡数据
	WlstRtu_7053 *WlstRtu_7053 `protobuf:"bytes,65,opt,name=wlst_rtu_7053,json=wlstRtu7053,proto3" json:"wlst_rtu_7053,omitempty"`
	// 读取sd卡数据应答
	WlstRtu_70D3 *WlstRtu_70D3 `protobuf:"bytes,66,opt,name=wlst_rtu_70d3,json=wlstRtu70d3,proto3" json:"wlst_rtu_70d3,omitempty"`
	// 远程升级完成主动上报
	WlstRtu_7081 *WlstRtu_7081 `protobuf:"bytes,67,opt,name=wlst_rtu_7081,json=wlstRtu7081,proto3" json:"wlst_rtu_7081,omitempty"`
	// 升级准备查询应答
	WlstRtu_7086 *WlstRtu_7081 `protobuf:"bytes,68,opt,name=wlst_rtu_7086,json=wlstRtu7086,proto3" json:"wlst_rtu_7086,omitempty"`
	// 升级版本查询
	WlstRtu_7085 *WlstRtu_7081 `protobuf:"bytes,69,opt,name=wlst_rtu_7085,json=wlstRtu7085,proto3" json:"wlst_rtu_7085,omitempty"`
	// 电能计量查询
	WlstRtu_7020 *WlstRtu_70A0 `protobuf:"bytes,70,opt,name=wlst_rtu_7020,json=wlstRtu7020,proto3" json:"wlst_rtu_7020,omitempty"`
	// 电能计量应答
	WlstRtu_70A0 *WlstRtu_70A0 `protobuf:"bytes,71,opt,name=wlst_rtu_70a0,json=wlstRtu70a0,proto3" json:"wlst_rtu_70a0,omitempty"`
	// 设置电能采集板互感器比值
	WlstRtu_4111 *WlstRtu_4111 `protobuf:"bytes,72,opt,name=wlst_rtu_4111,json=wlstRtu4111,proto3" json:"wlst_rtu_4111,omitempty"`
	// 设置电能采集板互感器比值应答
	WlstRtuC111 *WlstRtu_4111 `protobuf:"bytes,73,opt,name=wlst_rtu_c111,json=wlstRtuC111,proto3" json:"wlst_rtu_c111,omitempty"`
	// 新版招测参数
	WlstRtu_705A *WlstRtu_705A `protobuf:"bytes,74,opt,name=wlst_rtu_705a,json=wlstRtu705a,proto3" json:"wlst_rtu_705a,omitempty"`
	//设置各种参数应答
	WlstRtuCxxx *WlstRtu_4111 `protobuf:"bytes,75,opt,name=wlst_rtu_cxxx,json=wlstRtuCxxx,proto3" json:"wlst_rtu_cxxx,omitempty"`
	// 读取硬件相关参数
	WlstRtu_705B *WlstRtu_705B `protobuf:"bytes,76,opt,name=wlst_rtu_705b,json=wlstRtu705b,proto3" json:"wlst_rtu_705b,omitempty"`
	// 读取硬件相关参数应答
	WlstRtu_70Db *WlstRtu_705B `protobuf:"bytes,77,opt,name=wlst_rtu_70db,json=wlstRtu70db,proto3" json:"wlst_rtu_70db,omitempty"`
	// 3006主动上报
	WlstRtu_7094 *WlstRtu_7094 `protobuf:"bytes,78,opt,name=wlst_rtu_7094,json=wlstRtu7094,proto3" json:"wlst_rtu_7094,omitempty"`
	// 设置火零不平衡
	WlstRtu_7021 *WlstRtu_7021 `protobuf:"bytes,79,opt,name=wlst_rtu_7021,json=wlstRtu7021,proto3" json:"wlst_rtu_7021,omitempty"`
	// 设置火零不平衡应答 (填充status_code)
	WlstRtu_70A1 *WlstRtu_7021 `protobuf:"bytes,80,opt,name=wlst_rtu_70a1,json=wlstRtu70a1,proto3" json:"wlst_rtu_70a1,omitempty"`
	// 读取火零不平衡
	WlstRtu_7022 *WlstRtu_7021 `protobuf:"bytes,81,opt,name=wlst_rtu_7022,json=wlstRtu7022,proto3" json:"wlst_rtu_7022,omitempty"`
	// 读取火零不平衡应答
	WlstRtu_70A2 *WlstRtu_7021 `protobuf:"bytes,82,opt,name=wlst_rtu_70a2,json=wlstRtu70a2,proto3" json:"wlst_rtu_70a2,omitempty"`
	// 遥控
	WlstRtu_7023 *WlstRtu_7023 `protobuf:"bytes,83,opt,name=wlst_rtu_7023,json=wlstRtu7023,proto3" json:"wlst_rtu_7023,omitempty"`
	// 遥控应答
	WlstRtu_70A3 *WlstRtu_7023 `protobuf:"bytes,84,opt,name=wlst_rtu_70a3,json=wlstRtu70a3,proto3" json:"wlst_rtu_70a3,omitempty"`
	//线路检测
	//召测终端软件版本
	WlstLduDc00 *WlstRtuDc00 `protobuf:"bytes,200,opt,name=wlst_ldu_dc00,json=wlstLduDc00,proto3" json:"wlst_ldu_dc00,omitempty"`
	//选测回路状态
	WlstLdu_2600 *WlstLdu_2600 `protobuf:"bytes,201,opt,name=wlst_ldu_2600,json=wlstLdu2600,proto3" json:"wlst_ldu_2600,omitempty"`
	//读终端检测参数
	WlstLdu_5B00 *WlstLdu_2600 `protobuf:"bytes,202,opt,name=wlst_ldu_5b00,json=wlstLdu5b00,proto3" json:"wlst_ldu_5b00,omitempty"`
	//设置终端检测参数
	WlstLduC900 *WlstLdu_2600 `protobuf:"bytes,203,opt,name=wlst_ldu_c900,json=wlstLduC900,proto3" json:"wlst_ldu_c900,omitempty"`
	//自适应门限设置
	WlstLdu_4A01 *WlstLdu_2600 `protobuf:"bytes,204,opt,name=wlst_ldu_4a01,json=wlstLdu4a01,proto3" json:"wlst_ldu_4a01,omitempty"`
	//自适应门限设置
	WlstLduCa01 *WlstLdu_2600 `protobuf:"bytes,205,opt,name=wlst_ldu_ca01,json=wlstLduCa01,proto3" json:"wlst_ldu_ca01,omitempty"`
	//选测开灯阻抗基准
	WlstLdu_4D01 *WlstLdu_2600 `protobuf:"bytes,206,opt,name=wlst_ldu_4d01,json=wlstLdu4d01,proto3" json:"wlst_ldu_4d01,omitempty"`
	//选测开灯阻抗最大值
	WlstLdu_4D02 *WlstLdu_2600 `protobuf:"bytes,207,opt,name=wlst_ldu_4d02,json=wlstLdu4d02,proto3" json:"wlst_ldu_4d02,omitempty"`
	//复位开灯阻抗最大值
	WlstLdu_4D03 *WlstLdu_2600 `protobuf:"bytes,208,opt,name=wlst_ldu_4d03,json=wlstLdu4d03,proto3" json:"wlst_ldu_4d03,omitempty"`
	//选测开灯阻抗最大值
	WlstLduCd02 *WlstLdu_2600 `protobuf:"bytes,209,opt,name=wlst_ldu_cd02,json=wlstLduCd02,proto3" json:"wlst_ldu_cd02,omitempty"`
	//复位开灯阻抗最大值
	WlstLduCd03 *WlstLdu_2600 `protobuf:"bytes,210,opt,name=wlst_ldu_cd03,json=wlstLduCd03,proto3" json:"wlst_ldu_cd03,omitempty"`
	//选测回路状态
	WlstLduA600 *WlstLduA600 `protobuf:"bytes,211,opt,name=wlst_ldu_a600,json=wlstLduA600,proto3" json:"wlst_ldu_a600,omitempty"`
	//设置检测终端参数
	WlstLdu_4900 *WlstLdu_4900 `protobuf:"bytes,212,opt,name=wlst_ldu_4900,json=wlstLdu4900,proto3" json:"wlst_ldu_4900,omitempty"`
	//召测终端检测参数
	WlstLduDb00 *WlstLdu_4900 `protobuf:"bytes,213,opt,name=wlst_ldu_db00,json=wlstLduDb00,proto3" json:"wlst_ldu_db00,omitempty"`
	//选测开灯阻抗基准
	WlstLduCd01 *WlstLduCd01 `protobuf:"bytes,214,opt,name=wlst_ldu_cd01,json=wlstLduCd01,proto3" json:"wlst_ldu_cd01,omitempty"`
	//节能
	WlstEsu_9B00 *WlstRtuDc00  `protobuf:"bytes,800,opt,name=wlst_esu_9b00,json=wlstEsu9b00,proto3" json:"wlst_esu_9b00,omitempty"`
	WlstEsu_9200 *WlstEsu_9200 `protobuf:"bytes,801,opt,name=wlst_esu_9200,json=wlstEsu9200,proto3" json:"wlst_esu_9200,omitempty"`
	WlstEsu_1100 *WlstEsu_9200 `protobuf:"bytes,802,opt,name=wlst_esu_1100,json=wlstEsu1100,proto3" json:"wlst_esu_1100,omitempty"`
	WlstEsu_9E00 *WlstEsu_9E00 `protobuf:"bytes,803,opt,name=wlst_esu_9e00,json=wlstEsu9e00,proto3" json:"wlst_esu_9e00,omitempty"`
	WlstEsu_1D00 *WlstEsu_9E00 `protobuf:"bytes,804,opt,name=wlst_esu_1d00,json=wlstEsu1d00,proto3" json:"wlst_esu_1d00,omitempty"`
	WlstEsu_9A00 *WlstEsu_9A00 `protobuf:"bytes,805,opt,name=wlst_esu_9a00,json=wlstEsu9a00,proto3" json:"wlst_esu_9a00,omitempty"`
	WlstEsu_1900 *WlstEsu_1900 `protobuf:"bytes,806,opt,name=wlst_esu_1900,json=wlstEsu1900,proto3" json:"wlst_esu_1900,omitempty"`
	WlstEsu_2500 *WlstEsu_1900 `protobuf:"bytes,807,opt,name=wlst_esu_2500,json=wlstEsu2500,proto3" json:"wlst_esu_2500,omitempty"`
	WlstEsu_1800 *WlstEsu_1800 `protobuf:"bytes,808,opt,name=wlst_esu_1800,json=wlstEsu1800,proto3" json:"wlst_esu_1800,omitempty"`
	WlstEsu_9700 *WlstEsu_9700 `protobuf:"bytes,809,opt,name=wlst_esu_9700,json=wlstEsu9700,proto3" json:"wlst_esu_9700,omitempty"`
	WlstEsu_1700 *WlstEsu_9700 `protobuf:"bytes,810,opt,name=wlst_esu_1700,json=wlstEsu1700,proto3" json:"wlst_esu_1700,omitempty"`
	WlstEsu_1A00 *WlstEsu_9700 `protobuf:"bytes,811,opt,name=wlst_esu_1a00,json=wlstEsu1a00,proto3" json:"wlst_esu_1a00,omitempty"`
	WlstEsu_9500 *WlstEsu_9500 `protobuf:"bytes,812,opt,name=wlst_esu_9500,json=wlstEsu9500,proto3" json:"wlst_esu_9500,omitempty"`
	WlstEsu_1400 *WlstEsu_9500 `protobuf:"bytes,813,opt,name=wlst_esu_1400,json=wlstEsu1400,proto3" json:"wlst_esu_1400,omitempty"`
	WlstEsu_9F00 *WlstEsu_9F00 `protobuf:"bytes,814,opt,name=wlst_esu_9f00,json=wlstEsu9f00,proto3" json:"wlst_esu_9f00,omitempty"`
	WlstEsu_9300 *WlstEsu_9F00 `protobuf:"bytes,815,opt,name=wlst_esu_9300,json=wlstEsu9300,proto3" json:"wlst_esu_9300,omitempty"`
	WlstEsu_9400 *WlstEsu_9400 `protobuf:"bytes,816,opt,name=wlst_esu_9400,json=wlstEsu9400,proto3" json:"wlst_esu_9400,omitempty"`
	WlstEsu_9000 *WlstEsu_9000 `protobuf:"bytes,817,opt,name=wlst_esu_9000,json=wlstEsu9000,proto3" json:"wlst_esu_9000,omitempty"`
	WlstEsu_9100 *WlstEsu_9000 `protobuf:"bytes,818,opt,name=wlst_esu_9100,json=wlstEsu9100,proto3" json:"wlst_esu_9100,omitempty"`
	WlstEsu_9900 *WlstEsu_9000 `protobuf:"bytes,819,opt,name=wlst_esu_9900,json=wlstEsu9900,proto3" json:"wlst_esu_9900,omitempty"`
	WlstEsu_9D00 *WlstEsu_9000 `protobuf:"bytes,820,opt,name=wlst_esu_9d00,json=wlstEsu9d00,proto3" json:"wlst_esu_9d00,omitempty"`
	WlstEsuA500  *WlstEsu_9000 `protobuf:"bytes,821,opt,name=wlst_esu_a500,json=wlstEsuA500,proto3" json:"wlst_esu_a500,omitempty"`
	WlstEsu_1600 *WlstEsu_1600 `protobuf:"bytes,822,opt,name=wlst_esu_1600,json=wlstEsu1600,proto3" json:"wlst_esu_1600,omitempty"`
	WlstEsu_9600 *WlstEsu_9000 `protobuf:"bytes,823,opt,name=wlst_esu_9600,json=wlstEsu9600,proto3" json:"wlst_esu_9600,omitempty"`
	WlstEsu_9800 *WlstEsu_9000 `protobuf:"bytes,825,opt,name=wlst_esu_9800,json=wlstEsu9800,proto3" json:"wlst_esu_9800,omitempty"`
	WlstEsuA200  *WlstEsu_9000 `protobuf:"bytes,826,opt,name=wlst_esu_a200,json=wlstEsuA200,proto3" json:"wlst_esu_a200,omitempty"`
	WlstEsuA300  *WlstEsu_9000 `protobuf:"bytes,827,opt,name=wlst_esu_a300,json=wlstEsuA300,proto3" json:"wlst_esu_a300,omitempty"`
	//光照度,GPS,抄表
	//gps数据
	WlstGps_0000 *WlstGps_0000 `protobuf:"bytes,400,opt,name=wlst_gps_0000,json=wlstGps0000,proto3" json:"wlst_gps_0000,omitempty"`
	//wx2002gps 读版本
	WlstGps_5903 *WlstGps_5903 `protobuf:"bytes,434,opt,name=wlst_gps_5903,json=wlstGps5903,proto3" json:"wlst_gps_5903,omitempty"`
	WlstGps_5983 *WlstGps_5903 `protobuf:"bytes,435,opt,name=wlst_gps_5983,json=wlstGps5983,proto3" json:"wlst_gps_5983,omitempty"`
	//wx2002gps 选测
	WlstGps_5904 *WlstGps_5904 `protobuf:"bytes,436,opt,name=wlst_gps_5904,json=wlstGps5904,proto3" json:"wlst_gps_5904,omitempty"`
	WlstGps_5984 *WlstGps_5904 `protobuf:"bytes,437,opt,name=wlst_gps_5984,json=wlstGps5984,proto3" json:"wlst_gps_5984,omitempty"`
	//选测2（多光控）
	WlstAlsA700  *WlstAlsA700 `protobuf:"bytes,401,opt,name=wlst_als_a700,json=wlstAlsA700,proto3" json:"wlst_als_a700,omitempty"`
	WlstAls_2700 *WlstAlsA700 `protobuf:"bytes,402,opt,name=wlst_als_2700,json=wlstAls2700,proto3" json:"wlst_als_2700,omitempty"`
	//设置模式（多光控）
	WlstAlsB700 *WlstAlsA700 `protobuf:"bytes,403,opt,name=wlst_als_b700,json=wlstAlsB700,proto3" json:"wlst_als_b700,omitempty"`
	//设置地址（多光控）
	WlstAlsA500  *WlstAlsA700 `protobuf:"bytes,404,opt,name=wlst_als_a500,json=wlstAlsA500,proto3" json:"wlst_als_a500,omitempty"`
	WlstAls_2500 *WlstAlsA700 `protobuf:"bytes,405,opt,name=wlst_als_2500,json=wlstAls2500,proto3" json:"wlst_als_2500,omitempty"`
	//设置上报数据间隔时间
	WlstAlsB800 *WlstAlsA700 `protobuf:"bytes,406,opt,name=wlst_als_b800,json=wlstAlsB800,proto3" json:"wlst_als_b800,omitempty"`
	//设置模式
	WlstAlsB600 *WlstAlsA700 `protobuf:"bytes,407,opt,name=wlst_als_b600,json=wlstAlsB600,proto3" json:"wlst_als_b600,omitempty"`
	//设置模式
	WlstAls_3600 *WlstAlsA700 `protobuf:"bytes,408,opt,name=wlst_als_3600,json=wlstAls3600,proto3" json:"wlst_als_3600,omitempty"`
	//召测模式
	WlstAlsC600 *WlstAlsA700 `protobuf:"bytes,409,opt,name=wlst_als_c600,json=wlstAlsC600,proto3" json:"wlst_als_c600,omitempty"`
	//设置模式（多光控）
	WlstAls_3700 *WlstAlsA700 `protobuf:"bytes,410,opt,name=wlst_als_3700,json=wlstAls3700,proto3" json:"wlst_als_3700,omitempty"`
	//对终端主报数据（RS485）（多光控）
	WlstAlsA800 *WlstAlsA700 `protobuf:"bytes,411,opt,name=wlst_als_a800,json=wlstAlsA800,proto3" json:"wlst_als_a800,omitempty"`
	//召测模式（多光控）
	WlstAlsC700  *WlstAlsA700 `protobuf:"bytes,412,opt,name=wlst_als_c700,json=wlstAlsC700,proto3" json:"wlst_als_c700,omitempty"`
	WlstAls_4700 *WlstAlsA700 `protobuf:"bytes,413,opt,name=wlst_als_4700,json=wlstAls4700,proto3" json:"wlst_als_4700,omitempty"`
	//设置上报数据间隔时间
	WlstAls_3800 *WlstAlsA700 `protobuf:"bytes,414,opt,name=wlst_als_3800,json=wlstAls3800,proto3" json:"wlst_als_3800,omitempty"`
	//召测上报数据间隔时间
	WlstAlsC800  *WlstAlsA700 `protobuf:"bytes,415,opt,name=wlst_als_c800,json=wlstAlsC800,proto3" json:"wlst_als_c800,omitempty"`
	WlstAls_4800 *WlstAlsA700 `protobuf:"bytes,416,opt,name=wlst_als_4800,json=wlstAls4800,proto3" json:"wlst_als_4800,omitempty"`
	//召测软件版本
	WlstAlsCa00  *WlstAlsA700 `protobuf:"bytes,417,opt,name=wlst_als_ca00,json=wlstAlsCa00,proto3" json:"wlst_als_ca00,omitempty"`
	WlstAls_4A00 *WlstAlsA700 `protobuf:"bytes,418,opt,name=wlst_als_4a00,json=wlstAls4a00,proto3" json:"wlst_als_4a00,omitempty"`
	//选测1
	WlstAlsA600 *WlstAlsA700 `protobuf:"bytes,419,opt,name=wlst_als_a600,json=wlstAlsA600,proto3" json:"wlst_als_a600,omitempty"`
	//2007读电表数据
	WlstMru_9100 *WlstMru_9100 `protobuf:"bytes,430,opt,name=wlst_mru_9100,json=wlstMru9100,proto3" json:"wlst_mru_9100,omitempty"`
	//2007读电表数据
	WlstMru_1100 *WlstMru_9100 `protobuf:"bytes,431,opt,name=wlst_mru_1100,json=wlstMru1100,proto3" json:"wlst_mru_1100,omitempty"`
	//2007读电表地址
	WlstMru_9300 *WlstMru_9100 `protobuf:"bytes,432,opt,name=wlst_mru_9300,json=wlstMru9300,proto3" json:"wlst_mru_9300,omitempty"`
	//2007读电表地址
	WlstMru_1300 *WlstMru_9100 `protobuf:"bytes,433,opt,name=wlst_mru_1300,json=wlstMru1300,proto3" json:"wlst_mru_1300,omitempty"`
	// 漏电
	// 手动操作
	WlstElu_6257 *WlstElu_6257 `protobuf:"bytes,438,opt,name=wlst_elu_6257,json=wlstElu6257,proto3" json:"wlst_elu_6257,omitempty"`
	WlstElu_62D7 *WlstElu_6257 `protobuf:"bytes,439,opt,name=wlst_elu_62d7,json=wlstElu62d7,proto3" json:"wlst_elu_62d7,omitempty"`
	// 主动报警/选测应答,漏电/温度
	WlstElu_62D8 *WlstElu_62D8 `protobuf:"bytes,440,opt,name=wlst_elu_62d8,json=wlstElu62d8,proto3" json:"wlst_elu_62d8,omitempty"`
	// 查询事件
	WlstElu_625A *WlstElu_625A `protobuf:"bytes,444,opt,name=wlst_elu_625a,json=wlstElu625a,proto3" json:"wlst_elu_625a,omitempty"`
	WlstElu_62Da *WlstElu_625A `protobuf:"bytes,445,opt,name=wlst_elu_62da,json=wlstElu62da,proto3" json:"wlst_elu_62da,omitempty"`
	// 设置检测门限
	WlstElu_625B *WlstElu_625B `protobuf:"bytes,446,opt,name=wlst_elu_625b,json=wlstElu625b,proto3" json:"wlst_elu_625b,omitempty"`
	WlstElu_62Db *WlstElu_625B `protobuf:"bytes,447,opt,name=wlst_elu_62db,json=wlstElu62db,proto3" json:"wlst_elu_62db,omitempty"`
	// 设置时钟
	WlstElu_625C *WlstElu_625C `protobuf:"bytes,448,opt,name=wlst_elu_625c,json=wlstElu625c,proto3" json:"wlst_elu_625c,omitempty"`
	WlstElu_62Dc *WlstElu_625C `protobuf:"bytes,449,opt,name=wlst_elu_62dc,json=wlstElu62dc,proto3" json:"wlst_elu_62dc,omitempty"`
	// 召测参数
	WlstElu_62Dd *WlstElu_6256 `protobuf:"bytes,450,opt,name=wlst_elu_62dd,json=wlstElu62dd,proto3" json:"wlst_elu_62dd,omitempty"`
	// 召测时钟
	WlstElu_62De *WlstElu_625C `protobuf:"bytes,451,opt,name=wlst_elu_62de,json=wlstElu62de,proto3" json:"wlst_elu_62de,omitempty"`
	// 复位应答
	WlstElu_62Df *WlstElu_6255 `protobuf:"bytes,452,opt,name=wlst_elu_62df,json=wlstElu62df,proto3" json:"wlst_elu_62df,omitempty"`
	// 设置地址
	WlstElu_6255 *WlstElu_6255 `protobuf:"bytes,453,opt,name=wlst_elu_6255,json=wlstElu6255,proto3" json:"wlst_elu_6255,omitempty"`
	WlstElu_62D5 *WlstElu_6255 `protobuf:"bytes,454,opt,name=wlst_elu_62d5,json=wlstElu62d5,proto3" json:"wlst_elu_62d5,omitempty"`
	// 设置运行参数
	WlstElu_6256 *WlstElu_6256 `protobuf:"bytes,455,opt,name=wlst_elu_6256,json=wlstElu6256,proto3" json:"wlst_elu_6256,omitempty"`
	WlstElu_62D6 *WlstElu_6256 `protobuf:"bytes,456,opt,name=wlst_elu_62d6,json=wlstElu62d6,proto3" json:"wlst_elu_62d6,omitempty"`
	//单灯
	//复位网络
	WlstSlu_1900 *WlstSlu_2400 `protobuf:"bytes,601,opt,name=wlst_slu_1900,json=wlstSlu1900,proto3" json:"wlst_slu_1900,omitempty"`
	//复位网络应答
	WlstSlu_9900 *WlstSlu_2400 `protobuf:"bytes,602,opt,name=wlst_slu_9900,json=wlstSlu9900,proto3" json:"wlst_slu_9900,omitempty"`
	//招测集中器版本
	WlstSluD000 *WlstSluD000 `protobuf:"bytes,603,opt,name=wlst_slu_d000,json=wlstSluD000,proto3" json:"wlst_slu_d000,omitempty"`
	//启动停止集中器巡测
	WlstSlu_2400 *WlstSlu_2400 `protobuf:"bytes,604,opt,name=wlst_slu_2400,json=wlstSlu2400,proto3" json:"wlst_slu_2400,omitempty"`
	//启动停止集中器巡测 应答
	WlstSluA400 *WlstSluF400 `protobuf:"bytes,605,opt,name=wlst_slu_a400,json=wlstSluA400,proto3" json:"wlst_slu_a400,omitempty"`
	//设置集中器停运主报
	WlstSlu_2800 *WlstSlu_2800 `protobuf:"bytes,606,opt,name=wlst_slu_2800,json=wlstSlu2800,proto3" json:"wlst_slu_2800,omitempty"`
	//设置集中器停运主报 应答
	WlstSluA800 *WlstSluF400 `protobuf:"bytes,607,opt,name=wlst_slu_a800,json=wlstSluA800,proto3" json:"wlst_slu_a800,omitempty"`
	//设置集中器参数
	WlstSlu_3000 *WlstSlu_3000 `protobuf:"bytes,608,opt,name=wlst_slu_3000,json=wlstSlu3000,proto3" json:"wlst_slu_3000,omitempty"`
	//设置集中器参数 应答
	WlstSluB000 *WlstSluF400 `protobuf:"bytes,609,opt,name=wlst_slu_b000,json=wlstSluB000,proto3" json:"wlst_slu_b000,omitempty"`
	//选测集中器参数 应答
	WlstSluB200 *WlstSlu_3000 `protobuf:"bytes,610,opt,name=wlst_slu_b200,json=wlstSluB200,proto3" json:"wlst_slu_b200,omitempty"`
	//招测控制器域名更改信息 应答
	WlstSlu_9A00 *WlstSlu_9A00 `protobuf:"bytes,611,opt,name=wlst_slu_9a00,json=wlstSlu9a00,proto3" json:"wlst_slu_9a00,omitempty"`
	//选测集中器报警参数 应答
	WlstSluCd00 *WlstSluCd00 `protobuf:"bytes,612,opt,name=wlst_slu_cd00,json=wlstSluCd00,proto3" json:"wlst_slu_cd00,omitempty"`
	//设置控制器域名
	WlstSlu_1C00 *WlstSlu_1C00 `protobuf:"bytes,613,opt,name=wlst_slu_1c00,json=wlstSlu1c00,proto3" json:"wlst_slu_1c00,omitempty"`
	//设置控制器域名 应答
	WlstSlu_9C00 *WlstSluF400 `protobuf:"bytes,614,opt,name=wlst_slu_9c00,json=wlstSlu9c00,proto3" json:"wlst_slu_9c00,omitempty"`
	//选测未知控制器
	WlstSlu_1D00 *WlstSlu_1D00 `protobuf:"bytes,615,opt,name=wlst_slu_1d00,json=wlstSlu1d00,proto3" json:"wlst_slu_1d00,omitempty"`
	//选测未知控制器 应答
	WlstSlu_9D00 *WlstSlu_9D00 `protobuf:"bytes,616,opt,name=wlst_slu_9d00,json=wlstSlu9d00,proto3" json:"wlst_slu_9d00,omitempty"`
	//复位以及参数初始化
	WlstSlu_7000 *WlstSluF000 `protobuf:"bytes,617,opt,name=wlst_slu_7000,json=wlstSlu7000,proto3" json:"wlst_slu_7000,omitempty"`
	//复位以及参数初始化 应答
	WlstSluF000 *WlstSluF000 `protobuf:"bytes,618,opt,name=wlst_slu_f000,json=wlstSluF000,proto3" json:"wlst_slu_f000,omitempty"`
	//时钟设置
	WlstSlu_7100 *WlstSluF100 `protobuf:"bytes,619,opt,name=wlst_slu_7100,json=wlstSlu7100,proto3" json:"wlst_slu_7100,omitempty"`
	//时钟设置 应答
	WlstSluF100 *WlstSluF100 `protobuf:"bytes,620,opt,name=wlst_slu_f100,json=wlstSluF100,proto3" json:"wlst_slu_f100,omitempty"`
	//控制器参数设置读取
	WlstSlu_7200 *WlstSluF200 `protobuf:"bytes,621,opt,name=wlst_slu_7200,json=wlstSlu7200,proto3" json:"wlst_slu_7200,omitempty"`
	//控制器参数设置读取 应答
	WlstSluF200 *WlstSluF200 `protobuf:"bytes,622,opt,name=wlst_slu_f200,json=wlstSluF200,proto3" json:"wlst_slu_f200,omitempty"`
	//选测 （集中器缓存）
	WlstSlu_7300 *WlstSlu_7300 `protobuf:"bytes,623,opt,name=wlst_slu_7300,json=wlstSlu7300,proto3" json:"wlst_slu_7300,omitempty"`
	//选测 应答
	WlstSluF300 *WlstSlu_7300 `protobuf:"bytes,624,opt,name=wlst_slu_f300,json=wlstSluF300,proto3" json:"wlst_slu_f300,omitempty"`
	//设置时间（485用，到集中器）
	WlstSlu_7400 *WlstSlu_7400 `protobuf:"bytes,625,opt,name=wlst_slu_7400,json=wlstSlu7400,proto3" json:"wlst_slu_7400,omitempty"`
	//设置时间（485用，到集中器） 应答
	WlstSluF400 *WlstSluF400 `protobuf:"bytes,626,opt,name=wlst_slu_f400,json=wlstSluF400,proto3" json:"wlst_slu_f400,omitempty"`
	//设置时间（gprs用，到集中器）
	//wlst.pb2.Wlst_slu_7400 wlst_slu_7d00 = 627;
	//设置时间（gprs用，到集中器） 应答
	//wlst.pb2.Wlst_slu_f400 wlst_slu_fd00 = 628;
	//设置集中器报警参数
	WlstSlu_7600 *WlstSluCd00 `protobuf:"bytes,629,opt,name=wlst_slu_7600,json=wlstSlu7600,proto3" json:"wlst_slu_7600,omitempty"`
	//设置集中器报警参数 应答
	WlstSluF600 *WlstSluF400 `protobuf:"bytes,630,opt,name=wlst_slu_f600,json=wlstSluF600,proto3" json:"wlst_slu_f600,omitempty"`
	//集中器主动上报
	WlstSluF900 *WlstSluF900 `protobuf:"bytes,631,opt,name=wlst_slu_f900,json=wlstSluF900,proto3" json:"wlst_slu_f900,omitempty"`
	//选测控制器参数
	WlstSlu_7A00 *WlstSlu_1D00 `protobuf:"bytes,632,opt,name=wlst_slu_7a00,json=wlstSlu7a00,proto3" json:"wlst_slu_7a00,omitempty"`
	//选测控制器参数 应答
	WlstSluFa00 *WlstSlu_9D00 `protobuf:"bytes,633,opt,name=wlst_slu_fa00,json=wlstSluFa00,proto3" json:"wlst_slu_fa00,omitempty"`
	//读取短程控制参数
	WlstSlu_7B00 *WlstSlu_7B00 `protobuf:"bytes,634,opt,name=wlst_slu_7b00,json=wlstSlu7b00,proto3" json:"wlst_slu_7b00,omitempty"`
	//读取短程控制参数 应答
	WlstSluFb00 *WlstSlu_7B00 `protobuf:"bytes,635,opt,name=wlst_slu_fb00,json=wlstSluFb00,proto3" json:"wlst_slu_fb00,omitempty"`
	//集中器返回操作失败的控制器
	WlstSluFe00 *WlstSluFe00 `protobuf:"bytes,636,opt,name=wlst_slu_fe00,json=wlstSluFe00,proto3" json:"wlst_slu_fe00,omitempty"`
	//设置本地控制参数（到控制器）
	WlstSlu_7C00 *WlstSlu_7C00 `protobuf:"bytes,637,opt,name=wlst_slu_7c00,json=wlstSlu7c00,proto3" json:"wlst_slu_7c00,omitempty"`
	//设置本地控制参数 应答
	WlstSluFc00 *WlstSluF400 `protobuf:"bytes,638,opt,name=wlst_slu_fc00,json=wlstSluFc00,proto3" json:"wlst_slu_fc00,omitempty"`
	//控制器复位以及参数初始化
	WlstSlu_6F00 *WlstSlu_6F00 `protobuf:"bytes,639,opt,name=wlst_slu_6f00,json=wlstSlu6f00,proto3" json:"wlst_slu_6f00,omitempty"`
	//控制器复位以及参数初始化 应答
	WlstSluEf00 *WlstSlu_6F00 `protobuf:"bytes,640,opt,name=wlst_slu_ef00,json=wlstSluEf00,proto3" json:"wlst_slu_ef00,omitempty"`
	//设置延迟巡测间隔
	WlstSlu_6E00 *WlstSlu_6E00 `protobuf:"bytes,641,opt,name=wlst_slu_6e00,json=wlstSlu6e00,proto3" json:"wlst_slu_6e00,omitempty"`
	//延迟巡测间隔招测/应答
	WlstSluEe00 *WlstSlu_6E00 `protobuf:"bytes,642,opt,name=wlst_slu_ee00,json=wlstSluEe00,proto3" json:"wlst_slu_ee00,omitempty"`
	// 设置单灯节假日
	WlstSlu_6B00 *WlstSlu_6B00 `protobuf:"bytes,643,opt,name=wlst_slu_6b00,json=wlstSlu6b00,proto3" json:"wlst_slu_6b00,omitempty"`
	// 设置单灯节假日应答
	WlstSluEb00 *WlstSluF400 `protobuf:"bytes,644,opt,name=wlst_slu_eb00,json=wlstSluEb00,proto3" json:"wlst_slu_eb00,omitempty"`
	// 召测单灯节假日设置
	WlstSlu_6C00 *WlstSlu_6C00 `protobuf:"bytes,645,opt,name=wlst_slu_6c00,json=wlstSlu6c00,proto3" json:"wlst_slu_6c00,omitempty"`
	// 召测单灯节假日设置应答
	WlstSluEc00 *WlstSluEc00 `protobuf:"bytes,646,opt,name=wlst_slu_ec00,json=wlstSluEc00,proto3" json:"wlst_slu_ec00,omitempty"`
	// 召测事件记录
	WlstSlu_7800 *WlstSlu_7800 `protobuf:"bytes,647,opt,name=wlst_slu_7800,json=wlstSlu7800,proto3" json:"wlst_slu_7800,omitempty"`
	// 召测事件记录应答
	WlstSluF800 *WlstSluF800 `protobuf:"bytes,648,opt,name=wlst_slu_f800,json=wlstSluF800,proto3" json:"wlst_slu_f800,omitempty"`
	// nb控制器数据主报
	WlstSluB900          *WlstSlu_3900 `protobuf:"bytes,649,opt,name=wlst_slu_b900,json=wlstSluB900,proto3" json:"wlst_slu_b900,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *WlstTerminal) Reset()         { *m = WlstTerminal{} }
func (m *WlstTerminal) String() string { return proto.CompactTextString(m) }
func (*WlstTerminal) ProtoMessage()    {}
func (*WlstTerminal) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e80f3177279cb0c, []int{0}
}

func (m *WlstTerminal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WlstTerminal.Unmarshal(m, b)
}
func (m *WlstTerminal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WlstTerminal.Marshal(b, m, deterministic)
}
func (m *WlstTerminal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WlstTerminal.Merge(m, src)
}
func (m *WlstTerminal) XXX_Size() int {
	return xxx_messageInfo_WlstTerminal.Size(m)
}
func (m *WlstTerminal) XXX_DiscardUnknown() {
	xxx_messageInfo_WlstTerminal.DiscardUnknown(m)
}

var xxx_messageInfo_WlstTerminal proto.InternalMessageInfo

func (m *WlstTerminal) GetWlstRtu_1900() *WlstRtu_1900 {
	if m != nil {
		return m.WlstRtu_1900
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtu_4000() *WlstRtu_4000 {
	if m != nil {
		return m.WlstRtu_4000
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtu_4101() *WlstRtu_4101 {
	if m != nil {
		return m.WlstRtu_4101
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtu_4104() *WlstRtu_4104 {
	if m != nil {
		return m.WlstRtu_4104
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtu_4110() *WlstRtu_4110 {
	if m != nil {
		return m.WlstRtu_4110
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtu_4201() *WlstRtu_4200 {
	if m != nil {
		return m.WlstRtu_4201
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtu_4204() *WlstRtu_4200 {
	if m != nil {
		return m.WlstRtu_4204
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtu_4210() *WlstRtu_4200 {
	if m != nil {
		return m.WlstRtu_4210
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtu_4401() *WlstRtu_4401 {
	if m != nil {
		return m.WlstRtu_4401
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtuDa00() *WlstRtuDa00 {
	if m != nil {
		return m.WlstRtuDa00
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtu_6100() *WlstRtu_6100 {
	if m != nil {
		return m.WlstRtu_6100
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtuA000() *WlstRtuA000 {
	if m != nil {
		return m.WlstRtuA000
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtu_4B00() *WlstRtu_4B00 {
	if m != nil {
		return m.WlstRtu_4B00
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtu_9300() *WlstRtu_9300 {
	if m != nil {
		return m.WlstRtu_9300
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtu_1200() *WlstRtu_9300 {
	if m != nil {
		return m.WlstRtu_1200
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtuB200() *WlstRtuB200 {
	if m != nil {
		return m.WlstRtuB200
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtu_3100() *WlstRtuB200 {
	if m != nil {
		return m.WlstRtu_3100
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtu_5800() *WlstRtuB200 {
	if m != nil {
		return m.WlstRtu_5800
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtuD900() *WlstRtuB200 {
	if m != nil {
		return m.WlstRtuD900
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtuE900() *WlstRtuB200 {
	if m != nil {
		return m.WlstRtuE900
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtu_6800() *WlstRtuB200 {
	if m != nil {
		return m.WlstRtu_6800
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtuE600() *WlstRtuE600 {
	if m != nil {
		return m.WlstRtuE600
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtu_4600() *WlstRtuE600 {
	if m != nil {
		return m.WlstRtu_4600
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtuC700() *WlstRtuE600 {
	if m != nil {
		return m.WlstRtuC700
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtu_6500() *WlstRtuE600 {
	if m != nil {
		return m.WlstRtu_6500
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtu_9800() *WlstRtu_9800 {
	if m != nil {
		return m.WlstRtu_9800
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtuCc00() *WlstRtu_9800 {
	if m != nil {
		return m.WlstRtuCc00
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtu_4C00() *WlstRtu_9800 {
	if m != nil {
		return m.WlstRtu_4C00
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtuDc00() *WlstRtuDc00 {
	if m != nil {
		return m.WlstRtuDc00
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtuAb00() *WlstRtuDc00 {
	if m != nil {
		return m.WlstRtuAb00
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtu_7B00() *WlstRtu_7B00 {
	if m != nil {
		return m.WlstRtu_7B00
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtu_2210() *WlstRtuA200 {
	if m != nil {
		return m.WlstRtu_2210
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtuA200() *WlstRtuA200 {
	if m != nil {
		return m.WlstRtuA200
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtu_7060() *WlstRtu_7060 {
	if m != nil {
		return m.WlstRtu_7060
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtu_70E0() *WlstRtu_70E0 {
	if m != nil {
		return m.WlstRtu_70E0
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtu_7061() *WlstRtu_7061 {
	if m != nil {
		return m.WlstRtu_7061
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtu_70E1() *WlstRtu_7060 {
	if m != nil {
		return m.WlstRtu_70E1
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtu_7006() *WlstRtu_7006 {
	if m != nil {
		return m.WlstRtu_7006
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtu_7007() *WlstRtu_7007 {
	if m != nil {
		return m.WlstRtu_7007
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtu_7008() *WlstRtu_7008 {
	if m != nil {
		return m.WlstRtu_7008
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtuCupd() *WlstRtu_7008 {
	if m != nil {
		return m.WlstRtuCupd
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtu_7003() *WlstRtu_7003 {
	if m != nil {
		return m.WlstRtu_7003
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtu_7087() *WlstRtu_7087 {
	if m != nil {
		return m.WlstRtu_7087
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtu_7083() *WlstRtu_7087 {
	if m != nil {
		return m.WlstRtu_7083
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtu_700A() *WlstRtu_700A {
	if m != nil {
		return m.WlstRtu_700A
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtu_7010() *WlstRtu_7010 {
	if m != nil {
		return m.WlstRtu_7010
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtu_7090() *WlstRtu_7010 {
	if m != nil {
		return m.WlstRtu_7090
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtuDf00() *WlstRtuDf00 {
	if m != nil {
		return m.WlstRtuDf00
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtu_70D0() *WlstRtu_70D0 {
	if m != nil {
		return m.WlstRtu_70D0
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtu_70Da() *WlstRtu_70Da {
	if m != nil {
		return m.WlstRtu_70Da
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtuCb00() *WlstRtuAns {
	if m != nil {
		return m.WlstRtuCb00
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtu_9200() *WlstRtuAns {
	if m != nil {
		return m.WlstRtu_9200
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtuC400() *WlstRtuAns {
	if m != nil {
		return m.WlstRtuC400
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtu_7800() *WlstRtu_7800 {
	if m != nil {
		return m.WlstRtu_7800
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtuF800() *WlstRtu_7800 {
	if m != nil {
		return m.WlstRtuF800
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtu_7053() *WlstRtu_7053 {
	if m != nil {
		return m.WlstRtu_7053
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtu_70D3() *WlstRtu_70D3 {
	if m != nil {
		return m.WlstRtu_70D3
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtu_7081() *WlstRtu_7081 {
	if m != nil {
		return m.WlstRtu_7081
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtu_7086() *WlstRtu_7081 {
	if m != nil {
		return m.WlstRtu_7086
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtu_7085() *WlstRtu_7081 {
	if m != nil {
		return m.WlstRtu_7085
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtu_7020() *WlstRtu_70A0 {
	if m != nil {
		return m.WlstRtu_7020
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtu_70A0() *WlstRtu_70A0 {
	if m != nil {
		return m.WlstRtu_70A0
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtu_4111() *WlstRtu_4111 {
	if m != nil {
		return m.WlstRtu_4111
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtuC111() *WlstRtu_4111 {
	if m != nil {
		return m.WlstRtuC111
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtu_705A() *WlstRtu_705A {
	if m != nil {
		return m.WlstRtu_705A
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtuCxxx() *WlstRtu_4111 {
	if m != nil {
		return m.WlstRtuCxxx
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtu_705B() *WlstRtu_705B {
	if m != nil {
		return m.WlstRtu_705B
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtu_70Db() *WlstRtu_705B {
	if m != nil {
		return m.WlstRtu_70Db
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtu_7094() *WlstRtu_7094 {
	if m != nil {
		return m.WlstRtu_7094
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtu_7021() *WlstRtu_7021 {
	if m != nil {
		return m.WlstRtu_7021
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtu_70A1() *WlstRtu_7021 {
	if m != nil {
		return m.WlstRtu_70A1
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtu_7022() *WlstRtu_7021 {
	if m != nil {
		return m.WlstRtu_7022
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtu_70A2() *WlstRtu_7021 {
	if m != nil {
		return m.WlstRtu_70A2
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtu_7023() *WlstRtu_7023 {
	if m != nil {
		return m.WlstRtu_7023
	}
	return nil
}

func (m *WlstTerminal) GetWlstRtu_70A3() *WlstRtu_7023 {
	if m != nil {
		return m.WlstRtu_70A3
	}
	return nil
}

func (m *WlstTerminal) GetWlstLduDc00() *WlstRtuDc00 {
	if m != nil {
		return m.WlstLduDc00
	}
	return nil
}

func (m *WlstTerminal) GetWlstLdu_2600() *WlstLdu_2600 {
	if m != nil {
		return m.WlstLdu_2600
	}
	return nil
}

func (m *WlstTerminal) GetWlstLdu_5B00() *WlstLdu_2600 {
	if m != nil {
		return m.WlstLdu_5B00
	}
	return nil
}

func (m *WlstTerminal) GetWlstLduC900() *WlstLdu_2600 {
	if m != nil {
		return m.WlstLduC900
	}
	return nil
}

func (m *WlstTerminal) GetWlstLdu_4A01() *WlstLdu_2600 {
	if m != nil {
		return m.WlstLdu_4A01
	}
	return nil
}

func (m *WlstTerminal) GetWlstLduCa01() *WlstLdu_2600 {
	if m != nil {
		return m.WlstLduCa01
	}
	return nil
}

func (m *WlstTerminal) GetWlstLdu_4D01() *WlstLdu_2600 {
	if m != nil {
		return m.WlstLdu_4D01
	}
	return nil
}

func (m *WlstTerminal) GetWlstLdu_4D02() *WlstLdu_2600 {
	if m != nil {
		return m.WlstLdu_4D02
	}
	return nil
}

func (m *WlstTerminal) GetWlstLdu_4D03() *WlstLdu_2600 {
	if m != nil {
		return m.WlstLdu_4D03
	}
	return nil
}

func (m *WlstTerminal) GetWlstLduCd02() *WlstLdu_2600 {
	if m != nil {
		return m.WlstLduCd02
	}
	return nil
}

func (m *WlstTerminal) GetWlstLduCd03() *WlstLdu_2600 {
	if m != nil {
		return m.WlstLduCd03
	}
	return nil
}

func (m *WlstTerminal) GetWlstLduA600() *WlstLduA600 {
	if m != nil {
		return m.WlstLduA600
	}
	return nil
}

func (m *WlstTerminal) GetWlstLdu_4900() *WlstLdu_4900 {
	if m != nil {
		return m.WlstLdu_4900
	}
	return nil
}

func (m *WlstTerminal) GetWlstLduDb00() *WlstLdu_4900 {
	if m != nil {
		return m.WlstLduDb00
	}
	return nil
}

func (m *WlstTerminal) GetWlstLduCd01() *WlstLduCd01 {
	if m != nil {
		return m.WlstLduCd01
	}
	return nil
}

func (m *WlstTerminal) GetWlstEsu_9B00() *WlstRtuDc00 {
	if m != nil {
		return m.WlstEsu_9B00
	}
	return nil
}

func (m *WlstTerminal) GetWlstEsu_9200() *WlstEsu_9200 {
	if m != nil {
		return m.WlstEsu_9200
	}
	return nil
}

func (m *WlstTerminal) GetWlstEsu_1100() *WlstEsu_9200 {
	if m != nil {
		return m.WlstEsu_1100
	}
	return nil
}

func (m *WlstTerminal) GetWlstEsu_9E00() *WlstEsu_9E00 {
	if m != nil {
		return m.WlstEsu_9E00
	}
	return nil
}

func (m *WlstTerminal) GetWlstEsu_1D00() *WlstEsu_9E00 {
	if m != nil {
		return m.WlstEsu_1D00
	}
	return nil
}

func (m *WlstTerminal) GetWlstEsu_9A00() *WlstEsu_9A00 {
	if m != nil {
		return m.WlstEsu_9A00
	}
	return nil
}

func (m *WlstTerminal) GetWlstEsu_1900() *WlstEsu_1900 {
	if m != nil {
		return m.WlstEsu_1900
	}
	return nil
}

func (m *WlstTerminal) GetWlstEsu_2500() *WlstEsu_1900 {
	if m != nil {
		return m.WlstEsu_2500
	}
	return nil
}

func (m *WlstTerminal) GetWlstEsu_1800() *WlstEsu_1800 {
	if m != nil {
		return m.WlstEsu_1800
	}
	return nil
}

func (m *WlstTerminal) GetWlstEsu_9700() *WlstEsu_9700 {
	if m != nil {
		return m.WlstEsu_9700
	}
	return nil
}

func (m *WlstTerminal) GetWlstEsu_1700() *WlstEsu_9700 {
	if m != nil {
		return m.WlstEsu_1700
	}
	return nil
}

func (m *WlstTerminal) GetWlstEsu_1A00() *WlstEsu_9700 {
	if m != nil {
		return m.WlstEsu_1A00
	}
	return nil
}

func (m *WlstTerminal) GetWlstEsu_9500() *WlstEsu_9500 {
	if m != nil {
		return m.WlstEsu_9500
	}
	return nil
}

func (m *WlstTerminal) GetWlstEsu_1400() *WlstEsu_9500 {
	if m != nil {
		return m.WlstEsu_1400
	}
	return nil
}

func (m *WlstTerminal) GetWlstEsu_9F00() *WlstEsu_9F00 {
	if m != nil {
		return m.WlstEsu_9F00
	}
	return nil
}

func (m *WlstTerminal) GetWlstEsu_9300() *WlstEsu_9F00 {
	if m != nil {
		return m.WlstEsu_9300
	}
	return nil
}

func (m *WlstTerminal) GetWlstEsu_9400() *WlstEsu_9400 {
	if m != nil {
		return m.WlstEsu_9400
	}
	return nil
}

func (m *WlstTerminal) GetWlstEsu_9000() *WlstEsu_9000 {
	if m != nil {
		return m.WlstEsu_9000
	}
	return nil
}

func (m *WlstTerminal) GetWlstEsu_9100() *WlstEsu_9000 {
	if m != nil {
		return m.WlstEsu_9100
	}
	return nil
}

func (m *WlstTerminal) GetWlstEsu_9900() *WlstEsu_9000 {
	if m != nil {
		return m.WlstEsu_9900
	}
	return nil
}

func (m *WlstTerminal) GetWlstEsu_9D00() *WlstEsu_9000 {
	if m != nil {
		return m.WlstEsu_9D00
	}
	return nil
}

func (m *WlstTerminal) GetWlstEsuA500() *WlstEsu_9000 {
	if m != nil {
		return m.WlstEsuA500
	}
	return nil
}

func (m *WlstTerminal) GetWlstEsu_1600() *WlstEsu_1600 {
	if m != nil {
		return m.WlstEsu_1600
	}
	return nil
}

func (m *WlstTerminal) GetWlstEsu_9600() *WlstEsu_9000 {
	if m != nil {
		return m.WlstEsu_9600
	}
	return nil
}

func (m *WlstTerminal) GetWlstEsu_9800() *WlstEsu_9000 {
	if m != nil {
		return m.WlstEsu_9800
	}
	return nil
}

func (m *WlstTerminal) GetWlstEsuA200() *WlstEsu_9000 {
	if m != nil {
		return m.WlstEsuA200
	}
	return nil
}

func (m *WlstTerminal) GetWlstEsuA300() *WlstEsu_9000 {
	if m != nil {
		return m.WlstEsuA300
	}
	return nil
}

func (m *WlstTerminal) GetWlstGps_0000() *WlstGps_0000 {
	if m != nil {
		return m.WlstGps_0000
	}
	return nil
}

func (m *WlstTerminal) GetWlstGps_5903() *WlstGps_5903 {
	if m != nil {
		return m.WlstGps_5903
	}
	return nil
}

func (m *WlstTerminal) GetWlstGps_5983() *WlstGps_5903 {
	if m != nil {
		return m.WlstGps_5983
	}
	return nil
}

func (m *WlstTerminal) GetWlstGps_5904() *WlstGps_5904 {
	if m != nil {
		return m.WlstGps_5904
	}
	return nil
}

func (m *WlstTerminal) GetWlstGps_5984() *WlstGps_5904 {
	if m != nil {
		return m.WlstGps_5984
	}
	return nil
}

func (m *WlstTerminal) GetWlstAlsA700() *WlstAlsA700 {
	if m != nil {
		return m.WlstAlsA700
	}
	return nil
}

func (m *WlstTerminal) GetWlstAls_2700() *WlstAlsA700 {
	if m != nil {
		return m.WlstAls_2700
	}
	return nil
}

func (m *WlstTerminal) GetWlstAlsB700() *WlstAlsA700 {
	if m != nil {
		return m.WlstAlsB700
	}
	return nil
}

func (m *WlstTerminal) GetWlstAlsA500() *WlstAlsA700 {
	if m != nil {
		return m.WlstAlsA500
	}
	return nil
}

func (m *WlstTerminal) GetWlstAls_2500() *WlstAlsA700 {
	if m != nil {
		return m.WlstAls_2500
	}
	return nil
}

func (m *WlstTerminal) GetWlstAlsB800() *WlstAlsA700 {
	if m != nil {
		return m.WlstAlsB800
	}
	return nil
}

func (m *WlstTerminal) GetWlstAlsB600() *WlstAlsA700 {
	if m != nil {
		return m.WlstAlsB600
	}
	return nil
}

func (m *WlstTerminal) GetWlstAls_3600() *WlstAlsA700 {
	if m != nil {
		return m.WlstAls_3600
	}
	return nil
}

func (m *WlstTerminal) GetWlstAlsC600() *WlstAlsA700 {
	if m != nil {
		return m.WlstAlsC600
	}
	return nil
}

func (m *WlstTerminal) GetWlstAls_3700() *WlstAlsA700 {
	if m != nil {
		return m.WlstAls_3700
	}
	return nil
}

func (m *WlstTerminal) GetWlstAlsA800() *WlstAlsA700 {
	if m != nil {
		return m.WlstAlsA800
	}
	return nil
}

func (m *WlstTerminal) GetWlstAlsC700() *WlstAlsA700 {
	if m != nil {
		return m.WlstAlsC700
	}
	return nil
}

func (m *WlstTerminal) GetWlstAls_4700() *WlstAlsA700 {
	if m != nil {
		return m.WlstAls_4700
	}
	return nil
}

func (m *WlstTerminal) GetWlstAls_3800() *WlstAlsA700 {
	if m != nil {
		return m.WlstAls_3800
	}
	return nil
}

func (m *WlstTerminal) GetWlstAlsC800() *WlstAlsA700 {
	if m != nil {
		return m.WlstAlsC800
	}
	return nil
}

func (m *WlstTerminal) GetWlstAls_4800() *WlstAlsA700 {
	if m != nil {
		return m.WlstAls_4800
	}
	return nil
}

func (m *WlstTerminal) GetWlstAlsCa00() *WlstAlsA700 {
	if m != nil {
		return m.WlstAlsCa00
	}
	return nil
}

func (m *WlstTerminal) GetWlstAls_4A00() *WlstAlsA700 {
	if m != nil {
		return m.WlstAls_4A00
	}
	return nil
}

func (m *WlstTerminal) GetWlstAlsA600() *WlstAlsA700 {
	if m != nil {
		return m.WlstAlsA600
	}
	return nil
}

func (m *WlstTerminal) GetWlstMru_9100() *WlstMru_9100 {
	if m != nil {
		return m.WlstMru_9100
	}
	return nil
}

func (m *WlstTerminal) GetWlstMru_1100() *WlstMru_9100 {
	if m != nil {
		return m.WlstMru_1100
	}
	return nil
}

func (m *WlstTerminal) GetWlstMru_9300() *WlstMru_9100 {
	if m != nil {
		return m.WlstMru_9300
	}
	return nil
}

func (m *WlstTerminal) GetWlstMru_1300() *WlstMru_9100 {
	if m != nil {
		return m.WlstMru_1300
	}
	return nil
}

func (m *WlstTerminal) GetWlstElu_6257() *WlstElu_6257 {
	if m != nil {
		return m.WlstElu_6257
	}
	return nil
}

func (m *WlstTerminal) GetWlstElu_62D7() *WlstElu_6257 {
	if m != nil {
		return m.WlstElu_62D7
	}
	return nil
}

func (m *WlstTerminal) GetWlstElu_62D8() *WlstElu_62D8 {
	if m != nil {
		return m.WlstElu_62D8
	}
	return nil
}

func (m *WlstTerminal) GetWlstElu_625A() *WlstElu_625A {
	if m != nil {
		return m.WlstElu_625A
	}
	return nil
}

func (m *WlstTerminal) GetWlstElu_62Da() *WlstElu_625A {
	if m != nil {
		return m.WlstElu_62Da
	}
	return nil
}

func (m *WlstTerminal) GetWlstElu_625B() *WlstElu_625B {
	if m != nil {
		return m.WlstElu_625B
	}
	return nil
}

func (m *WlstTerminal) GetWlstElu_62Db() *WlstElu_625B {
	if m != nil {
		return m.WlstElu_62Db
	}
	return nil
}

func (m *WlstTerminal) GetWlstElu_625C() *WlstElu_625C {
	if m != nil {
		return m.WlstElu_625C
	}
	return nil
}

func (m *WlstTerminal) GetWlstElu_62Dc() *WlstElu_625C {
	if m != nil {
		return m.WlstElu_62Dc
	}
	return nil
}

func (m *WlstTerminal) GetWlstElu_62Dd() *WlstElu_6256 {
	if m != nil {
		return m.WlstElu_62Dd
	}
	return nil
}

func (m *WlstTerminal) GetWlstElu_62De() *WlstElu_625C {
	if m != nil {
		return m.WlstElu_62De
	}
	return nil
}

func (m *WlstTerminal) GetWlstElu_62Df() *WlstElu_6255 {
	if m != nil {
		return m.WlstElu_62Df
	}
	return nil
}

func (m *WlstTerminal) GetWlstElu_6255() *WlstElu_6255 {
	if m != nil {
		return m.WlstElu_6255
	}
	return nil
}

func (m *WlstTerminal) GetWlstElu_62D5() *WlstElu_6255 {
	if m != nil {
		return m.WlstElu_62D5
	}
	return nil
}

func (m *WlstTerminal) GetWlstElu_6256() *WlstElu_6256 {
	if m != nil {
		return m.WlstElu_6256
	}
	return nil
}

func (m *WlstTerminal) GetWlstElu_62D6() *WlstElu_6256 {
	if m != nil {
		return m.WlstElu_62D6
	}
	return nil
}

func (m *WlstTerminal) GetWlstSlu_1900() *WlstSlu_2400 {
	if m != nil {
		return m.WlstSlu_1900
	}
	return nil
}

func (m *WlstTerminal) GetWlstSlu_9900() *WlstSlu_2400 {
	if m != nil {
		return m.WlstSlu_9900
	}
	return nil
}

func (m *WlstTerminal) GetWlstSluD000() *WlstSluD000 {
	if m != nil {
		return m.WlstSluD000
	}
	return nil
}

func (m *WlstTerminal) GetWlstSlu_2400() *WlstSlu_2400 {
	if m != nil {
		return m.WlstSlu_2400
	}
	return nil
}

func (m *WlstTerminal) GetWlstSluA400() *WlstSluF400 {
	if m != nil {
		return m.WlstSluA400
	}
	return nil
}

func (m *WlstTerminal) GetWlstSlu_2800() *WlstSlu_2800 {
	if m != nil {
		return m.WlstSlu_2800
	}
	return nil
}

func (m *WlstTerminal) GetWlstSluA800() *WlstSluF400 {
	if m != nil {
		return m.WlstSluA800
	}
	return nil
}

func (m *WlstTerminal) GetWlstSlu_3000() *WlstSlu_3000 {
	if m != nil {
		return m.WlstSlu_3000
	}
	return nil
}

func (m *WlstTerminal) GetWlstSluB000() *WlstSluF400 {
	if m != nil {
		return m.WlstSluB000
	}
	return nil
}

func (m *WlstTerminal) GetWlstSluB200() *WlstSlu_3000 {
	if m != nil {
		return m.WlstSluB200
	}
	return nil
}

func (m *WlstTerminal) GetWlstSlu_9A00() *WlstSlu_9A00 {
	if m != nil {
		return m.WlstSlu_9A00
	}
	return nil
}

func (m *WlstTerminal) GetWlstSluCd00() *WlstSluCd00 {
	if m != nil {
		return m.WlstSluCd00
	}
	return nil
}

func (m *WlstTerminal) GetWlstSlu_1C00() *WlstSlu_1C00 {
	if m != nil {
		return m.WlstSlu_1C00
	}
	return nil
}

func (m *WlstTerminal) GetWlstSlu_9C00() *WlstSluF400 {
	if m != nil {
		return m.WlstSlu_9C00
	}
	return nil
}

func (m *WlstTerminal) GetWlstSlu_1D00() *WlstSlu_1D00 {
	if m != nil {
		return m.WlstSlu_1D00
	}
	return nil
}

func (m *WlstTerminal) GetWlstSlu_9D00() *WlstSlu_9D00 {
	if m != nil {
		return m.WlstSlu_9D00
	}
	return nil
}

func (m *WlstTerminal) GetWlstSlu_7000() *WlstSluF000 {
	if m != nil {
		return m.WlstSlu_7000
	}
	return nil
}

func (m *WlstTerminal) GetWlstSluF000() *WlstSluF000 {
	if m != nil {
		return m.WlstSluF000
	}
	return nil
}

func (m *WlstTerminal) GetWlstSlu_7100() *WlstSluF100 {
	if m != nil {
		return m.WlstSlu_7100
	}
	return nil
}

func (m *WlstTerminal) GetWlstSluF100() *WlstSluF100 {
	if m != nil {
		return m.WlstSluF100
	}
	return nil
}

func (m *WlstTerminal) GetWlstSlu_7200() *WlstSluF200 {
	if m != nil {
		return m.WlstSlu_7200
	}
	return nil
}

func (m *WlstTerminal) GetWlstSluF200() *WlstSluF200 {
	if m != nil {
		return m.WlstSluF200
	}
	return nil
}

func (m *WlstTerminal) GetWlstSlu_7300() *WlstSlu_7300 {
	if m != nil {
		return m.WlstSlu_7300
	}
	return nil
}

func (m *WlstTerminal) GetWlstSluF300() *WlstSlu_7300 {
	if m != nil {
		return m.WlstSluF300
	}
	return nil
}

func (m *WlstTerminal) GetWlstSlu_7400() *WlstSlu_7400 {
	if m != nil {
		return m.WlstSlu_7400
	}
	return nil
}

func (m *WlstTerminal) GetWlstSluF400() *WlstSluF400 {
	if m != nil {
		return m.WlstSluF400
	}
	return nil
}

func (m *WlstTerminal) GetWlstSlu_7600() *WlstSluCd00 {
	if m != nil {
		return m.WlstSlu_7600
	}
	return nil
}

func (m *WlstTerminal) GetWlstSluF600() *WlstSluF400 {
	if m != nil {
		return m.WlstSluF600
	}
	return nil
}

func (m *WlstTerminal) GetWlstSluF900() *WlstSluF900 {
	if m != nil {
		return m.WlstSluF900
	}
	return nil
}

func (m *WlstTerminal) GetWlstSlu_7A00() *WlstSlu_1D00 {
	if m != nil {
		return m.WlstSlu_7A00
	}
	return nil
}

func (m *WlstTerminal) GetWlstSluFa00() *WlstSlu_9D00 {
	if m != nil {
		return m.WlstSluFa00
	}
	return nil
}

func (m *WlstTerminal) GetWlstSlu_7B00() *WlstSlu_7B00 {
	if m != nil {
		return m.WlstSlu_7B00
	}
	return nil
}

func (m *WlstTerminal) GetWlstSluFb00() *WlstSlu_7B00 {
	if m != nil {
		return m.WlstSluFb00
	}
	return nil
}

func (m *WlstTerminal) GetWlstSluFe00() *WlstSluFe00 {
	if m != nil {
		return m.WlstSluFe00
	}
	return nil
}

func (m *WlstTerminal) GetWlstSlu_7C00() *WlstSlu_7C00 {
	if m != nil {
		return m.WlstSlu_7C00
	}
	return nil
}

func (m *WlstTerminal) GetWlstSluFc00() *WlstSluF400 {
	if m != nil {
		return m.WlstSluFc00
	}
	return nil
}

func (m *WlstTerminal) GetWlstSlu_6F00() *WlstSlu_6F00 {
	if m != nil {
		return m.WlstSlu_6F00
	}
	return nil
}

func (m *WlstTerminal) GetWlstSluEf00() *WlstSlu_6F00 {
	if m != nil {
		return m.WlstSluEf00
	}
	return nil
}

func (m *WlstTerminal) GetWlstSlu_6E00() *WlstSlu_6E00 {
	if m != nil {
		return m.WlstSlu_6E00
	}
	return nil
}

func (m *WlstTerminal) GetWlstSluEe00() *WlstSlu_6E00 {
	if m != nil {
		return m.WlstSluEe00
	}
	return nil
}

func (m *WlstTerminal) GetWlstSlu_6B00() *WlstSlu_6B00 {
	if m != nil {
		return m.WlstSlu_6B00
	}
	return nil
}

func (m *WlstTerminal) GetWlstSluEb00() *WlstSluF400 {
	if m != nil {
		return m.WlstSluEb00
	}
	return nil
}

func (m *WlstTerminal) GetWlstSlu_6C00() *WlstSlu_6C00 {
	if m != nil {
		return m.WlstSlu_6C00
	}
	return nil
}

func (m *WlstTerminal) GetWlstSluEc00() *WlstSluEc00 {
	if m != nil {
		return m.WlstSluEc00
	}
	return nil
}

func (m *WlstTerminal) GetWlstSlu_7800() *WlstSlu_7800 {
	if m != nil {
		return m.WlstSlu_7800
	}
	return nil
}

func (m *WlstTerminal) GetWlstSluF800() *WlstSluF800 {
	if m != nil {
		return m.WlstSluF800
	}
	return nil
}

func (m *WlstTerminal) GetWlstSluB900() *WlstSlu_3900 {
	if m != nil {
		return m.WlstSluB900
	}
	return nil
}

func init() {
	proto.RegisterType((*WlstTerminal)(nil), "wlst.pb2.WlstTerminal")
}

func init() { proto.RegisterFile("protocol_tml.proto", fileDescriptor_0e80f3177279cb0c) }

var fileDescriptor_0e80f3177279cb0c = []byte{
	// 2155 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0xdb, 0x55, 0x8c, 0x24, 0xd7,
	0xd5, 0x07, 0x70, 0xed, 0xf7, 0xc5, 0x56, 0xb4, 0x6b, 0x07, 0x26, 0x89, 0x7d, 0xe2, 0x90, 0xe3,
	0x90, 0x43, 0x9b, 0x73, 0x8b, 0xcb, 0x76, 0x60, 0xa8, 0xed, 0x24, 0x76, 0x60, 0x6d, 0xc9, 0x8f,
	0xa3, 0x5b, 0xd0, 0x51, 0xa4, 0x5e, 0xef, 0x68, 0x7a, 0x46, 0x99, 0xc7, 0x30, 0xbc, 0x85, 0x19,
	0xd6, 0x76, 0x18, 0xcc, 0x10, 0x66, 0x70, 0x98, 0x23, 0x85, 0x99, 0x39, 0x52, 0x18, 0x75, 0x7a,
	0xa0, 0x4f, 0xfd, 0x6b, 0xea, 0xea, 0x3c, 0xf6, 0xdc, 0xfe, 0xf9, 0x7f, 0xeb, 0xde, 0x73, 0x4f,
	0x55, 0x8d, 0x67, 0x0f, 0x2f, 0xac, 0x6f, 0x9c, 0xd8, 0x3c, 0x51, 0x9f, 0x98, 0xac, 0x6d, 0x1e,
	0x9f, 0x1c, 0x9d, 0x7d, 0x58, 0xb8, 0xfd, 0xd3, 0x26, 0xd3, 0xcd, 0xa3, 0xeb, 0x55, 0x74, 0xd6,
	0x7c, 0x74, 0x63, 0x73, 0x6b, 0x67, 0x54, 0xfd, 0x6c, 0xd2, 0xf4, 0x7f, 0xe6, 0x27, 0xd3, 0xde,
	0xcf, 0xda, 0x69, 0xff, 0x7b, 0xd3, 0xc9, 0xee, 0xcf, 0xce, 0x39, 0xd9, 0x1c, 0x3e, 0xed, 0xf2,
	0xc9, 0x74, 0xf3, 0xb2, 0x76, 0xe3, 0xf8, 0x53, 0xaf, 0xf0, 0x93, 0x85, 0xf3, 0x0f, 0x9f, 0x2e,
	0x13, 0x90, 0xc8, 0x35, 0x57, 0x32, 0xd3, 0xe1, 0xb3, 0x0f, 0x9d, 0x7b, 0x24, 0x3a, 0xf3, 0xe8,
	0xde, 0xb4, 0x8e, 0x5e, 0xae, 0x87, 0x8f, 0x1d, 0x91, 0x9f, 0x1f, 0xdb, 0xdc, 0x92, 0x0f, 0x1d,
	0x9c, 0x30, 0x33, 0x1d, 0x19, 0xc4, 0x32, 0xbc, 0x8f, 0xe5, 0x43, 0x17, 0x3b, 0x76, 0x74, 0xda,
	0x30, 0x76, 0xec, 0xe6, 0xd8, 0xb1, 0x43, 0x9c, 0xd0, 0xe9, 0x21, 0x9c, 0x68, 0x9c, 0x00, 0x76,
	0x4c, 0x77, 0x08, 0x60, 0xa7, 0xa6, 0xed, 0x1c, 0x4c, 0x3b, 0x62, 0x47, 0x77, 0x1c, 0xc6, 0x91,
	0xbe, 0xe6, 0x08, 0xa7, 0x1d, 0x71, 0x42, 0x77, 0x32, 0x63, 0x98, 0x76, 0xe4, 0x98, 0xee, 0x6c,
	0xc5, 0x38, 0xed, 0x84, 0x1d, 0x2d, 0x0c, 0xe3, 0x44, 0xaf, 0x76, 0x02, 0xd3, 0x6e, 0x3c, 0x33,
	0xdd, 0x65, 0x10, 0xcb, 0xf0, 0x3e, 0x5e, 0xf1, 0xb0, 0xcf, 0x99, 0x63, 0xa6, 0xbb, 0x0e, 0x62,
	0x19, 0xde, 0xc7, 0xf2, 0xa1, 0x83, 0xbd, 0x54, 0xd8, 0xdd, 0x06, 0xb1, 0xd7, 0x15, 0xb6, 0xd8,
	0xab, 0xb0, 0x8a, 0x99, 0xce, 0x18, 0xbe, 0xe6, 0x4a, 0x2f, 0x58, 0x05, 0xb8, 0x8c, 0x99, 0xe9,
	0xcc, 0x41, 0x2c, 0xc3, 0xfb, 0x58, 0x3e, 0x74, 0x4f, 0x55, 0xc4, 0x4c, 0x64, 0xc3, 0xf2, 0xdd,
	0x0e, 0xae, 0x04, 0xdf, 0x7d, 0x10, 0x57, 0x7a, 0x9f, 0x97, 0x10, 0xc7, 0xb2, 0xda, 0x67, 0xd9,
	0x70, 0x8c, 0xab, 0x9d, 0x16, 0xcc, 0x74, 0x0f, 0x1b, 0x96, 0xef, 0x76, 0x8b, 0x44, 0x3a, 0xc9,
	0x3d, 0x6d, 0x78, 0x05, 0x3b, 0x49, 0x2b, 0xf8, 0x5e, 0x36, 0xbc, 0x8a, 0x38, 0x93, 0x69, 0xdf,
	0xdb, 0x86, 0x33, 0x9c, 0x76, 0x9b, 0x31, 0xd3, 0x7d, 0x06, 0xb1, 0x0c, 0xcf, 0x93, 0x33, 0xac,
	0x30, 0xc1, 0x67, 0xdb, 0x70, 0x82, 0xb8, 0xce, 0x99, 0xe9, 0xbe, 0x36, 0xbc, 0x9c, 0xe3, 0x35,
	0xa7, 0xcc, 0x74, 0x8e, 0x0d, 0xcb, 0x77, 0xbb, 0xb5, 0x2d, 0x0b, 0x76, 0xbf, 0xe1, 0xf2, 0x2c,
	0x74, 0x6d, 0xe3, 0x82, 0xd5, 0x35, 0x33, 0xdd, 0xdf, 0x86, 0x97, 0x6b, 0x5c, 0x30, 0xc1, 0x0f,
	0xb0, 0xe1, 0x04, 0x71, 0x23, 0xf8, 0x81, 0xc3, 0x6d, 0xa8, 0xd6, 0x15, 0x86, 0xd8, 0x4b, 0x33,
	0x78, 0x90, 0x0d, 0x2f, 0x62, 0x33, 0xc8, 0x05, 0x9f, 0x3b, 0x88, 0x73, 0xdd, 0x49, 0x72, 0xc4,
	0x91, 0xf4, 0xed, 0x07, 0x0f, 0xf7, 0x30, 0x5d, 0x9e, 0x11, 0xf6, 0x6d, 0x19, 0xa5, 0x87, 0xd8,
	0xf0, 0x22, 0x36, 0x83, 0x9c, 0x33, 0xa6, 0x87, 0x0e, 0x4f, 0x9b, 0x33, 0x35, 0x6d, 0xce, 0x10,
	0xb7, 0x4c, 0x0f, 0x0b, 0xe0, 0x56, 0xe3, 0xb6, 0x97, 0xec, 0xe8, 0xe1, 0xa1, 0x64, 0xa7, 0x93,
	0x1d, 0x26, 0x3b, 0x3a, 0x6a, 0x9d, 0x76, 0x8b, 0x98, 0x33, 0x7a, 0x44, 0x00, 0x73, 0xa6, 0x30,
	0x67, 0x88, 0x73, 0xe2, 0x10, 0xce, 0x35, 0xce, 0x11, 0x17, 0xe4, 0x42, 0xb8, 0xd0, 0xb8, 0xe8,
	0x9e, 0xaa, 0xad, 0xf5, 0x86, 0x22, 0x1b, 0x5e, 0xde, 0x5a, 0x6f, 0x30, 0x39, 0xa6, 0x38, 0x84,
	0x63, 0x9d, 0x1c, 0x03, 0x2e, 0x72, 0x4a, 0x02, 0xb8, 0xd0, 0xd7, 0x5c, 0xe0, 0x35, 0x17, 0x31,
	0xa5, 0x66, 0x8c, 0xc9, 0xec, 0x29, 0x0b, 0x4d, 0xdb, 0xeb, 0x69, 0x7b, 0xc0, 0x8e, 0x29, 0x0f,
	0x60, 0xa7, 0x8b, 0xc4, 0x61, 0x79, 0x96, 0x4c, 0x85, 0x15, 0x97, 0xd0, 0x86, 0xc6, 0xcc, 0x54,
	0x0e, 0x77, 0x92, 0xb1, 0x6e, 0x43, 0xe3, 0xde, 0x91, 0x6c, 0x98, 0xce, 0x0b, 0x24, 0x37, 0x3a,
	0xb9, 0xe9, 0x61, 0x4f, 0xe7, 0x87, 0xb0, 0x5e, 0xb0, 0xc6, 0x2f, 0x9c, 0xa7, 0x2b, 0x4c, 0x7a,
	0xd8, 0x05, 0x33, 0x7c, 0xc6, 0x41, 0x9d, 0xe4, 0x8a, 0xe9, 0xbc, 0xc0, 0xa4, 0x85, 0x69, 0x5b,
	0x4a, 0x17, 0x7a, 0xa4, 0xc9, 0xca, 0x57, 0xbb, 0xb9, 0x09, 0x33, 0x3d, 0xca, 0x96, 0x9b, 0xe0,
	0x6a, 0xc9, 0x8d, 0xea, 0xd1, 0xc3, 0x17, 0xac, 0x6f, 0x17, 0x39, 0xde, 0xa8, 0xc6, 0x82, 0x1f,
	0x63, 0xc3, 0xa3, 0xa2, 0xb7, 0x4f, 0x69, 0x4c, 0x8b, 0x81, 0xa5, 0x4e, 0xf5, 0x91, 0x4a, 0xb1,
	0xb0, 0x9b, 0x98, 0x96, 0x42, 0xfb, 0xa4, 0x71, 0xd3, 0x3b, 0x8f, 0x8e, 0x96, 0x43, 0x47, 0x4a,
	0xb7, 0xce, 0x02, 0xbb, 0x5f, 0x91, 0xd1, 0x8a, 0x19, 0x63, 0xf7, 0x2b, 0x52, 0x5a, 0x35, 0xe3,
	0x14, 0x70, 0xc4, 0x34, 0x0a, 0x60, 0xaf, 0x0b, 0x3b, 0xc2, 0xd5, 0xf6, 0x4c, 0x17, 0x5a, 0xb1,
	0xc7, 0x17, 0x49, 0xe7, 0xe8, 0xa2, 0xd0, 0xeb, 0x9c, 0x7e, 0x91, 0x74, 0xdd, 0x05, 0xab, 0x05,
	0x3f, 0xd6, 0x86, 0x97, 0x11, 0xe7, 0x9c, 0x7a, 0x7a, 0x5c, 0xa8, 0x48, 0xf4, 0x79, 0x4c, 0xbb,
	0x0d, 0xac, 0xde, 0xde, 0xde, 0xa6, 0xc7, 0x1b, 0x93, 0xb7, 0xb7, 0xb7, 0x31, 0xb9, 0xa2, 0x8b,
	0x43, 0xc9, 0x95, 0x4e, 0xae, 0xb0, 0x3c, 0x2b, 0xba, 0xc4, 0x8a, 0x1b, 0xc4, 0x65, 0x42, 0x4f,
	0x08, 0xe0, 0x32, 0xd1, 0xad, 0x33, 0xc1, 0x22, 0x71, 0xf4, 0xc4, 0x00, 0x8e, 0x74, 0x85, 0x45,
	0xb8, 0xda, 0xde, 0xd1, 0x93, 0xac, 0xd8, 0x23, 0x8e, 0x22, 0x7a, 0xb2, 0x39, 0x39, 0xc2, 0xe4,
	0x88, 0x8e, 0x99, 0x93, 0x11, 0x47, 0x31, 0x5d, 0x1a, 0xc2, 0xba, 0x19, 0x44, 0xd8, 0x0c, 0x7c,
	0x4c, 0x97, 0x59, 0xb1, 0x8f, 0x17, 0x2e, 0xd8, 0xc5, 0x93, 0x66, 0xf7, 0x79, 0xf9, 0xb6, 0x43,
	0x86, 0x67, 0xde, 0x8b, 0x9b, 0x9d, 0x07, 0x66, 0xad, 0x23, 0x79, 0xb7, 0xf9, 0xf4, 0xc1, 0x7a,
	0x6f, 0x7c, 0x5f, 0xcb, 0x87, 0x8e, 0x4e, 0xe5, 0x6e, 0xf3, 0x19, 0xa3, 0x96, 0x2f, 0x77, 0x74,
	0x2d, 0xaf, 0x83, 0x9f, 0x35, 0xea, 0xe5, 0x12, 0x74, 0xe2, 0xd9, 0xd1, 0xe7, 0x8c, 0x5a, 0xbe,
	0xdc, 0xcd, 0x16, 0xfd, 0x79, 0x6b, 0x36, 0xea, 0xa4, 0x61, 0x47, 0x5f, 0xb0, 0x66, 0x37, 0x7d,
	0x1d, 0xd1, 0x17, 0xed, 0x3a, 0x42, 0x1d, 0xd3, 0x97, 0xec, 0xba, 0x5b, 0x2d, 0xb5, 0x64, 0x7f,
	0xd9, 0x7a, 0xdd, 0x98, 0x5d, 0x4b, 0xf6, 0x57, 0xec, 0xba, 0x9b, 0xed, 0xa5, 0xd6, 0xbe, 0x3a,
	0xac, 0xbd, 0xd6, 0x8b, 0x58, 0x6b, 0x89, 0x54, 0xcb, 0xd7, 0x86, 0x75, 0x52, 0xea, 0xeb, 0xc6,
	0x6a, 0x69, 0xa4, 0x52, 0xbf, 0x6e, 0xd4, 0x2b, 0xbd, 0x4a, 0x95, 0xfd, 0xfe, 0xc6, 0xb0, 0x96,
	0x71, 0x7d, 0xdd, 0xf3, 0xfd, 0x6e, 0xa7, 0x5b, 0x6b, 0xa5, 0x64, 0x9f, 0x3c, 0xd5, 0x70, 0x42,
	0x57, 0xa7, 0x5b, 0xa5, 0xce, 0x9e, 0x69, 0x79, 0x2a, 0xbb, 0xf2, 0x60, 0xbd, 0x37, 0x3e, 0xd7,
	0x11, 0x68, 0xe7, 0x98, 0xe9, 0x2a, 0xa3, 0x96, 0x2f, 0x77, 0xb3, 0x5b, 0x66, 0xba, 0x3a, 0xa0,
	0x5b, 0x9d, 0xdd, 0x62, 0x76, 0xc3, 0x4c, 0x6f, 0x34, 0x6a, 0xf9, 0x72, 0x37, 0xdb, 0x33, 0xd3,
	0x9b, 0x02, 0xda, 0xeb, 0x6c, 0x8f, 0xd9, 0x52, 0x2d, 0x6f, 0x1e, 0xd6, 0xf3, 0x5f, 0x79, 0x4b,
	0x76, 0x09, 0x3a, 0x4a, 0x99, 0xe9, 0x2d, 0x46, 0x2d, 0x5f, 0xee, 0x66, 0xcb, 0x23, 0xe9, 0x5b,
	0x03, 0xba, 0xd0, 0xd9, 0x05, 0x5e, 0x77, 0xce, 0x4c, 0x6f, 0x0b, 0x5c, 0x77, 0xae, 0xaf, 0x3b,
	0xc7, 0x6c, 0xd1, 0x6f, 0x37, 0x6a, 0xd7, 0xd3, 0xb2, 0xe6, 0xef, 0xb0, 0x6a, 0x5c, 0xf3, 0x52,
	0x56, 0xed, 0x9d, 0x01, 0x9d, 0xea, 0x99, 0xf7, 0x56, 0x4d, 0xde, 0x20, 0xde, 0x65, 0xd4, 0xf2,
	0xe5, 0x6e, 0xb6, 0xbc, 0xae, 0x5d, 0x13, 0xd0, 0x63, 0x9d, 0x3d, 0x46, 0x1d, 0x33, 0xd3, 0xb5,
	0x56, 0x1d, 0xa3, 0x96, 0x99, 0x5f, 0x17, 0xd0, 0x89, 0xd6, 0xbd, 0x99, 0x33, 0x33, 0x5d, 0x1f,
	0xd0, 0xac, 0x35, 0xa3, 0x96, 0xf3, 0x7d, 0x83, 0x55, 0xf7, 0xce, 0xb7, 0x9c, 0x92, 0x1b, 0xad,
	0x1a, 0x4f, 0x49, 0x29, 0xe7, 0xfb, 0x26, 0xab, 0xc6, 0xf3, 0xed, 0xa5, 0x5a, 0x6e, 0x36, 0xea,
	0xc5, 0x5e, 0xb5, 0xc8, 0xbd, 0xe4, 0x96, 0xc0, 0x19, 0xcb, 0x74, 0xb5, 0x64, 0x38, 0x73, 0xd1,
	0xb7, 0x5a, 0x67, 0xde, 0xd3, 0x72, 0xbe, 0xdf, 0x63, 0xd5, 0x78, 0xbe, 0x67, 0xbf, 0xeb, 0x7b,
	0xaf, 0xf5, 0xba, 0xb1, 0x9f, 0x7b, 0xa9, 0xd4, 0xf7, 0x59, 0xb5, 0xae, 0xd4, 0xa7, 0xac, 0x4f,
	0xd7, 0x58, 0x6a, 0xed, 0x85, 0xff, 0x7f, 0xa0, 0xde, 0x1b, 0xdf, 0xd1, 0x17, 0xae, 0x4f, 0x99,
	0x41, 0xa7, 0x25, 0xc7, 0x74, 0xc3, 0xb0, 0x96, 0xf1, 0x7d, 0x2d, 0x1f, 0x40, 0x17, 0x31, 0xdd,
	0x68, 0xd6, 0x05, 0x6a, 0x4e, 0xe8, 0xa6, 0xa0, 0x4e, 0x74, 0x76, 0x82, 0xd9, 0x09, 0xdd, 0x6c,
	0xd6, 0xc5, 0x5c, 0xfb, 0xc9, 0x74, 0xcd, 0x4b, 0x4f, 0x7d, 0xd1, 0xc1, 0x7a, 0x6f, 0x7c, 0x47,
	0x2f, 0x4e, 0xa6, 0x8b, 0xba, 0xa7, 0xca, 0x68, 0x24, 0xfa, 0xc5, 0x46, 0x1d, 0xa1, 0xae, 0x44,
	0xbf, 0xc4, 0xa8, 0x97, 0x50, 0xcf, 0xce, 0xd8, 0x4b, 0xad, 0x33, 0x4f, 0x71, 0xe6, 0xa2, 0x5f,
	0x66, 0x9d, 0x39, 0xea, 0x4a, 0x4e, 0xc9, 0xcb, 0xad, 0x33, 0x2f, 0x50, 0xcb, 0x09, 0x7d, 0x85,
	0x55, 0x67, 0xa0, 0x63, 0xd1, 0xaf, 0x34, 0xea, 0x18, 0x75, 0x2d, 0xfa, 0x55, 0x46, 0xbd, 0xdc,
	0xcb, 0x96, 0x1d, 0x7b, 0xb5, 0x35, 0xbb, 0xb7, 0x63, 0xb2, 0x6a, 0xaf, 0xb1, 0xee, 0x18, 0xae,
	0xda, 0xec, 0x7f, 0x36, 0xbd, 0xd6, 0x3a, 0x73, 0xcc, 0x4e, 0x44, 0xbf, 0xce, 0xa8, 0x13, 0xd4,
	0xb1, 0xcc, 0xfc, 0xf5, 0xd6, 0xeb, 0xee, 0xcd, 0x5c, 0xf4, 0x1b, 0xac, 0x33, 0x47, 0x9d, 0x88,
	0x3e, 0x69, 0x9d, 0x79, 0x2f, 0x5b, 0x9e, 0x7a, 0xae, 0xb4, 0x66, 0x7b, 0xcc, 0x16, 0x7d, 0x95,
	0x35, 0x1b, 0xf5, 0xec, 0x9d, 0xe8, 0x6a, 0xeb, 0x7e, 0xeb, 0x5a, 0x3b, 0xbe, 0xb1, 0x7b, 0xf7,
	0xbf, 0xe6, 0x60, 0xbd, 0x37, 0xbe, 0xa3, 0x2f, 0xd9, 0xe8, 0xde, 0xfd, 0x65, 0x74, 0xf6, 0x6e,
	0x70, 0xad, 0x51, 0x3b, 0xd4, 0xb3, 0x67, 0xa6, 0xeb, 0xac, 0xd9, 0x31, 0x66, 0x8b, 0xbe, 0xde,
	0x9a, 0xdd, 0x79, 0xe2, 0x9a, 0x6c, 0xad, 0x65, 0x51, 0x9a, 0xd3, 0x2d, 0x07, 0xeb, 0xbd, 0xf1,
	0xdd, 0xbb, 0xe0, 0x64, 0x4b, 0x3e, 0x80, 0x6e, 0x72, 0xba, 0xd5, 0xac, 0x9b, 0x9e, 0x2e, 0xe8,
	0xdd, 0x21, 0xdd, 0x14, 0x5a, 0x17, 0x38, 0x73, 0x4f, 0xef, 0x0f, 0x66, 0x7b, 0x3d, 0x73, 0x8f,
	0xd9, 0x9e, 0x3e, 0x60, 0xd6, 0x0d, 0xea, 0xb4, 0xa2, 0x0f, 0x06, 0x75, 0xa5, 0xb3, 0x2b, 0xcc,
	0xae, 0xe8, 0x43, 0x66, 0xdd, 0xa0, 0x4e, 0x6b, 0xfa, 0x70, 0x50, 0xd7, 0x3a, 0xbb, 0xc6, 0xec,
	0x9a, 0x3e, 0x62, 0xd6, 0x4d, 0x4f, 0x37, 0xf4, 0xd1, 0xa0, 0xce, 0xb4, 0x6e, 0x50, 0xb7, 0xf4,
	0x31, 0x7b, 0x76, 0x8b, 0x7a, 0x4c, 0x1f, 0x0f, 0xea, 0x54, 0xeb, 0x31, 0xae, 0x5a, 0x4a, 0x9f,
	0x30, 0xeb, 0x34, 0xc5, 0xec, 0x94, 0x3e, 0x69, 0xcf, 0x46, 0x9d, 0x66, 0xf4, 0x29, 0xf3, 0xaa,
	0xa5, 0x19, 0x66, 0x67, 0x74, 0x9b, 0x7d, 0xcd, 0xe7, 0x7a, 0x3a, 0xd9, 0x7d, 0x7b, 0xff, 0xe6,
	0xed, 0x0e, 0xd4, 0x32, 0x1e, 0xed, 0xbf, 0x51, 0x5d, 0x3a, 0xe9, 0xbe, 0xbd, 0xcb, 0xe8, 0xec,
	0xad, 0xe6, 0x5b, 0x46, 0x5d, 0xa2, 0x6e, 0xe4, 0x19, 0xf9, 0xdb, 0xc3, 0xba, 0x61, 0xa5, 0x57,
	0x18, 0xb4, 0xfc, 0xb7, 0xe9, 0x3b, 0xc6, 0xec, 0x28, 0x01, 0xed, 0x45, 0x7f, 0x77, 0x58, 0x8f,
	0xb5, 0x5e, 0x44, 0x1d, 0xc9, 0x5d, 0xf0, 0x7b, 0x81, 0xec, 0x42, 0x67, 0x17, 0x98, 0x2d, 0xfa,
	0xfb, 0xd6, 0x6c, 0xd4, 0xb1, 0xac, 0xda, 0x0f, 0x86, 0x75, 0xac, 0x57, 0x2d, 0xc6, 0x55, 0xab,
	0x44, 0xff, 0xd0, 0x98, 0xbd, 0xd4, 0xd3, 0xf2, 0x46, 0xf5, 0x23, 0x63, 0xf6, 0x52, 0x84, 0xd5,
	0x22, 0xf7, 0xef, 0x1f, 0x0f, 0xeb, 0xf9, 0xef, 0x99, 0xa4, 0x5a, 0x3c, 0xe8, 0x5a, 0xde, 0x81,
	0x7f, 0x32, 0xac, 0x65, 0x7c, 0x5f, 0x2f, 0x37, 0xa0, 0x5d, 0xcd, 0x4c, 0x3f, 0x1d, 0xd6, 0xae,
	0xd6, 0x75, 0x5e, 0xe3, 0xcc, 0x45, 0xff, 0xcc, 0xb8, 0x6a, 0x25, 0xea, 0xd9, 0x6f, 0xe7, 0x7e,
	0x1e, 0xc8, 0xd6, 0x33, 0x77, 0x38, 0xf3, 0xd9, 0xbb, 0xff, 0x2f, 0x02, 0xab, 0xa6, 0x75, 0x89,
	0x3a, 0x97, 0xfd, 0xfe, 0x65, 0x60, 0xe6, 0x7a, 0xc7, 0x72, 0xdc, 0x6f, 0x19, 0xa5, 0x5f, 0x19,
	0xf5, 0x08, 0x75, 0x2e, 0x4f, 0x3d, 0xbf, 0x0e, 0x68, 0xa7, 0xb3, 0x1d, 0x66, 0x8b, 0xfe, 0x8d,
	0x51, 0x8f, 0x50, 0xe7, 0x52, 0xa9, 0xbf, 0x0d, 0xe8, 0x48, 0x67, 0x63, 0xa5, 0xca, 0x28, 0xfd,
	0xce, 0xa8, 0x47, 0xa8, 0x73, 0x79, 0xe2, 0xfa, 0xfd, 0xb0, 0xce, 0x63, 0x9d, 0x1d, 0x63, 0xb6,
	0xe8, 0x3f, 0x18, 0xf5, 0x08, 0x75, 0x2e, 0x7d, 0xed, 0x8f, 0x01, 0xad, 0x2b, 0x35, 0xc7, 0xbe,
	0x26, 0x75, 0x4c, 0x7f, 0x32, 0xd6, 0xf9, 0x08, 0x75, 0x2e, 0x4f, 0xd8, 0x7f, 0x36, 0x9e, 0xd0,
	0x3c, 0xc3, 0x6c, 0xd1, 0x7f, 0xb1, 0x66, 0xf7, 0xb4, 0xdc, 0x89, 0xfe, 0x1a, 0xd0, 0xa5, 0xd6,
	0x78, 0x27, 0xca, 0xa5, 0x33, 0xfd, 0xcd, 0x78, 0x42, 0x73, 0xec, 0x4c, 0x63, 0xd1, 0x7f, 0x37,
	0x9e, 0xd0, 0x11, 0xea, 0xd9, 0xdf, 0xc2, 0xfd, 0x23, 0xb0, 0x63, 0x95, 0xce, 0xae, 0x30, 0x5b,
	0xf4, 0x3f, 0x8d, 0x7a, 0xd4, 0xd3, 0x2d, 0x33, 0xfd, 0x2b, 0xb0, 0x6a, 0xad, 0xd6, 0x2d, 0xce,
	0x5c, 0xba, 0xe2, 0xbf, 0x03, 0xd9, 0xba, 0xa7, 0xe6, 0xd8, 0x15, 0xc7, 0xa2, 0xff, 0x63, 0xdd,
	0x6f, 0xd4, 0xd9, 0x98, 0x99, 0xfe, 0x3b, 0xac, 0xb3, 0xb1, 0xd2, 0xd9, 0x18, 0x74, 0x2b, 0xfa,
	0xe9, 0xa7, 0xd8, 0xf4, 0x2a, 0xea, 0x4c, 0x56, 0xed, 0x19, 0x01, 0xad, 0x57, 0x2d, 0xc3, 0x55,
	0x6b, 0x45, 0x3f, 0xd3, 0xa8, 0x57, 0x51, 0x67, 0xb2, 0xdf, 0xcf, 0x0a, 0x68, 0xbd, 0xdf, 0x19,
	0xee, 0x77, 0x2b, 0xfa, 0xd9, 0xa7, 0xd8, 0xd6, 0x7c, 0x15, 0x75, 0x26, 0x3b, 0xf6, 0x9c, 0x40,
	0xb6, 0xde, 0xef, 0x0c, 0x77, 0xac, 0x15, 0xfd, 0xdc, 0x61, 0xdd, 0x6a, 0xbd, 0x8a, 0x7a, 0xf6,
	0x97, 0x4b, 0xcf, 0x1b, 0xd6, 0xb9, 0x7e, 0xe2, 0xca, 0xf1, 0x99, 0x69, 0xf6, 0xa7, 0x4b, 0xcf,
	0x0f, 0x5c, 0xb7, 0xd6, 0x23, 0xd4, 0x95, 0xf4, 0x96, 0x17, 0x0c, 0xeb, 0x58, 0xf7, 0x96, 0xa5,
	0x92, 0x79, 0xe9, 0xff, 0x2e, 0x3a, 0x54, 0x9d, 0x3a, 0xfb, 0xd7, 0x22, 0xf1, 0xff, 0x02, 0x00,
	0x00, 0xff, 0xff, 0x19, 0xd9, 0x04, 0xbd, 0xb1, 0x32, 0x00, 0x00,
}
