// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg_nb.proto

package wlst_nbiot

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MsgNBiot struct {
	CmdIdx int64 `protobuf:"varint,1,opt,name=cmd_idx,json=cmdIdx,proto3" json:"cmd_idx,omitempty"`
	// GoWork or GoWorkTask
	CmdName string `protobuf:"bytes,2,opt,name=cmd_name,json=cmdName,proto3" json:"cmd_name,omitempty"`
	// 0xdad9 or 0xdad0
	CmdFlag int32   `protobuf:"varint,3,opt,name=cmd_flag,json=cmdFlag,proto3" json:"cmd_flag,omitempty"`
	Imei    []int64 `protobuf:"varint,4,rep,packed,name=imei,proto3" json:"imei,omitempty"`
	// hex string
	RawData              []int32  `protobuf:"varint,5,rep,packed,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgNBiot) Reset()         { *m = MsgNBiot{} }
func (m *MsgNBiot) String() string { return proto.CompactTextString(m) }
func (*MsgNBiot) ProtoMessage()    {}
func (*MsgNBiot) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d0ba9a34991f86e, []int{0}
}

func (m *MsgNBiot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgNBiot.Unmarshal(m, b)
}
func (m *MsgNBiot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgNBiot.Marshal(b, m, deterministic)
}
func (m *MsgNBiot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgNBiot.Merge(m, src)
}
func (m *MsgNBiot) XXX_Size() int {
	return xxx_messageInfo_MsgNBiot.Size(m)
}
func (m *MsgNBiot) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgNBiot.DiscardUnknown(m)
}

var xxx_messageInfo_MsgNBiot proto.InternalMessageInfo

func (m *MsgNBiot) GetCmdIdx() int64 {
	if m != nil {
		return m.CmdIdx
	}
	return 0
}

func (m *MsgNBiot) GetCmdName() string {
	if m != nil {
		return m.CmdName
	}
	return ""
}

func (m *MsgNBiot) GetCmdFlag() int32 {
	if m != nil {
		return m.CmdFlag
	}
	return 0
}

func (m *MsgNBiot) GetImei() []int64 {
	if m != nil {
		return m.Imei
	}
	return nil
}

func (m *MsgNBiot) GetRawData() []int32 {
	if m != nil {
		return m.RawData
	}
	return nil
}

//数据服务和通讯服务传输格式
type MsgNBOpen struct {
	// 设备imei
	Imei int64 `protobuf:"varint,1,opt,name=imei,proto3" json:"imei,omitempty"`
	// 数据接收时间
	DtReceive int64 `protobuf:"varint,2,opt,name=dt_receive,json=dtReceive,proto3" json:"dt_receive,omitempty"`
	// 数据类型，1-设备最新数据，2-控制应答，3-参数设置/读取应答
	DataType int32 `protobuf:"varint,3,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	// 内部用命令字符串，类似wlst.vslu.3900等
	DataCmd string `protobuf:"bytes,9,opt,name=data_cmd,json=dataCmd,proto3" json:"data_cmd,omitempty"`
	// 设备最新数据
	SluitemData *SluitemData `protobuf:"bytes,4,opt,name=sluitem_data,json=sluitemData,proto3" json:"sluitem_data,omitempty"`
	// 控制应答
	SluitemReply *SluitemReply `protobuf:"bytes,5,opt,name=sluitem_reply,json=sluitemReply,proto3" json:"sluitem_reply,omitempty"`
	// 参数设置/读取
	SluitemConfig        *SluitemConfig `protobuf:"bytes,6,opt,name=sluitem_config,json=sluitemConfig,proto3" json:"sluitem_config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *MsgNBOpen) Reset()         { *m = MsgNBOpen{} }
func (m *MsgNBOpen) String() string { return proto.CompactTextString(m) }
func (*MsgNBOpen) ProtoMessage()    {}
func (*MsgNBOpen) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d0ba9a34991f86e, []int{1}
}

func (m *MsgNBOpen) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgNBOpen.Unmarshal(m, b)
}
func (m *MsgNBOpen) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgNBOpen.Marshal(b, m, deterministic)
}
func (m *MsgNBOpen) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgNBOpen.Merge(m, src)
}
func (m *MsgNBOpen) XXX_Size() int {
	return xxx_messageInfo_MsgNBOpen.Size(m)
}
func (m *MsgNBOpen) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgNBOpen.DiscardUnknown(m)
}

var xxx_messageInfo_MsgNBOpen proto.InternalMessageInfo

func (m *MsgNBOpen) GetImei() int64 {
	if m != nil {
		return m.Imei
	}
	return 0
}

func (m *MsgNBOpen) GetDtReceive() int64 {
	if m != nil {
		return m.DtReceive
	}
	return 0
}

func (m *MsgNBOpen) GetDataType() int32 {
	if m != nil {
		return m.DataType
	}
	return 0
}

func (m *MsgNBOpen) GetDataCmd() string {
	if m != nil {
		return m.DataCmd
	}
	return ""
}

func (m *MsgNBOpen) GetSluitemData() *SluitemData {
	if m != nil {
		return m.SluitemData
	}
	return nil
}

func (m *MsgNBOpen) GetSluitemReply() *SluitemReply {
	if m != nil {
		return m.SluitemReply
	}
	return nil
}

func (m *MsgNBOpen) GetSluitemConfig() *SluitemConfig {
	if m != nil {
		return m.SluitemConfig
	}
	return nil
}

type SluitemConfig struct {
	// 序号
	CmdIdx int32 `protobuf:"varint,1,opt,name=cmd_idx,json=cmdIdx,proto3" json:"cmd_idx,omitempty"`
	// 控制器条码（4字节）
	SluitemIdx int64 `protobuf:"varint,2,opt,name=sluitem_idx,json=sluitemIdx,proto3" json:"sluitem_idx,omitempty"`
	// 参数读取标识
	DataMark *SluitemConfig_DataMark `protobuf:"bytes,4,opt,name=data_mark,json=dataMark,proto3" json:"data_mark,omitempty"`
	// 控制器回路数量
	LoopCount int32 `protobuf:"varint,5,opt,name=loop_count,json=loopCount,proto3" json:"loop_count,omitempty"`
	// 控制器时钟(read_timer)
	SluitemTime int64 `protobuf:"varint,7,opt,name=sluitem_time,json=sluitemTime,proto3" json:"sluitem_time,omitempty"`
	// 控制器运行参数(read_args)
	SluitemPara *SluitemConfig_SluitemPara `protobuf:"bytes,8,opt,name=sluitem_para,json=sluitemPara,proto3" json:"sluitem_para,omitempty"`
	// 控制器版本(read_ver)
	SluitemVer *SluitemConfig_SluitemVer `protobuf:"bytes,10,opt,name=sluitem_ver,json=sluitemVer,proto3" json:"sluitem_ver,omitempty"`
	// 控制器当日日出日落(read_sunriseset)
	SluitemSunriseset *SluitemConfig_SluitemSunriseset `protobuf:"bytes,11,opt,name=sluitem_sunriseset,json=sluitemSunriseset,proto3" json:"sluitem_sunriseset,omitempty"`
	// 控制器定时控制参数(read_timetable)
	SluitemRuntime []*SluitemConfig_SluitemRuntime `protobuf:"bytes,12,rep,name=sluitem_runtime,json=sluitemRuntime,proto3" json:"sluitem_runtime,omitempty"`
	// 设置状态0-失败，1-成功
	Status int32 `protobuf:"varint,14,opt,name=status,proto3" json:"status,omitempty"`
	// 参数设置标识
	SetMark              *SluitemConfig_SetMark `protobuf:"bytes,15,opt,name=set_mark,json=setMark,proto3" json:"set_mark,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *SluitemConfig) Reset()         { *m = SluitemConfig{} }
func (m *SluitemConfig) String() string { return proto.CompactTextString(m) }
func (*SluitemConfig) ProtoMessage()    {}
func (*SluitemConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d0ba9a34991f86e, []int{2}
}

func (m *SluitemConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SluitemConfig.Unmarshal(m, b)
}
func (m *SluitemConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SluitemConfig.Marshal(b, m, deterministic)
}
func (m *SluitemConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SluitemConfig.Merge(m, src)
}
func (m *SluitemConfig) XXX_Size() int {
	return xxx_messageInfo_SluitemConfig.Size(m)
}
func (m *SluitemConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_SluitemConfig.DiscardUnknown(m)
}

var xxx_messageInfo_SluitemConfig proto.InternalMessageInfo

func (m *SluitemConfig) GetCmdIdx() int32 {
	if m != nil {
		return m.CmdIdx
	}
	return 0
}

func (m *SluitemConfig) GetSluitemIdx() int64 {
	if m != nil {
		return m.SluitemIdx
	}
	return 0
}

func (m *SluitemConfig) GetDataMark() *SluitemConfig_DataMark {
	if m != nil {
		return m.DataMark
	}
	return nil
}

func (m *SluitemConfig) GetLoopCount() int32 {
	if m != nil {
		return m.LoopCount
	}
	return 0
}

func (m *SluitemConfig) GetSluitemTime() int64 {
	if m != nil {
		return m.SluitemTime
	}
	return 0
}

func (m *SluitemConfig) GetSluitemPara() *SluitemConfig_SluitemPara {
	if m != nil {
		return m.SluitemPara
	}
	return nil
}

func (m *SluitemConfig) GetSluitemVer() *SluitemConfig_SluitemVer {
	if m != nil {
		return m.SluitemVer
	}
	return nil
}

func (m *SluitemConfig) GetSluitemSunriseset() *SluitemConfig_SluitemSunriseset {
	if m != nil {
		return m.SluitemSunriseset
	}
	return nil
}

func (m *SluitemConfig) GetSluitemRuntime() []*SluitemConfig_SluitemRuntime {
	if m != nil {
		return m.SluitemRuntime
	}
	return nil
}

func (m *SluitemConfig) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *SluitemConfig) GetSetMark() *SluitemConfig_SetMark {
	if m != nil {
		return m.SetMark
	}
	return nil
}

type SluitemConfig_DataMark struct {
	// 读取时钟
	ReadTimer int32 `protobuf:"varint,2,opt,name=read_timer,json=readTimer,proto3" json:"read_timer,omitempty"`
	// 读取运行参数
	ReadArgs int32 `protobuf:"varint,3,opt,name=read_args,json=readArgs,proto3" json:"read_args,omitempty"`
	// 读取版本
	ReadVer int32 `protobuf:"varint,5,opt,name=read_ver,json=readVer,proto3" json:"read_ver,omitempty"`
	// 读取当天日出日落
	ReadSunriseset int32 `protobuf:"varint,6,opt,name=read_sunriseset,json=readSunriseset,proto3" json:"read_sunriseset,omitempty"`
	// 读取定时控制参数
	ReadTimetable        int32    `protobuf:"varint,7,opt,name=read_timetable,json=readTimetable,proto3" json:"read_timetable,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SluitemConfig_DataMark) Reset()         { *m = SluitemConfig_DataMark{} }
func (m *SluitemConfig_DataMark) String() string { return proto.CompactTextString(m) }
func (*SluitemConfig_DataMark) ProtoMessage()    {}
func (*SluitemConfig_DataMark) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d0ba9a34991f86e, []int{2, 0}
}

func (m *SluitemConfig_DataMark) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SluitemConfig_DataMark.Unmarshal(m, b)
}
func (m *SluitemConfig_DataMark) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SluitemConfig_DataMark.Marshal(b, m, deterministic)
}
func (m *SluitemConfig_DataMark) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SluitemConfig_DataMark.Merge(m, src)
}
func (m *SluitemConfig_DataMark) XXX_Size() int {
	return xxx_messageInfo_SluitemConfig_DataMark.Size(m)
}
func (m *SluitemConfig_DataMark) XXX_DiscardUnknown() {
	xxx_messageInfo_SluitemConfig_DataMark.DiscardUnknown(m)
}

var xxx_messageInfo_SluitemConfig_DataMark proto.InternalMessageInfo

func (m *SluitemConfig_DataMark) GetReadTimer() int32 {
	if m != nil {
		return m.ReadTimer
	}
	return 0
}

func (m *SluitemConfig_DataMark) GetReadArgs() int32 {
	if m != nil {
		return m.ReadArgs
	}
	return 0
}

func (m *SluitemConfig_DataMark) GetReadVer() int32 {
	if m != nil {
		return m.ReadVer
	}
	return 0
}

func (m *SluitemConfig_DataMark) GetReadSunriseset() int32 {
	if m != nil {
		return m.ReadSunriseset
	}
	return 0
}

func (m *SluitemConfig_DataMark) GetReadTimetable() int32 {
	if m != nil {
		return m.ReadTimetable
	}
	return 0
}

type SluitemConfig_SetMark struct {
	// 设置时钟
	SetTimer int32 `protobuf:"varint,1,opt,name=set_timer,json=setTimer,proto3" json:"set_timer,omitempty"`
	// 设置运行参数
	SetArgs int32 `protobuf:"varint,2,opt,name=set_args,json=setArgs,proto3" json:"set_args,omitempty"`
	// 复位设备
	SetReset int32 `protobuf:"varint,4,opt,name=set_reset,json=setReset,proto3" json:"set_reset,omitempty"`
	// 设置定时控制参数
	SetTimetable         int32    `protobuf:"varint,5,opt,name=set_timetable,json=setTimetable,proto3" json:"set_timetable,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SluitemConfig_SetMark) Reset()         { *m = SluitemConfig_SetMark{} }
func (m *SluitemConfig_SetMark) String() string { return proto.CompactTextString(m) }
func (*SluitemConfig_SetMark) ProtoMessage()    {}
func (*SluitemConfig_SetMark) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d0ba9a34991f86e, []int{2, 1}
}

func (m *SluitemConfig_SetMark) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SluitemConfig_SetMark.Unmarshal(m, b)
}
func (m *SluitemConfig_SetMark) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SluitemConfig_SetMark.Marshal(b, m, deterministic)
}
func (m *SluitemConfig_SetMark) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SluitemConfig_SetMark.Merge(m, src)
}
func (m *SluitemConfig_SetMark) XXX_Size() int {
	return xxx_messageInfo_SluitemConfig_SetMark.Size(m)
}
func (m *SluitemConfig_SetMark) XXX_DiscardUnknown() {
	xxx_messageInfo_SluitemConfig_SetMark.DiscardUnknown(m)
}

var xxx_messageInfo_SluitemConfig_SetMark proto.InternalMessageInfo

func (m *SluitemConfig_SetMark) GetSetTimer() int32 {
	if m != nil {
		return m.SetTimer
	}
	return 0
}

func (m *SluitemConfig_SetMark) GetSetArgs() int32 {
	if m != nil {
		return m.SetArgs
	}
	return 0
}

func (m *SluitemConfig_SetMark) GetSetReset() int32 {
	if m != nil {
		return m.SetReset
	}
	return 0
}

func (m *SluitemConfig_SetMark) GetSetTimetable() int32 {
	if m != nil {
		return m.SetTimetable
	}
	return 0
}

type SluitemConfig_SluitemPara struct {
	// 域名
	DomainName int32 `protobuf:"varint,1,opt,name=domain_name,json=domainName,proto3" json:"domain_name,omitempty"`
	// 控制器状态 false-停运，true-投运
	SluitemStatus int32 `protobuf:"varint,2,opt,name=sluitem_status,json=sluitemStatus,proto3" json:"sluitem_status,omitempty"`
	// 控制器主报 false-禁止主报，true-允许主报
	SluitemEnableAlarm int32 `protobuf:"varint,3,opt,name=sluitem_enable_alarm,json=sluitemEnableAlarm,proto3" json:"sluitem_enable_alarm,omitempty"`
	// 控制器上电开灯 true-开灯，false-关灯
	SluitemPowerTurnon []int32 `protobuf:"varint,4,rep,packed,name=sluitem_power_turnon,json=sluitemPowerTurnon,proto3" json:"sluitem_power_turnon,omitempty"`
	// 控制器1-4回路矢量
	SluitemVector []int32 `protobuf:"varint,5,rep,packed,name=sluitem_vector,json=sluitemVector,proto3" json:"sluitem_vector,omitempty"`
	// 经度
	Longitude float64 `protobuf:"fixed64,6,opt,name=longitude,proto3" json:"longitude,omitempty"`
	// 纬度
	Latitude float64 `protobuf:"fixed64,7,opt,name=latitude,proto3" json:"latitude,omitempty"`
	// 1-4回路额定功率
	RatedPower []int32 `protobuf:"varint,8,rep,packed,name=rated_power,json=ratedPower,proto3" json:"rated_power,omitempty"`
	// nb主报间隔，(0～127)*5
	UplinkTimer int32 `protobuf:"varint,9,opt,name=uplink_timer,json=uplinkTimer,proto3" json:"uplink_timer,omitempty"`
	// nb主报需要主站应答，0-不需要，1-需要
	UplinkReply          int32    `protobuf:"varint,10,opt,name=uplink_reply,json=uplinkReply,proto3" json:"uplink_reply,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SluitemConfig_SluitemPara) Reset()         { *m = SluitemConfig_SluitemPara{} }
func (m *SluitemConfig_SluitemPara) String() string { return proto.CompactTextString(m) }
func (*SluitemConfig_SluitemPara) ProtoMessage()    {}
func (*SluitemConfig_SluitemPara) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d0ba9a34991f86e, []int{2, 2}
}

func (m *SluitemConfig_SluitemPara) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SluitemConfig_SluitemPara.Unmarshal(m, b)
}
func (m *SluitemConfig_SluitemPara) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SluitemConfig_SluitemPara.Marshal(b, m, deterministic)
}
func (m *SluitemConfig_SluitemPara) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SluitemConfig_SluitemPara.Merge(m, src)
}
func (m *SluitemConfig_SluitemPara) XXX_Size() int {
	return xxx_messageInfo_SluitemConfig_SluitemPara.Size(m)
}
func (m *SluitemConfig_SluitemPara) XXX_DiscardUnknown() {
	xxx_messageInfo_SluitemConfig_SluitemPara.DiscardUnknown(m)
}

var xxx_messageInfo_SluitemConfig_SluitemPara proto.InternalMessageInfo

func (m *SluitemConfig_SluitemPara) GetDomainName() int32 {
	if m != nil {
		return m.DomainName
	}
	return 0
}

func (m *SluitemConfig_SluitemPara) GetSluitemStatus() int32 {
	if m != nil {
		return m.SluitemStatus
	}
	return 0
}

func (m *SluitemConfig_SluitemPara) GetSluitemEnableAlarm() int32 {
	if m != nil {
		return m.SluitemEnableAlarm
	}
	return 0
}

func (m *SluitemConfig_SluitemPara) GetSluitemPowerTurnon() []int32 {
	if m != nil {
		return m.SluitemPowerTurnon
	}
	return nil
}

func (m *SluitemConfig_SluitemPara) GetSluitemVector() []int32 {
	if m != nil {
		return m.SluitemVector
	}
	return nil
}

func (m *SluitemConfig_SluitemPara) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *SluitemConfig_SluitemPara) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *SluitemConfig_SluitemPara) GetRatedPower() []int32 {
	if m != nil {
		return m.RatedPower
	}
	return nil
}

func (m *SluitemConfig_SluitemPara) GetUplinkTimer() int32 {
	if m != nil {
		return m.UplinkTimer
	}
	return 0
}

func (m *SluitemConfig_SluitemPara) GetUplinkReply() int32 {
	if m != nil {
		return m.UplinkReply
	}
	return 0
}

type SluitemConfig_SluitemVer struct {
	// 控制器回路
	SluitemLoop int32 `protobuf:"varint,1,opt,name=sluitem_loop,json=sluitemLoop,proto3" json:"sluitem_loop,omitempty"`
	// 节能方式
	EnergySaving int32 `protobuf:"varint,2,opt,name=energy_saving,json=energySaving,proto3" json:"energy_saving,omitempty"`
	// 有漏电模块
	ElectricLeakageModule int32 `protobuf:"varint,3,opt,name=electric_leakage_module,json=electricLeakageModule,proto3" json:"electric_leakage_module,omitempty"`
	// 有温度检测模块
	TemperatureModule int32 `protobuf:"varint,4,opt,name=temperature_module,json=temperatureModule,proto3" json:"temperature_module,omitempty"`
	// 有时钟
	TimerModule int32 `protobuf:"varint,5,opt,name=timer_module,json=timerModule,proto3" json:"timer_module,omitempty"`
	// 型号 0-unknow,1-wj2090j
	SluitemType string `protobuf:"bytes,6,opt,name=sluitem_type,json=sluitemType,proto3" json:"sluitem_type,omitempty"`
	// 软件版本
	Ver                  string   `protobuf:"bytes,7,opt,name=ver,proto3" json:"ver,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SluitemConfig_SluitemVer) Reset()         { *m = SluitemConfig_SluitemVer{} }
func (m *SluitemConfig_SluitemVer) String() string { return proto.CompactTextString(m) }
func (*SluitemConfig_SluitemVer) ProtoMessage()    {}
func (*SluitemConfig_SluitemVer) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d0ba9a34991f86e, []int{2, 3}
}

func (m *SluitemConfig_SluitemVer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SluitemConfig_SluitemVer.Unmarshal(m, b)
}
func (m *SluitemConfig_SluitemVer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SluitemConfig_SluitemVer.Marshal(b, m, deterministic)
}
func (m *SluitemConfig_SluitemVer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SluitemConfig_SluitemVer.Merge(m, src)
}
func (m *SluitemConfig_SluitemVer) XXX_Size() int {
	return xxx_messageInfo_SluitemConfig_SluitemVer.Size(m)
}
func (m *SluitemConfig_SluitemVer) XXX_DiscardUnknown() {
	xxx_messageInfo_SluitemConfig_SluitemVer.DiscardUnknown(m)
}

var xxx_messageInfo_SluitemConfig_SluitemVer proto.InternalMessageInfo

func (m *SluitemConfig_SluitemVer) GetSluitemLoop() int32 {
	if m != nil {
		return m.SluitemLoop
	}
	return 0
}

func (m *SluitemConfig_SluitemVer) GetEnergySaving() int32 {
	if m != nil {
		return m.EnergySaving
	}
	return 0
}

func (m *SluitemConfig_SluitemVer) GetElectricLeakageModule() int32 {
	if m != nil {
		return m.ElectricLeakageModule
	}
	return 0
}

func (m *SluitemConfig_SluitemVer) GetTemperatureModule() int32 {
	if m != nil {
		return m.TemperatureModule
	}
	return 0
}

func (m *SluitemConfig_SluitemVer) GetTimerModule() int32 {
	if m != nil {
		return m.TimerModule
	}
	return 0
}

func (m *SluitemConfig_SluitemVer) GetSluitemType() string {
	if m != nil {
		return m.SluitemType
	}
	return ""
}

func (m *SluitemConfig_SluitemVer) GetVer() string {
	if m != nil {
		return m.Ver
	}
	return ""
}

type SluitemConfig_SluitemSunriseset struct {
	// 当日日出日落时间 hhmm->int32
	Sunrise              int32    `protobuf:"varint,1,opt,name=sunrise,proto3" json:"sunrise,omitempty"`
	Sunset               int32    `protobuf:"varint,2,opt,name=sunset,proto3" json:"sunset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SluitemConfig_SluitemSunriseset) Reset()         { *m = SluitemConfig_SluitemSunriseset{} }
func (m *SluitemConfig_SluitemSunriseset) String() string { return proto.CompactTextString(m) }
func (*SluitemConfig_SluitemSunriseset) ProtoMessage()    {}
func (*SluitemConfig_SluitemSunriseset) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d0ba9a34991f86e, []int{2, 4}
}

func (m *SluitemConfig_SluitemSunriseset) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SluitemConfig_SluitemSunriseset.Unmarshal(m, b)
}
func (m *SluitemConfig_SluitemSunriseset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SluitemConfig_SluitemSunriseset.Marshal(b, m, deterministic)
}
func (m *SluitemConfig_SluitemSunriseset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SluitemConfig_SluitemSunriseset.Merge(m, src)
}
func (m *SluitemConfig_SluitemSunriseset) XXX_Size() int {
	return xxx_messageInfo_SluitemConfig_SluitemSunriseset.Size(m)
}
func (m *SluitemConfig_SluitemSunriseset) XXX_DiscardUnknown() {
	xxx_messageInfo_SluitemConfig_SluitemSunriseset.DiscardUnknown(m)
}

var xxx_messageInfo_SluitemConfig_SluitemSunriseset proto.InternalMessageInfo

func (m *SluitemConfig_SluitemSunriseset) GetSunrise() int32 {
	if m != nil {
		return m.Sunrise
	}
	return 0
}

func (m *SluitemConfig_SluitemSunriseset) GetSunset() int32 {
	if m != nil {
		return m.Sunset
	}
	return 0
}

type SluitemConfig_SluitemRuntime struct {
	// 本地控制数据类型0-基本类型（6字节），1-扩展类型（6+20字节）
	DataType int32 `protobuf:"varint,1,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	// 输出类型0-继电器，1-pwm输出，2-485
	OutputType int32 `protobuf:"varint,2,opt,name=output_type,json=outputType,proto3" json:"output_type,omitempty"`
	// 操作类型1-定时操作，2-经纬度操作，3-即时操作
	OperateType int32 `protobuf:"varint,3,opt,name=operate_type,json=operateType,proto3" json:"operate_type,omitempty"`
	// 有效日期，0-6～周日-周6
	DateEnable []int32 `protobuf:"varint,4,rep,packed,name=date_enable,json=dateEnable,proto3" json:"date_enable,omitempty"`
	// 开关灯操作时间 hhmm->int32
	OperateTime int32 `protobuf:"varint,5,opt,name=operate_time,json=operateTime,proto3" json:"operate_time,omitempty"`
	// 操作偏移 -720~+720
	OperateOffset int32 `protobuf:"varint,6,opt,name=operate_offset,json=operateOffset,proto3" json:"operate_offset,omitempty"`
	// 继电器操作回路1-4 0-不操作，3-开灯，5-一档节能，a-二档节能，c-关灯
	RelayOperate []int32 `protobuf:"varint,7,rep,packed,name=relay_operate,json=relayOperate,proto3" json:"relay_operate,omitempty"`
	// PWM操作回路
	PwmLoop []int32 `protobuf:"varint,8,rep,packed,name=pwm_loop,json=pwmLoop,proto3" json:"pwm_loop,omitempty"`
	// PWM操作占空比
	PwmPower int32 `protobuf:"varint,9,opt,name=pwm_power,json=pwmPower,proto3" json:"pwm_power,omitempty"`
	// PWM频率 (1~255) * 100
	PwmBaudrate int32 `protobuf:"varint,10,opt,name=pwm_baudrate,json=pwmBaudrate,proto3" json:"pwm_baudrate,omitempty"`
	// 485波特率 0-300,1-600,2-1200,3-2400,4-4800,5-9600,6-19200
	Rs485Baudrate int32 `protobuf:"varint,11,opt,name=rs485_baudrate,json=rs485Baudrate,proto3" json:"rs485_baudrate,omitempty"`
	// 485校验位 0-无校验，1-奇校验，2-偶校验
	Rs485Check           int32    `protobuf:"varint,12,opt,name=rs485_check,json=rs485Check,proto3" json:"rs485_check,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SluitemConfig_SluitemRuntime) Reset()         { *m = SluitemConfig_SluitemRuntime{} }
func (m *SluitemConfig_SluitemRuntime) String() string { return proto.CompactTextString(m) }
func (*SluitemConfig_SluitemRuntime) ProtoMessage()    {}
func (*SluitemConfig_SluitemRuntime) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d0ba9a34991f86e, []int{2, 5}
}

func (m *SluitemConfig_SluitemRuntime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SluitemConfig_SluitemRuntime.Unmarshal(m, b)
}
func (m *SluitemConfig_SluitemRuntime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SluitemConfig_SluitemRuntime.Marshal(b, m, deterministic)
}
func (m *SluitemConfig_SluitemRuntime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SluitemConfig_SluitemRuntime.Merge(m, src)
}
func (m *SluitemConfig_SluitemRuntime) XXX_Size() int {
	return xxx_messageInfo_SluitemConfig_SluitemRuntime.Size(m)
}
func (m *SluitemConfig_SluitemRuntime) XXX_DiscardUnknown() {
	xxx_messageInfo_SluitemConfig_SluitemRuntime.DiscardUnknown(m)
}

var xxx_messageInfo_SluitemConfig_SluitemRuntime proto.InternalMessageInfo

func (m *SluitemConfig_SluitemRuntime) GetDataType() int32 {
	if m != nil {
		return m.DataType
	}
	return 0
}

func (m *SluitemConfig_SluitemRuntime) GetOutputType() int32 {
	if m != nil {
		return m.OutputType
	}
	return 0
}

func (m *SluitemConfig_SluitemRuntime) GetOperateType() int32 {
	if m != nil {
		return m.OperateType
	}
	return 0
}

func (m *SluitemConfig_SluitemRuntime) GetDateEnable() []int32 {
	if m != nil {
		return m.DateEnable
	}
	return nil
}

func (m *SluitemConfig_SluitemRuntime) GetOperateTime() int32 {
	if m != nil {
		return m.OperateTime
	}
	return 0
}

func (m *SluitemConfig_SluitemRuntime) GetOperateOffset() int32 {
	if m != nil {
		return m.OperateOffset
	}
	return 0
}

func (m *SluitemConfig_SluitemRuntime) GetRelayOperate() []int32 {
	if m != nil {
		return m.RelayOperate
	}
	return nil
}

func (m *SluitemConfig_SluitemRuntime) GetPwmLoop() []int32 {
	if m != nil {
		return m.PwmLoop
	}
	return nil
}

func (m *SluitemConfig_SluitemRuntime) GetPwmPower() int32 {
	if m != nil {
		return m.PwmPower
	}
	return 0
}

func (m *SluitemConfig_SluitemRuntime) GetPwmBaudrate() int32 {
	if m != nil {
		return m.PwmBaudrate
	}
	return 0
}

func (m *SluitemConfig_SluitemRuntime) GetRs485Baudrate() int32 {
	if m != nil {
		return m.Rs485Baudrate
	}
	return 0
}

func (m *SluitemConfig_SluitemRuntime) GetRs485Check() int32 {
	if m != nil {
		return m.Rs485Check
	}
	return 0
}

type SluitemReply struct {
	// 开关灯调光操作结果，0-失败，1-成功
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SluitemReply) Reset()         { *m = SluitemReply{} }
func (m *SluitemReply) String() string { return proto.CompactTextString(m) }
func (*SluitemReply) ProtoMessage()    {}
func (*SluitemReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d0ba9a34991f86e, []int{3}
}

func (m *SluitemReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SluitemReply.Unmarshal(m, b)
}
func (m *SluitemReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SluitemReply.Marshal(b, m, deterministic)
}
func (m *SluitemReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SluitemReply.Merge(m, src)
}
func (m *SluitemReply) XXX_Size() int {
	return xxx_messageInfo_SluitemReply.Size(m)
}
func (m *SluitemReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SluitemReply.DiscardUnknown(m)
}

var xxx_messageInfo_SluitemReply proto.InternalMessageInfo

func (m *SluitemReply) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type SluitemData struct {
	// 序号
	CmdIdx int32 `protobuf:"varint,1,opt,name=cmd_idx,json=cmdIdx,proto3" json:"cmd_idx,omitempty"`
	// 型号
	ModelInfo *SluitemData_ModelInfo `protobuf:"bytes,2,opt,name=model_info,json=modelInfo,proto3" json:"model_info,omitempty"`
	// 回路数据(最大4个)
	LightData []*SluitemData_LightData `protobuf:"bytes,3,rep,name=light_data,json=lightData,proto3" json:"light_data,omitempty"`
	// 漏电流
	LeakageCurrent float64 `protobuf:"fixed64,4,opt,name=leakage_current,json=leakageCurrent,proto3" json:"leakage_current,omitempty"`
	// 控制器状态
	SluitemStatus *SluitemData_SluitemStatus `protobuf:"bytes,5,opt,name=sluitem_status,json=sluitemStatus,proto3" json:"sluitem_status,omitempty"`
	// 时钟故障
	TimeFault *SluitemData_TimeFault `protobuf:"bytes,6,opt,name=time_fault,json=timeFault,proto3" json:"time_fault,omitempty"`
	// 自复位次数
	ResetCount int32 `protobuf:"varint,7,opt,name=reset_count,json=resetCount,proto3" json:"reset_count,omitempty"`
	// 时间
	DateTime int64 `protobuf:"varint,8,opt,name=date_time,json=dateTime,proto3" json:"date_time,omitempty"`
	// 控制器运行参数
	SluitemPara *SluitemData_SluitemPara `protobuf:"bytes,9,opt,name=sluitem_para,json=sluitemPara,proto3" json:"sluitem_para,omitempty"`
	// 参考信号接收功率
	Rsrp int64 `protobuf:"varint,10,opt,name=rsrp,proto3" json:"rsrp,omitempty"`
	// 接收信号强度等级
	Rssi int64 `protobuf:"varint,11,opt,name=rssi,proto3" json:"rssi,omitempty"`
	// 信噪比
	Snr int64 `protobuf:"varint,12,opt,name=snr,proto3" json:"snr,omitempty"`
	// 物理小区标识
	Pci int64 `protobuf:"varint,13,opt,name=pci,proto3" json:"pci,omitempty"`
	// 参考信号接收质量
	Rsrq int64 `protobuf:"varint,14,opt,name=rsrq,proto3" json:"rsrq,omitempty"`
	// 终端发射功率
	Txpower int64 `protobuf:"varint,15,opt,name=txpower,proto3" json:"txpower,omitempty"`
	// 频点号
	Earfcn int64 `protobuf:"varint,16,opt,name=earfcn,proto3" json:"earfcn,omitempty"`
	// 信号覆盖等级
	Ecl int32 `protobuf:"varint,17,opt,name=ecl,proto3" json:"ecl,omitempty"`
	// 信号强度值
	Csq int32 `protobuf:"varint,18,opt,name=csq,proto3" json:"csq,omitempty"`
	// 主动上报原因，0-非主动上报，1-上电，2-开关灯状态变化，3-故障发生/消除，4-定时主动上报
	Reson int32 `protobuf:"varint,19,opt,name=reson,proto3" json:"reson,omitempty"`
	// 重连次数
	Retry int32 `protobuf:"varint,20,opt,name=retry,proto3" json:"retry,omitempty"`
	// 日出时间
	Sunrise int32 `protobuf:"varint,21,opt,name=sunrise,proto3" json:"sunrise,omitempty"`
	// 日落时间
	Sunset               int32    `protobuf:"varint,22,opt,name=sunset,proto3" json:"sunset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SluitemData) Reset()         { *m = SluitemData{} }
func (m *SluitemData) String() string { return proto.CompactTextString(m) }
func (*SluitemData) ProtoMessage()    {}
func (*SluitemData) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d0ba9a34991f86e, []int{4}
}

func (m *SluitemData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SluitemData.Unmarshal(m, b)
}
func (m *SluitemData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SluitemData.Marshal(b, m, deterministic)
}
func (m *SluitemData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SluitemData.Merge(m, src)
}
func (m *SluitemData) XXX_Size() int {
	return xxx_messageInfo_SluitemData.Size(m)
}
func (m *SluitemData) XXX_DiscardUnknown() {
	xxx_messageInfo_SluitemData.DiscardUnknown(m)
}

var xxx_messageInfo_SluitemData proto.InternalMessageInfo

func (m *SluitemData) GetCmdIdx() int32 {
	if m != nil {
		return m.CmdIdx
	}
	return 0
}

func (m *SluitemData) GetModelInfo() *SluitemData_ModelInfo {
	if m != nil {
		return m.ModelInfo
	}
	return nil
}

func (m *SluitemData) GetLightData() []*SluitemData_LightData {
	if m != nil {
		return m.LightData
	}
	return nil
}

func (m *SluitemData) GetLeakageCurrent() float64 {
	if m != nil {
		return m.LeakageCurrent
	}
	return 0
}

func (m *SluitemData) GetSluitemStatus() *SluitemData_SluitemStatus {
	if m != nil {
		return m.SluitemStatus
	}
	return nil
}

func (m *SluitemData) GetTimeFault() *SluitemData_TimeFault {
	if m != nil {
		return m.TimeFault
	}
	return nil
}

func (m *SluitemData) GetResetCount() int32 {
	if m != nil {
		return m.ResetCount
	}
	return 0
}

func (m *SluitemData) GetDateTime() int64 {
	if m != nil {
		return m.DateTime
	}
	return 0
}

func (m *SluitemData) GetSluitemPara() *SluitemData_SluitemPara {
	if m != nil {
		return m.SluitemPara
	}
	return nil
}

func (m *SluitemData) GetRsrp() int64 {
	if m != nil {
		return m.Rsrp
	}
	return 0
}

func (m *SluitemData) GetRssi() int64 {
	if m != nil {
		return m.Rssi
	}
	return 0
}

func (m *SluitemData) GetSnr() int64 {
	if m != nil {
		return m.Snr
	}
	return 0
}

func (m *SluitemData) GetPci() int64 {
	if m != nil {
		return m.Pci
	}
	return 0
}

func (m *SluitemData) GetRsrq() int64 {
	if m != nil {
		return m.Rsrq
	}
	return 0
}

func (m *SluitemData) GetTxpower() int64 {
	if m != nil {
		return m.Txpower
	}
	return 0
}

func (m *SluitemData) GetEarfcn() int64 {
	if m != nil {
		return m.Earfcn
	}
	return 0
}

func (m *SluitemData) GetEcl() int32 {
	if m != nil {
		return m.Ecl
	}
	return 0
}

func (m *SluitemData) GetCsq() int32 {
	if m != nil {
		return m.Csq
	}
	return 0
}

func (m *SluitemData) GetReson() int32 {
	if m != nil {
		return m.Reson
	}
	return 0
}

func (m *SluitemData) GetRetry() int32 {
	if m != nil {
		return m.Retry
	}
	return 0
}

func (m *SluitemData) GetSunrise() int32 {
	if m != nil {
		return m.Sunrise
	}
	return 0
}

func (m *SluitemData) GetSunset() int32 {
	if m != nil {
		return m.Sunset
	}
	return 0
}

type SluitemData_ModelInfo struct {
	// 控制器回路数量
	SluitemLoop int32 `protobuf:"varint,1,opt,name=sluitem_loop,json=sluitemLoop,proto3" json:"sluitem_loop,omitempty"`
	// 节能方式 0-无控制，1-只有开关灯，2-一档节能，3-二档节能，4-RS485，5-PWM，6-0~10V
	PowerSaving int32 `protobuf:"varint,2,opt,name=power_saving,json=powerSaving,proto3" json:"power_saving,omitempty"`
	// 漏电流测量 0-无，1-有
	HasLeakage int32 `protobuf:"varint,3,opt,name=has_leakage,json=hasLeakage,proto3" json:"has_leakage,omitempty"`
	// 温度采集 0-无，1-有
	HasTemperature int32 `protobuf:"varint,4,opt,name=has_temperature,json=hasTemperature,proto3" json:"has_temperature,omitempty"`
	// 时钟 0-无，1-有
	HasTimer int32 `protobuf:"varint,5,opt,name=has_timer,json=hasTimer,proto3" json:"has_timer,omitempty"`
	// 型号 0-unknow
	Model int32 `protobuf:"varint,6,opt,name=model,proto3" json:"model,omitempty"`
	// 字符串型号
	SluitemType          string   `protobuf:"bytes,7,opt,name=sluitem_type,json=sluitemType,proto3" json:"sluitem_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SluitemData_ModelInfo) Reset()         { *m = SluitemData_ModelInfo{} }
func (m *SluitemData_ModelInfo) String() string { return proto.CompactTextString(m) }
func (*SluitemData_ModelInfo) ProtoMessage()    {}
func (*SluitemData_ModelInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d0ba9a34991f86e, []int{4, 0}
}

func (m *SluitemData_ModelInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SluitemData_ModelInfo.Unmarshal(m, b)
}
func (m *SluitemData_ModelInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SluitemData_ModelInfo.Marshal(b, m, deterministic)
}
func (m *SluitemData_ModelInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SluitemData_ModelInfo.Merge(m, src)
}
func (m *SluitemData_ModelInfo) XXX_Size() int {
	return xxx_messageInfo_SluitemData_ModelInfo.Size(m)
}
func (m *SluitemData_ModelInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SluitemData_ModelInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SluitemData_ModelInfo proto.InternalMessageInfo

func (m *SluitemData_ModelInfo) GetSluitemLoop() int32 {
	if m != nil {
		return m.SluitemLoop
	}
	return 0
}

func (m *SluitemData_ModelInfo) GetPowerSaving() int32 {
	if m != nil {
		return m.PowerSaving
	}
	return 0
}

func (m *SluitemData_ModelInfo) GetHasLeakage() int32 {
	if m != nil {
		return m.HasLeakage
	}
	return 0
}

func (m *SluitemData_ModelInfo) GetHasTemperature() int32 {
	if m != nil {
		return m.HasTemperature
	}
	return 0
}

func (m *SluitemData_ModelInfo) GetHasTimer() int32 {
	if m != nil {
		return m.HasTimer
	}
	return 0
}

func (m *SluitemData_ModelInfo) GetModel() int32 {
	if m != nil {
		return m.Model
	}
	return 0
}

func (m *SluitemData_ModelInfo) GetSluitemType() string {
	if m != nil {
		return m.SluitemType
	}
	return ""
}

type SluitemData_LightData struct {
	// 电压
	Voltage float64 `protobuf:"fixed64,1,opt,name=voltage,proto3" json:"voltage,omitempty"`
	// 电流
	Current float64 `protobuf:"fixed64,2,opt,name=current,proto3" json:"current,omitempty"`
	// 有功功率
	ActivePower float64 `protobuf:"fixed64,3,opt,name=active_power,json=activePower,proto3" json:"active_power,omitempty"`
	// 无功功率
	ReactivePower float64 `protobuf:"fixed64,4,opt,name=reactive_power,json=reactivePower,proto3" json:"reactive_power,omitempty"`
	// 视在功率
	ApparentPower float64 `protobuf:"fixed64,5,opt,name=apparent_power,json=apparentPower,proto3" json:"apparent_power,omitempty"`
	// 电量
	Electricity float64 `protobuf:"fixed64,6,opt,name=electricity,proto3" json:"electricity,omitempty"`
	// 运行时间
	ActiveTime float64 `protobuf:"fixed64,7,opt,name=active_time,json=activeTime,proto3" json:"active_time,omitempty"`
	// 灯状态
	LightStatus *SluitemData_LightStatus `protobuf:"bytes,8,opt,name=light_status,json=lightStatus,proto3" json:"light_status,omitempty"`
	// 节能档位
	PowerLevel int32 `protobuf:"varint,9,opt,name=power_level,json=powerLevel,proto3" json:"power_level,omitempty"`
	// 控制器上电开灯 true-开灯，false-关灯
	SluitemPowerTurnon int32 `protobuf:"varint,10,opt,name=sluitem_power_turnon,json=sluitemPowerTurnon,proto3" json:"sluitem_power_turnon,omitempty"`
	// 1-4回路额定功率
	RatedPower           int32    `protobuf:"varint,11,opt,name=rated_power,json=ratedPower,proto3" json:"rated_power,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SluitemData_LightData) Reset()         { *m = SluitemData_LightData{} }
func (m *SluitemData_LightData) String() string { return proto.CompactTextString(m) }
func (*SluitemData_LightData) ProtoMessage()    {}
func (*SluitemData_LightData) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d0ba9a34991f86e, []int{4, 1}
}

func (m *SluitemData_LightData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SluitemData_LightData.Unmarshal(m, b)
}
func (m *SluitemData_LightData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SluitemData_LightData.Marshal(b, m, deterministic)
}
func (m *SluitemData_LightData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SluitemData_LightData.Merge(m, src)
}
func (m *SluitemData_LightData) XXX_Size() int {
	return xxx_messageInfo_SluitemData_LightData.Size(m)
}
func (m *SluitemData_LightData) XXX_DiscardUnknown() {
	xxx_messageInfo_SluitemData_LightData.DiscardUnknown(m)
}

var xxx_messageInfo_SluitemData_LightData proto.InternalMessageInfo

func (m *SluitemData_LightData) GetVoltage() float64 {
	if m != nil {
		return m.Voltage
	}
	return 0
}

func (m *SluitemData_LightData) GetCurrent() float64 {
	if m != nil {
		return m.Current
	}
	return 0
}

func (m *SluitemData_LightData) GetActivePower() float64 {
	if m != nil {
		return m.ActivePower
	}
	return 0
}

func (m *SluitemData_LightData) GetReactivePower() float64 {
	if m != nil {
		return m.ReactivePower
	}
	return 0
}

func (m *SluitemData_LightData) GetApparentPower() float64 {
	if m != nil {
		return m.ApparentPower
	}
	return 0
}

func (m *SluitemData_LightData) GetElectricity() float64 {
	if m != nil {
		return m.Electricity
	}
	return 0
}

func (m *SluitemData_LightData) GetActiveTime() float64 {
	if m != nil {
		return m.ActiveTime
	}
	return 0
}

func (m *SluitemData_LightData) GetLightStatus() *SluitemData_LightStatus {
	if m != nil {
		return m.LightStatus
	}
	return nil
}

func (m *SluitemData_LightData) GetPowerLevel() int32 {
	if m != nil {
		return m.PowerLevel
	}
	return 0
}

func (m *SluitemData_LightData) GetSluitemPowerTurnon() int32 {
	if m != nil {
		return m.SluitemPowerTurnon
	}
	return 0
}

func (m *SluitemData_LightData) GetRatedPower() int32 {
	if m != nil {
		return m.RatedPower
	}
	return 0
}

type SluitemData_LightStatus struct {
	// 灯具漏电 0-正常，1-漏电
	Leakage int32 `protobuf:"varint,1,opt,name=leakage,proto3" json:"leakage,omitempty"`
	// 故障 0-正常，1-光源故障，2-补偿电容故障，3-意外灭灯，4-意外亮灯，5-自熄灯
	Fault int32 `protobuf:"varint,2,opt,name=fault,proto3" json:"fault,omitempty"`
	// 工作状态 0-正常亮灯，1-保留，2-调光节能，3-关灯
	WorkingOn            int32    `protobuf:"varint,3,opt,name=working_on,json=workingOn,proto3" json:"working_on,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SluitemData_LightStatus) Reset()         { *m = SluitemData_LightStatus{} }
func (m *SluitemData_LightStatus) String() string { return proto.CompactTextString(m) }
func (*SluitemData_LightStatus) ProtoMessage()    {}
func (*SluitemData_LightStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d0ba9a34991f86e, []int{4, 2}
}

func (m *SluitemData_LightStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SluitemData_LightStatus.Unmarshal(m, b)
}
func (m *SluitemData_LightStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SluitemData_LightStatus.Marshal(b, m, deterministic)
}
func (m *SluitemData_LightStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SluitemData_LightStatus.Merge(m, src)
}
func (m *SluitemData_LightStatus) XXX_Size() int {
	return xxx_messageInfo_SluitemData_LightStatus.Size(m)
}
func (m *SluitemData_LightStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_SluitemData_LightStatus.DiscardUnknown(m)
}

var xxx_messageInfo_SluitemData_LightStatus proto.InternalMessageInfo

func (m *SluitemData_LightStatus) GetLeakage() int32 {
	if m != nil {
		return m.Leakage
	}
	return 0
}

func (m *SluitemData_LightStatus) GetFault() int32 {
	if m != nil {
		return m.Fault
	}
	return 0
}

func (m *SluitemData_LightStatus) GetWorkingOn() int32 {
	if m != nil {
		return m.WorkingOn
	}
	return 0
}

type SluitemData_SluitemStatus struct {
	// flash故障 0-正常 1-故障
	FlashFault int32 `protobuf:"varint,1,opt,name=flash_fault,json=flashFault,proto3" json:"flash_fault,omitempty"`
	// 主动报警禁止 0-正常 1-禁止
	EnableAlarm          int32    `protobuf:"varint,2,opt,name=enable_alarm,json=enableAlarm,proto3" json:"enable_alarm,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SluitemData_SluitemStatus) Reset()         { *m = SluitemData_SluitemStatus{} }
func (m *SluitemData_SluitemStatus) String() string { return proto.CompactTextString(m) }
func (*SluitemData_SluitemStatus) ProtoMessage()    {}
func (*SluitemData_SluitemStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d0ba9a34991f86e, []int{4, 3}
}

func (m *SluitemData_SluitemStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SluitemData_SluitemStatus.Unmarshal(m, b)
}
func (m *SluitemData_SluitemStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SluitemData_SluitemStatus.Marshal(b, m, deterministic)
}
func (m *SluitemData_SluitemStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SluitemData_SluitemStatus.Merge(m, src)
}
func (m *SluitemData_SluitemStatus) XXX_Size() int {
	return xxx_messageInfo_SluitemData_SluitemStatus.Size(m)
}
func (m *SluitemData_SluitemStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_SluitemData_SluitemStatus.DiscardUnknown(m)
}

var xxx_messageInfo_SluitemData_SluitemStatus proto.InternalMessageInfo

func (m *SluitemData_SluitemStatus) GetFlashFault() int32 {
	if m != nil {
		return m.FlashFault
	}
	return 0
}

func (m *SluitemData_SluitemStatus) GetEnableAlarm() int32 {
	if m != nil {
		return m.EnableAlarm
	}
	return 0
}

type SluitemData_TimeFault struct {
	// 本地时钟故障 0-正常 1-故障
	ClockFault int32 `protobuf:"varint,1,opt,name=clock_fault,json=clockFault,proto3" json:"clock_fault,omitempty"`
	// 本地时钟超差故障 0-正常 1-故障
	ClockOutFault int32 `protobuf:"varint,2,opt,name=clock_out_fault,json=clockOutFault,proto3" json:"clock_out_fault,omitempty"`
	// 校时超差故障 0-正常 1-故障
	ClockOutAlarm        int32    `protobuf:"varint,3,opt,name=clock_out_alarm,json=clockOutAlarm,proto3" json:"clock_out_alarm,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SluitemData_TimeFault) Reset()         { *m = SluitemData_TimeFault{} }
func (m *SluitemData_TimeFault) String() string { return proto.CompactTextString(m) }
func (*SluitemData_TimeFault) ProtoMessage()    {}
func (*SluitemData_TimeFault) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d0ba9a34991f86e, []int{4, 4}
}

func (m *SluitemData_TimeFault) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SluitemData_TimeFault.Unmarshal(m, b)
}
func (m *SluitemData_TimeFault) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SluitemData_TimeFault.Marshal(b, m, deterministic)
}
func (m *SluitemData_TimeFault) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SluitemData_TimeFault.Merge(m, src)
}
func (m *SluitemData_TimeFault) XXX_Size() int {
	return xxx_messageInfo_SluitemData_TimeFault.Size(m)
}
func (m *SluitemData_TimeFault) XXX_DiscardUnknown() {
	xxx_messageInfo_SluitemData_TimeFault.DiscardUnknown(m)
}

var xxx_messageInfo_SluitemData_TimeFault proto.InternalMessageInfo

func (m *SluitemData_TimeFault) GetClockFault() int32 {
	if m != nil {
		return m.ClockFault
	}
	return 0
}

func (m *SluitemData_TimeFault) GetClockOutFault() int32 {
	if m != nil {
		return m.ClockOutFault
	}
	return 0
}

func (m *SluitemData_TimeFault) GetClockOutAlarm() int32 {
	if m != nil {
		return m.ClockOutAlarm
	}
	return 0
}

type SluitemData_SluitemPara struct {
	// 经度
	Longitude float64 `protobuf:"fixed64,1,opt,name=longitude,proto3" json:"longitude,omitempty"`
	// 纬度
	Latitude float64 `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	// 是否允许主报 0-允许 1-不允许
	HasEnableAlarm int32 `protobuf:"varint,3,opt,name=has_enable_alarm,json=hasEnableAlarm,proto3" json:"has_enable_alarm,omitempty"`
	// 是否投运 0-投运 1-停运
	IsRunning int32 `protobuf:"varint,4,opt,name=is_running,json=isRunning,proto3" json:"is_running,omitempty"`
	// 主动报警间隔 单位分钟 0表示30分钟
	AlarmInterval        int32    `protobuf:"varint,5,opt,name=alarm_interval,json=alarmInterval,proto3" json:"alarm_interval,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SluitemData_SluitemPara) Reset()         { *m = SluitemData_SluitemPara{} }
func (m *SluitemData_SluitemPara) String() string { return proto.CompactTextString(m) }
func (*SluitemData_SluitemPara) ProtoMessage()    {}
func (*SluitemData_SluitemPara) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d0ba9a34991f86e, []int{4, 5}
}

func (m *SluitemData_SluitemPara) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SluitemData_SluitemPara.Unmarshal(m, b)
}
func (m *SluitemData_SluitemPara) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SluitemData_SluitemPara.Marshal(b, m, deterministic)
}
func (m *SluitemData_SluitemPara) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SluitemData_SluitemPara.Merge(m, src)
}
func (m *SluitemData_SluitemPara) XXX_Size() int {
	return xxx_messageInfo_SluitemData_SluitemPara.Size(m)
}
func (m *SluitemData_SluitemPara) XXX_DiscardUnknown() {
	xxx_messageInfo_SluitemData_SluitemPara.DiscardUnknown(m)
}

var xxx_messageInfo_SluitemData_SluitemPara proto.InternalMessageInfo

func (m *SluitemData_SluitemPara) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *SluitemData_SluitemPara) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *SluitemData_SluitemPara) GetHasEnableAlarm() int32 {
	if m != nil {
		return m.HasEnableAlarm
	}
	return 0
}

func (m *SluitemData_SluitemPara) GetIsRunning() int32 {
	if m != nil {
		return m.IsRunning
	}
	return 0
}

func (m *SluitemData_SluitemPara) GetAlarmInterval() int32 {
	if m != nil {
		return m.AlarmInterval
	}
	return 0
}

func init() {
	proto.RegisterType((*MsgNBiot)(nil), "wlst.nbiot.MsgNBiot")
	proto.RegisterType((*MsgNBOpen)(nil), "wlst.nbiot.MsgNBOpen")
	proto.RegisterType((*SluitemConfig)(nil), "wlst.nbiot.SluitemConfig")
	proto.RegisterType((*SluitemConfig_DataMark)(nil), "wlst.nbiot.SluitemConfig.Data_mark")
	proto.RegisterType((*SluitemConfig_SetMark)(nil), "wlst.nbiot.SluitemConfig.Set_mark")
	proto.RegisterType((*SluitemConfig_SluitemPara)(nil), "wlst.nbiot.SluitemConfig.Sluitem_para")
	proto.RegisterType((*SluitemConfig_SluitemVer)(nil), "wlst.nbiot.SluitemConfig.Sluitem_ver")
	proto.RegisterType((*SluitemConfig_SluitemSunriseset)(nil), "wlst.nbiot.SluitemConfig.Sluitem_sunriseset")
	proto.RegisterType((*SluitemConfig_SluitemRuntime)(nil), "wlst.nbiot.SluitemConfig.Sluitem_runtime")
	proto.RegisterType((*SluitemReply)(nil), "wlst.nbiot.SluitemReply")
	proto.RegisterType((*SluitemData)(nil), "wlst.nbiot.SluitemData")
	proto.RegisterType((*SluitemData_ModelInfo)(nil), "wlst.nbiot.SluitemData.Model_info")
	proto.RegisterType((*SluitemData_LightData)(nil), "wlst.nbiot.SluitemData.Light_data")
	proto.RegisterType((*SluitemData_LightStatus)(nil), "wlst.nbiot.SluitemData.Light_status")
	proto.RegisterType((*SluitemData_SluitemStatus)(nil), "wlst.nbiot.SluitemData.Sluitem_status")
	proto.RegisterType((*SluitemData_TimeFault)(nil), "wlst.nbiot.SluitemData.Time_fault")
	proto.RegisterType((*SluitemData_SluitemPara)(nil), "wlst.nbiot.SluitemData.Sluitem_para")
}

func init() { proto.RegisterFile("msg_nb.proto", fileDescriptor_7d0ba9a34991f86e) }

var fileDescriptor_7d0ba9a34991f86e = []byte{
	// 1836 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x58, 0xcd, 0x6e, 0x1b, 0xc9,
	0x11, 0xce, 0x88, 0xa2, 0xc8, 0xa9, 0x21, 0x25, 0xb9, 0x63, 0xaf, 0xc7, 0xdc, 0x18, 0x92, 0xe5,
	0xd8, 0xd6, 0x02, 0x89, 0x10, 0x38, 0x9b, 0x20, 0x48, 0xb0, 0xc0, 0x5a, 0xda, 0xf5, 0x46, 0x80,
	0x64, 0x2d, 0x46, 0x42, 0x2e, 0x41, 0x30, 0x68, 0x0d, 0x9b, 0xd4, 0x40, 0xf3, 0xe7, 0x9e, 0x1e,
	0xca, 0x3a, 0xe4, 0x96, 0x43, 0x4e, 0x39, 0xe5, 0x94, 0xb7, 0x48, 0x72, 0xc9, 0x23, 0xe4, 0x79,
	0xf2, 0x04, 0x41, 0x55, 0xf5, 0xfc, 0x50, 0x3f, 0xf6, 0xde, 0xd8, 0x5f, 0x55, 0x57, 0xd7, 0xd4,
	0xcf, 0x57, 0x25, 0xc1, 0x28, 0x2d, 0xe7, 0x61, 0x76, 0xbe, 0x57, 0xe8, 0xdc, 0xe4, 0x02, 0xae,
	0x92, 0xd2, 0xec, 0x65, 0xe7, 0x71, 0x6e, 0x76, 0xfe, 0xea, 0xc0, 0xf0, 0xb8, 0x9c, 0xbf, 0xdb,
	0x8f, 0x73, 0x23, 0x1e, 0xc3, 0x20, 0x4a, 0xa7, 0x61, 0x3c, 0xfd, 0xe0, 0x3b, 0xdb, 0xce, 0x6e,
	0x2f, 0x58, 0x8b, 0xd2, 0xe9, 0xe1, 0xf4, 0x83, 0x78, 0x02, 0x43, 0x14, 0x64, 0x32, 0x55, 0xfe,
	0xca, 0xb6, 0xb3, 0xeb, 0x06, 0xa8, 0xf8, 0x4e, 0xa6, 0xaa, 0x16, 0xcd, 0x12, 0x39, 0xf7, 0x7b,
	0xdb, 0xce, 0x6e, 0x9f, 0x44, 0x6f, 0x13, 0x39, 0x17, 0x02, 0x56, 0xe3, 0x54, 0xc5, 0xfe, 0xea,
	0x76, 0x6f, 0xb7, 0x17, 0xd0, 0x6f, 0x54, 0xd7, 0xf2, 0x2a, 0x9c, 0x4a, 0x23, 0xfd, 0xfe, 0x76,
	0x0f, 0xd5, 0xb5, 0xbc, 0xfa, 0x46, 0x1a, 0xb9, 0xf3, 0xef, 0x15, 0x70, 0xc9, 0x95, 0x93, 0x42,
	0x65, 0xcd, 0x65, 0x76, 0x84, 0x2f, 0x3f, 0x05, 0x98, 0x9a, 0x50, 0xab, 0x48, 0xc5, 0x0b, 0x76,
	0xa4, 0x17, 0xb8, 0x53, 0x13, 0x30, 0x20, 0x3e, 0x07, 0x17, 0xed, 0x86, 0xe6, 0xba, 0x50, 0xd6,
	0x97, 0x21, 0x02, 0x67, 0xd7, 0x05, 0xf9, 0x49, 0xc2, 0x28, 0x9d, 0xfa, 0x2e, 0x7f, 0x02, 0x9e,
	0x0f, 0xd2, 0xa9, 0xf8, 0x2d, 0x8c, 0xca, 0xa4, 0x8a, 0x8d, 0x4a, 0xd9, 0xaf, 0xd5, 0x6d, 0x67,
	0xd7, 0x7b, 0xfd, 0x78, 0xaf, 0x0d, 0xd3, 0xde, 0x29, 0xcb, 0xd1, 0xcf, 0xc0, 0x2b, 0xdb, 0x83,
	0xf8, 0x0a, 0xc6, 0xf5, 0x5d, 0xad, 0x8a, 0xe4, 0xda, 0xef, 0xd3, 0x65, 0xff, 0x8e, 0xcb, 0x01,
	0xca, 0x83, 0xfa, 0x29, 0x3a, 0x89, 0xaf, 0x61, 0xbd, 0xbe, 0x1e, 0xe5, 0xd9, 0x2c, 0x9e, 0xfb,
	0x6b, 0x74, 0xff, 0xc9, 0x1d, 0xf7, 0x0f, 0x48, 0x21, 0xa8, 0xdf, 0xe3, 0xe3, 0xce, 0x7f, 0x37,
	0x61, 0xbc, 0xa4, 0x70, 0x33, 0x8b, 0xfd, 0x26, 0x8b, 0x5b, 0x50, 0xbb, 0x4e, 0x42, 0x8e, 0x1f,
	0x58, 0x08, 0x15, 0xbe, 0xb6, 0x01, 0x4c, 0xa5, 0xbe, 0xb4, 0x51, 0x78, 0x7e, 0xaf, 0x23, 0x7b,
	0xdf, 0xd4, 0xaa, 0x1c, 0xe5, 0x63, 0xa9, 0x2f, 0x31, 0x43, 0x49, 0x9e, 0x17, 0x61, 0x94, 0x57,
	0x99, 0xa1, 0x58, 0xf4, 0x03, 0x17, 0x91, 0x03, 0x04, 0xc4, 0xb3, 0x36, 0xd2, 0x26, 0x4e, 0x95,
	0x3f, 0x20, 0x17, 0x6a, 0xaf, 0xce, 0xe2, 0x54, 0x89, 0xc3, 0x56, 0xa5, 0x90, 0x5a, 0xfa, 0x43,
	0x72, 0xe3, 0xe5, 0xfd, 0x6e, 0x9c, 0x76, 0xb4, 0x1b, 0x53, 0xdf, 0x4b, 0x2d, 0xc5, 0xdb, 0xf6,
	0x7b, 0x17, 0x4a, 0xfb, 0x40, 0x96, 0x5e, 0x7c, 0xda, 0xd2, 0x42, 0xe9, 0x26, 0x2c, 0x7f, 0x50,
	0x5a, 0xfc, 0x11, 0x44, 0x6d, 0xa7, 0xac, 0x32, 0x1d, 0x97, 0xaa, 0x54, 0xc6, 0xf7, 0xc8, 0xdc,
	0xcf, 0x3e, 0x6d, 0xae, 0xbd, 0x13, 0x3c, 0xb0, 0x76, 0x4e, 0x1b, 0x48, 0x04, 0xb0, 0xd1, 0x14,
	0x50, 0x95, 0x51, 0x54, 0x46, 0xdb, 0xbd, 0x5d, 0xef, 0xf5, 0x17, 0x9f, 0xb6, 0x6c, 0x2f, 0x04,
	0x75, 0x0d, 0x05, 0x7c, 0x16, 0x9f, 0xc1, 0x5a, 0x69, 0xa4, 0xa9, 0x4a, 0x7f, 0x9d, 0x0b, 0x80,
	0x4f, 0xe2, 0x2b, 0x18, 0x96, 0xca, 0x70, 0x7a, 0x37, 0xc8, 0xfd, 0x9d, 0x8f, 0x3c, 0x62, 0x35,
	0x83, 0x41, 0xa9, 0x0c, 0x26, 0x77, 0xf2, 0x2f, 0x07, 0xdc, 0x26, 0xe9, 0x98, 0x6a, 0xad, 0xe4,
	0x94, 0x12, 0xa9, 0xa9, 0x98, 0xfa, 0x81, 0x8b, 0x08, 0xa6, 0x51, 0x63, 0x33, 0x92, 0x58, 0xea,
	0x79, 0x59, 0x37, 0x23, 0x02, 0x6f, 0xf4, 0xbc, 0x24, 0x16, 0x40, 0x21, 0xa6, 0x85, 0x8b, 0x64,
	0x80, 0x67, 0x0c, 0xf6, 0x2b, 0xd8, 0x20, 0x51, 0x27, 0xd2, 0x6b, 0xa4, 0xb1, 0x8e, 0x70, 0x27,
	0x70, 0x2f, 0x60, 0xbd, 0x79, 0xdf, 0xc8, 0xf3, 0x84, 0xab, 0xa9, 0x1f, 0x8c, 0x6b, 0x1f, 0x08,
	0x9c, 0xfc, 0xc5, 0x81, 0x61, 0xfd, 0x29, 0xe8, 0x14, 0x06, 0x80, 0x5d, 0xe6, 0xe6, 0xc0, 0x88,
	0xb0, 0xc7, 0x4f, 0x38, 0x3a, 0xe4, 0x30, 0x7f, 0x0e, 0x7e, 0x39, 0xf9, 0x6b, 0xef, 0x69, 0x72,
	0x67, 0xb5, 0xb9, 0x17, 0x90, 0x23, 0xcf, 0x61, 0x5c, 0x1b, 0x65, 0x3f, 0xf8, 0x8b, 0x46, 0xd6,
	0x30, 0xbb, 0xf1, 0xb7, 0x1e, 0x8c, 0xba, 0x95, 0x8a, 0xcd, 0x38, 0xcd, 0x53, 0x19, 0x67, 0xcc,
	0xaa, 0xec, 0x0c, 0x30, 0x44, 0xc4, 0xfa, 0xa2, 0xa5, 0x06, 0x9b, 0x4c, 0x76, 0xaa, 0xee, 0xff,
	0x53, 0xce, 0xe9, 0x2f, 0xe0, 0x61, 0xad, 0xa6, 0x32, 0x7c, 0x2a, 0x94, 0x89, 0xd4, 0xa9, 0x0d,
	0x79, 0x5d, 0xb8, 0xdf, 0x92, 0xe8, 0x0d, 0x4a, 0xc4, 0x97, 0xed, 0x8d, 0x22, 0xbf, 0x52, 0x3a,
	0x34, 0x95, 0xce, 0xf2, 0x8c, 0x68, 0xba, 0xbf, 0xbf, 0xb2, 0xe9, 0x34, 0xb7, 0xbe, 0x47, 0xf1,
	0x19, 0x49, 0xc5, 0x17, 0xad, 0x3b, 0x0b, 0x15, 0x99, 0x5c, 0x33, 0x7d, 0x93, 0xfe, 0xb8, 0x69,
	0x16, 0x14, 0x88, 0x9f, 0x80, 0x9b, 0xe4, 0xd9, 0x3c, 0x36, 0xd5, 0x54, 0x51, 0xf2, 0x9c, 0xa0,
	0x05, 0xc4, 0x04, 0x86, 0x89, 0x34, 0x2c, 0x1c, 0x90, 0xb0, 0x39, 0x8b, 0xe7, 0xe0, 0x69, 0x69,
	0xd4, 0x94, 0x1d, 0xf3, 0x87, 0xcd, 0x0b, 0x40, 0x30, 0xf9, 0x83, 0x24, 0x52, 0x15, 0x49, 0x9c,
	0x5d, 0xda, 0x3c, 0xba, 0xf4, 0xa5, 0x1e, 0x63, 0x9c, 0xca, 0x56, 0x85, 0x49, 0x19, 0xba, 0x2a,
	0xc4, 0xbc, 0x93, 0xbf, 0xaf, 0x80, 0xd7, 0x69, 0xf8, 0x2e, 0x35, 0x21, 0x5f, 0xd9, 0x84, 0xd4,
	0x04, 0x72, 0x94, 0xe7, 0x05, 0x26, 0x5a, 0x65, 0x4a, 0xcf, 0xaf, 0xc3, 0x52, 0x2e, 0xe2, 0x6c,
	0x6e, 0x13, 0x32, 0x62, 0xf0, 0x94, 0x30, 0xf1, 0x6b, 0x78, 0xac, 0x12, 0x15, 0x19, 0x1d, 0x47,
	0x61, 0xa2, 0xe4, 0xa5, 0x9c, 0xab, 0x30, 0xcd, 0xa7, 0x55, 0x52, 0x8f, 0xa4, 0x47, 0xb5, 0xf8,
	0x88, 0xa5, 0xc7, 0x24, 0x14, 0x3f, 0x07, 0x61, 0x54, 0x5a, 0x28, 0x2d, 0x4d, 0xa5, 0x9b, 0x2b,
	0x5c, 0x6b, 0x0f, 0x3a, 0x12, 0xab, 0xfe, 0x0c, 0x46, 0xf4, 0xf5, 0xb5, 0x22, 0xd7, 0x9c, 0x47,
	0x58, 0xab, 0xd2, 0x90, 0x2d, 0x4e, 0xc4, 0x35, 0x9a, 0x7a, 0x0d, 0xd9, 0xe2, 0x50, 0xdc, 0x84,
	0x1e, 0xb6, 0xe0, 0x80, 0x24, 0xf8, 0x73, 0xf2, 0x16, 0xc4, 0x6d, 0xde, 0x12, 0x3e, 0x0c, 0xec,
	0xc9, 0xc6, 0xa5, 0x3e, 0x12, 0xd5, 0x54, 0x19, 0xb6, 0xc5, 0x8a, 0xa5, 0x1a, 0x3a, 0x4d, 0xfe,
	0xd9, 0x83, 0x8d, 0x1b, 0x34, 0xb5, 0x3c, 0x9f, 0x9d, 0x1b, 0xf3, 0x79, 0x0b, 0xbc, 0xbc, 0x32,
	0x45, 0x65, 0x58, 0xcc, 0xd6, 0x80, 0x21, 0x52, 0x78, 0x06, 0xa3, 0x9c, 0x82, 0xa0, 0xba, 0x03,
	0xde, 0xb3, 0x18, 0xa9, 0x3c, 0x07, 0x6f, 0x8a, 0x72, 0x6e, 0x84, 0x4e, 0x41, 0x03, 0xc2, 0xdc,
	0x03, 0x4b, 0x76, 0x90, 0x6d, 0xfb, 0xcb, 0x76, 0x62, 0x6e, 0xbd, 0x5a, 0x25, 0x9f, 0xcd, 0x5a,
	0x0a, 0x1a, 0x5b, 0xf4, 0x84, 0x40, 0xf1, 0x0a, 0xc6, 0x5a, 0x25, 0xf2, 0x3a, 0xb4, 0xb0, 0x3f,
	0x68, 0x1e, 0x1c, 0x91, 0xe0, 0x84, 0x71, 0xf1, 0x14, 0x86, 0xc5, 0x95, 0xad, 0xab, 0xb6, 0xa6,
	0x07, 0xc5, 0x15, 0xd7, 0xd5, 0xe7, 0xe0, 0xa2, 0x98, 0x6b, 0x9e, 0xab, 0x19, 0xf5, 0x9b, 0x6a,
	0x47, 0xe1, 0xb9, 0xac, 0xa6, 0xf4, 0x86, 0x2d, 0xe5, 0xe2, 0x2a, 0xdd, 0xb7, 0x10, 0x31, 0x61,
	0xf9, 0xe5, 0x6f, 0x7e, 0xd5, 0x2a, 0x79, 0x96, 0x09, 0x11, 0x6d, 0xd4, 0xb6, 0xc0, 0x63, 0xb5,
	0xe8, 0x42, 0x45, 0x97, 0xfe, 0x88, 0x23, 0x4c, 0xd0, 0x01, 0x22, 0x3b, 0x2f, 0x1b, 0x8a, 0xe2,
	0xe5, 0xa4, 0x1d, 0x23, 0x4e, 0x77, 0x8c, 0xec, 0xfc, 0x63, 0xa3, 0x69, 0x1d, 0xda, 0x81, 0xee,
	0x5d, 0x38, 0xde, 0x00, 0xa4, 0xf9, 0x54, 0x25, 0x61, 0x9c, 0xcd, 0x72, 0x4a, 0xe9, 0xdd, 0x13,
	0x07, 0xad, 0xec, 0x1d, 0x37, 0x9a, 0x81, 0x4b, 0xb7, 0x0e, 0xb3, 0x59, 0x8e, 0x26, 0x92, 0x78,
	0x7e, 0x61, 0x78, 0x33, 0xeb, 0xd1, 0x64, 0xbc, 0xd7, 0xc4, 0x51, 0xa3, 0x19, 0xb8, 0x74, 0x8b,
	0xdc, 0x7b, 0x05, 0x1b, 0x75, 0x23, 0x46, 0x95, 0xd6, 0x2a, 0x63, 0x0a, 0x77, 0x82, 0x75, 0x0b,
	0x1f, 0x30, 0x2a, 0x8e, 0x6f, 0x31, 0x6e, 0xff, 0xde, 0xe5, 0x83, 0xde, 0x3b, 0x5d, 0xd2, 0xbe,
	0xc9, 0xcc, 0x6f, 0x00, 0xb0, 0xc0, 0xc2, 0x99, 0xac, 0x12, 0x63, 0xf7, 0xba, 0x7b, 0x5d, 0x3f,
	0x6b, 0x34, 0x03, 0x17, 0x6f, 0xbd, 0xc5, 0x9f, 0x94, 0x32, 0x6c, 0x40, 0xbb, 0x4f, 0x0d, 0x6c,
	0xca, 0x10, 0xe2, 0x85, 0x8a, 0x5b, 0xca, 0x56, 0xf2, 0x90, 0xb6, 0x29, 0x6c, 0x29, 0x2e, 0xe3,
	0xef, 0x6e, 0xac, 0x52, 0x2e, 0xb9, 0xf0, 0xd3, 0x4f, 0x7d, 0xcd, 0xed, 0x45, 0x4a, 0xc0, 0xaa,
	0x2e, 0x75, 0x41, 0xb5, 0xd7, 0x0b, 0xe8, 0x37, 0x63, 0x65, 0x4c, 0xa5, 0x46, 0x58, 0x19, 0x23,
	0x9d, 0x94, 0x99, 0xa6, 0xca, 0xea, 0x05, 0xf8, 0x13, 0x91, 0x22, 0x8a, 0xfd, 0x31, 0x23, 0x45,
	0x14, 0x5b, 0x5b, 0xef, 0x69, 0x33, 0x61, 0x5b, 0xef, 0x91, 0x5e, 0xcc, 0x07, 0x2e, 0xff, 0x0d,
	0x82, 0xeb, 0x23, 0x96, 0xa0, 0x92, 0x7a, 0x16, 0x65, 0xfe, 0x26, 0xff, 0x41, 0xc2, 0x27, 0xb4,
	0xab, 0xa2, 0xc4, 0x7f, 0x40, 0x01, 0xc1, 0x9f, 0x88, 0x44, 0xe5, 0x7b, 0x5f, 0x30, 0x12, 0x95,
	0xef, 0xc5, 0x43, 0xe8, 0x6b, 0x55, 0xe6, 0x99, 0xff, 0x63, 0xc2, 0xf8, 0xc0, 0xa8, 0xd1, 0xd7,
	0xfe, 0xc3, 0x1a, 0x35, 0xfa, 0xba, 0x4b, 0x70, 0x8f, 0xee, 0x23, 0xb8, 0xcf, 0x96, 0x08, 0xee,
	0x7f, 0x0e, 0x40, 0x5b, 0xb2, 0x3f, 0x64, 0x7c, 0x60, 0x27, 0xd3, 0xbc, 0x5d, 0x9a, 0x1e, 0x1e,
	0x61, 0x76, 0x78, 0x6c, 0x81, 0x77, 0x21, 0xcb, 0x7a, 0x6e, 0x58, 0x8a, 0x83, 0x0b, 0x59, 0xda,
	0x59, 0x81, 0xb5, 0x8c, 0x0a, 0x9d, 0x79, 0x60, 0x47, 0xc4, 0xfa, 0x85, 0x2c, 0xcf, 0x5a, 0x14,
	0x0b, 0x83, 0x14, 0x69, 0x42, 0x32, 0xc5, 0x0d, 0x51, 0x85, 0xc6, 0xe3, 0x43, 0xe8, 0x53, 0x87,
	0x59, 0x5a, 0xe3, 0xc3, 0xad, 0x79, 0x31, 0xb8, 0x35, 0x2f, 0x90, 0xd5, 0xa1, 0x6d, 0x32, 0x8c,
	0xda, 0x22, 0x4f, 0x0c, 0xba, 0xea, 0x50, 0x47, 0xd5, 0x47, 0x94, 0xd4, 0xbd, 0xb6, 0xc2, 0x12,
	0x7b, 0xc4, 0x57, 0x64, 0x64, 0xe2, 0x85, 0xb2, 0x7c, 0xd7, 0x23, 0xb1, 0xc7, 0x18, 0x53, 0x1e,
	0x6f, 0x76, 0x5d, 0x25, 0xee, 0xd7, 0x71, 0x8d, 0x36, 0x6a, 0xb2, 0x28, 0x24, 0x5a, 0xb5, 0x6a,
	0x7d, 0x56, 0xab, 0x51, 0x56, 0xdb, 0x06, 0xaf, 0x9e, 0xb8, 0xb1, 0xb9, 0xb6, 0xfb, 0x48, 0x17,
	0xc2, 0xa8, 0xdb, 0xd7, 0x9a, 0x3f, 0x4a, 0x9c, 0x00, 0x18, 0xaa, 0x1b, 0x89, 0x49, 0xc8, 0xd2,
	0xc2, 0xf0, 0xe3, 0x8d, 0x74, 0xd4, 0xd1, 0x0d, 0x3c, 0xba, 0x69, 0x29, 0x61, 0x0b, 0x38, 0xdd,
	0x61, 0xa2, 0x16, 0x2a, 0xb1, 0x5c, 0x0f, 0x04, 0x1d, 0x21, 0xd2, 0xdd, 0xe6, 0x96, 0x76, 0x33,
	0x58, 0xda, 0xe6, 0xba, 0x7b, 0xd9, 0xd6, 0xf2, 0xca, 0xe4, 0x59, 0x8a, 0x68, 0xd6, 0xa5, 0xc9,
	0x9f, 0x60, 0xd4, 0x75, 0x08, 0x53, 0x53, 0xd7, 0x97, 0x9d, 0xe5, 0xf6, 0x88, 0x65, 0xc1, 0x5c,
	0xc5, 0x95, 0xc9, 0x07, 0xdc, 0xf3, 0xaf, 0x72, 0x7d, 0x19, 0x67, 0xf3, 0x30, 0xcf, 0x6c, 0x49,
	0xba, 0x16, 0x39, 0xc9, 0x26, 0x67, 0xb0, 0xbe, 0x4c, 0x83, 0xe8, 0xd1, 0x2c, 0x91, 0xe5, 0x85,
	0x25, 0x3e, 0xbb, 0xd9, 0x12, 0xc4, 0xac, 0xf6, 0x0c, 0x46, 0x4b, 0xab, 0xaa, 0x6d, 0x04, 0xd5,
	0xee, 0xa8, 0x93, 0x3f, 0x03, 0xb4, 0x8c, 0x88, 0x16, 0xa3, 0x24, 0x8f, 0x2e, 0x97, 0x2d, 0x12,
	0xc4, 0x16, 0x5f, 0xc2, 0x06, 0x2b, 0xe4, 0x95, 0x09, 0xbb, 0xdf, 0x30, 0x26, 0xf8, 0xa4, 0x32,
	0x77, 0xe8, 0x75, 0xf7, 0xe4, 0x46, 0x8f, 0x9f, 0xff, 0x8f, 0x73, 0x63, 0x5b, 0x5f, 0x5a, 0x69,
	0x9d, 0x8f, 0xad, 0xb4, 0x2b, 0x37, 0x56, 0xda, 0x5d, 0xd8, 0xc4, 0x46, 0xbc, 0x63, 0x37, 0xc7,
	0x96, 0xed, 0xee, 0xe5, 0x4f, 0x01, 0xe2, 0x12, 0x97, 0xa5, 0x0c, 0xd9, 0x81, 0xdb, 0xda, 0x8d,
	0xcb, 0x80, 0x01, 0x2a, 0x77, 0xd4, 0x0b, 0xe3, 0xcc, 0x28, 0xbd, 0x90, 0x89, 0x6d, 0xeb, 0x31,
	0xa1, 0x87, 0x16, 0x7c, 0xfd, 0x1d, 0x0c, 0xdf, 0xed, 0x1f, 0xe6, 0x67, 0x07, 0x26, 0x11, 0xbf,
	0x03, 0x97, 0x7e, 0x7f, 0x1b, 0x5d, 0xe4, 0xe2, 0x51, 0xb7, 0x5c, 0x9b, 0xff, 0xb3, 0x4c, 0xee,
	0x86, 0x77, 0x7e, 0xb4, 0xbf, 0xf2, 0x7b, 0xe7, 0x7c, 0x8d, 0xfe, 0x61, 0xf4, 0xcb, 0xff, 0x07,
	0x00, 0x00, 0xff, 0xff, 0xdf, 0x3d, 0x88, 0xc8, 0x40, 0x12, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NBIoTCtlClient is the client API for NBIoTCtl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NBIoTCtlClient interface {
	NBIoTEcho(ctx context.Context, in *MsgNBOpen, opts ...grpc.CallOption) (*MsgNBOpen, error)
}

type nBIoTCtlClient struct {
	cc *grpc.ClientConn
}

func NewNBIoTCtlClient(cc *grpc.ClientConn) NBIoTCtlClient {
	return &nBIoTCtlClient{cc}
}

func (c *nBIoTCtlClient) NBIoTEcho(ctx context.Context, in *MsgNBOpen, opts ...grpc.CallOption) (*MsgNBOpen, error) {
	out := new(MsgNBOpen)
	err := c.cc.Invoke(ctx, "/wlst.nbiot.NBIoTCtl/NBIoTEcho", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NBIoTCtlServer is the server API for NBIoTCtl service.
type NBIoTCtlServer interface {
	NBIoTEcho(context.Context, *MsgNBOpen) (*MsgNBOpen, error)
}

func RegisterNBIoTCtlServer(s *grpc.Server, srv NBIoTCtlServer) {
	s.RegisterService(&_NBIoTCtl_serviceDesc, srv)
}

func _NBIoTCtl_NBIoTEcho_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgNBOpen)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NBIoTCtlServer).NBIoTEcho(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wlst.nbiot.NBIoTCtl/NBIoTEcho",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NBIoTCtlServer).NBIoTEcho(ctx, req.(*MsgNBOpen))
	}
	return interceptor(ctx, in, info, handler)
}

var _NBIoTCtl_serviceDesc = grpc.ServiceDesc{
	ServiceName: "wlst.nbiot.NBIoTCtl",
	HandlerType: (*NBIoTCtlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NBIoTEcho",
			Handler:    _NBIoTCtl_NBIoTEcho_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "msg_nb.proto",
}
